[tool.poetry]
name = "cefweaver"
version = "0.1.0"
description = "GUI toolkit for embedding a Chromium widget in desktop applications"
authors = ["Jiho Lee <search5@gmail.com>"]
readme = ["README.rst", "CHANGELOG.rst", "LICENSE"]
keywords = ["cefpython"]
license = "BSD-3-Clause"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Desktop Environment",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Browsers",
    "Topic :: Multimedia",
    "Topic :: Software Development :: User Interfaces"
]
repository = "https://github.com/search5/cefweaver"
# packages = [{ include = "poetry_cython_example" }]
include = [{ path = "cefweaver/**/*.so", format = "wheel" }]


[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.2"
sphinx = "^7.2.6"
cmake = "^3.28.1"


[build-system]
requires = ["poetry-core", "setuptools", "Cython"]
build-backend = "poetry.core.masonry.api"
