# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

from libc.stdint cimport int16_t, uint16_t, int32_t, uint32_t, int64_t, uint64_t
from libcpp cimport bool as cpp_bool
from libcpp.string cimport string

cdef extern from "include/cef_base.h":
    cdef cppclass CefBaseRefCounted:
        void AddRef() nogil
        cpp_bool Release() nogil

cdef extern from "include/cef_api_hash.h":
    enum: CEF_API_VERSION
    const char* CEF_API_HASH_PLATFORM
    const char* cef_api_hash(int version, int entry)

cdef extern from "include/internal/cef_ptr.h":
    cdef cppclass CefRefPtr[T]:
        CefRefPtr()
        CefRefPtr(T*)
        T* get() nogil

cdef extern from "include/internal/cef_string.h":
    cdef cppclass CefString:
        CefString()
        CefString(const string&)
        string ToString() nogil

cdef extern from "include/internal/cef_types.h":
    ctypedef enum cef_errorcode_t:
        pass
    ctypedef enum cef_log_severity_t:
        pass
    ctypedef enum cef_referrer_policy_t:
        pass
    ctypedef enum cef_resource_type_t:
        pass
    ctypedef enum cef_transition_type_t:
        pass

# Value type structs (plain data, copied to and from Python named tuples)
cdef extern from "include/internal/cef_types_wrappers.h":
    cdef cppclass CefInsets:
        CefInsets()
        int top
        int left
        int bottom
        int right
    cdef cppclass CefMouseEvent:
        CefMouseEvent()
        int x
        int y
        uint32_t modifiers
    cdef cppclass CefPoint:
        CefPoint()
        int x
        int y
    cdef cppclass CefRange:
        CefRange()
        uint32_t from_ "from"
        uint32_t to
    cdef cppclass CefRect:
        CefRect()
        int x
        int y
        int width
        int height
    cdef cppclass CefSize:
        CefSize()
        int width
        int height

# Forward declarations
cdef extern from "include/cef_browser.h":
    cdef cppclass CefBrowser(CefBaseRefCounted)
cdef extern from "include/cef_callback.h":
    cdef cppclass CefCallback(CefBaseRefCounted)
cdef extern from "include/cef_frame.h":
    cdef cppclass CefFrame(CefBaseRefCounted)
cdef extern from "include/cef_request.h":
    cdef cppclass CefRequest(CefBaseRefCounted)
cdef extern from "include/cef_resource_handler.h":
    cdef cppclass CefResourceReadCallback(CefBaseRefCounted)
cdef extern from "include/cef_resource_handler.h":
    cdef cppclass CefResourceSkipCallback(CefBaseRefCounted)
cdef extern from "include/cef_response.h":
    cdef cppclass CefResponse(CefBaseRefCounted)
cdef extern from "include/cef_client.h":
    cdef cppclass CefClient(CefBaseRefCounted)
cdef extern from "include/cef_display_handler.h":
    cdef cppclass CefDisplayHandler(CefBaseRefCounted)
cdef extern from "include/cef_life_span_handler.h":
    cdef cppclass CefLifeSpanHandler(CefBaseRefCounted)
cdef extern from "include/cef_load_handler.h":
    cdef cppclass CefLoadHandler(CefBaseRefCounted)
cdef extern from "include/cef_resource_handler.h":
    cdef cppclass CefResourceHandler(CefBaseRefCounted)
cdef extern from "include/cef_scheme.h":
    cdef cppclass CefSchemeHandlerFactory(CefBaseRefCounted)

# Library classes (implemented by CEF)
cdef extern from "include/cef_browser.h":
    cdef cppclass CefBrowser(CefBaseRefCounted):
        cpp_bool IsValid() nogil
        cpp_bool CanGoBack() nogil
        void GoBack() nogil
        cpp_bool CanGoForward() nogil
        void GoForward() nogil
        cpp_bool IsLoading() nogil
        void Reload() nogil
        void ReloadIgnoreCache() nogil
        void StopLoad() nogil
        int GetIdentifier() nogil
        cpp_bool IsSame(CefRefPtr[CefBrowser]) nogil
        cpp_bool IsPopup() nogil
        cpp_bool HasDocument() nogil
        CefRefPtr[CefFrame] GetMainFrame() nogil
        CefRefPtr[CefFrame] GetFocusedFrame() nogil
        CefRefPtr[CefFrame] GetFrameByIdentifier(const CefString&) nogil
        CefRefPtr[CefFrame] GetFrameByName(const CefString&) nogil
        size_t GetFrameCount() nogil

cdef extern from "include/cef_callback.h":
    cdef cppclass CefCallback(CefBaseRefCounted):
        void Continue() nogil
        void Cancel() nogil

cdef extern from "include/cef_frame.h":
    cdef cppclass CefFrame(CefBaseRefCounted):
        cpp_bool IsValid() nogil
        void Undo() nogil
        void Redo() nogil
        void Cut() nogil
        void Copy() nogil
        void Paste() nogil
        void PasteAndMatchStyle() nogil
        void Delete() nogil
        void SelectAll() nogil
        void ViewSource() nogil
        void LoadRequest(CefRefPtr[CefRequest]) nogil
        void LoadURL(const CefString&) nogil
        void ExecuteJavaScript(const CefString&, const CefString&, int) nogil
        cpp_bool IsMain() nogil
        cpp_bool IsFocused() nogil
        CefString GetName() nogil
        CefString GetIdentifier() nogil
        CefRefPtr[CefFrame] GetParent() nogil
        CefString GetURL() nogil
        CefRefPtr[CefBrowser] GetBrowser() nogil

cdef extern from "include/cef_request.h":
    cdef cppclass CefRequest(CefBaseRefCounted):
        cpp_bool IsReadOnly() nogil
        CefString GetURL() nogil
        void SetURL(const CefString&) nogil
        CefString GetMethod() nogil
        void SetMethod(const CefString&) nogil
        void SetReferrer(const CefString&, cef_referrer_policy_t) nogil
        CefString GetReferrerURL() nogil
        cef_referrer_policy_t GetReferrerPolicy() nogil
        CefString GetHeaderByName(const CefString&) nogil
        void SetHeaderByName(const CefString&, const CefString&, cpp_bool) nogil
        int GetFlags() nogil
        void SetFlags(int) nogil
        CefString GetFirstPartyForCookies() nogil
        void SetFirstPartyForCookies(const CefString&) nogil
        cef_resource_type_t GetResourceType() nogil
        cef_transition_type_t GetTransitionType() nogil
        uint64_t GetIdentifier() nogil
        @staticmethod
        CefRefPtr[CefRequest] Create() nogil

cdef extern from "include/cef_resource_handler.h":
    cdef cppclass CefResourceReadCallback(CefBaseRefCounted):
        void Continue(int) nogil

cdef extern from "include/cef_resource_handler.h":
    cdef cppclass CefResourceSkipCallback(CefBaseRefCounted):
        void Continue(int64_t) nogil

cdef extern from "include/cef_response.h":
    cdef cppclass CefResponse(CefBaseRefCounted):
        cpp_bool IsReadOnly() nogil
        cef_errorcode_t GetError() nogil
        void SetError(cef_errorcode_t) nogil
        int GetStatus() nogil
        void SetStatus(int) nogil
        CefString GetStatusText() nogil
        void SetStatusText(const CefString&) nogil
        CefString GetMimeType() nogil
        void SetMimeType(const CefString&) nogil
        CefString GetCharset() nogil
        void SetCharset(const CefString&) nogil
        CefString GetHeaderByName(const CefString&) nogil
        void SetHeaderByName(const CefString&, const CefString&, cpp_bool) nogil
        CefString GetURL() nogil
        void SetURL(const CefString&) nogil
        @staticmethod
        CefRefPtr[CefResponse] Create() nogil

# Client classes (implemented by the application; Cython only needs the type)
cdef extern from "include/cef_client.h":
    cdef cppclass CefClient(CefBaseRefCounted):
        pass
cdef extern from "include/cef_display_handler.h":
    cdef cppclass CefDisplayHandler(CefBaseRefCounted):
        pass
cdef extern from "include/cef_life_span_handler.h":
    cdef cppclass CefLifeSpanHandler(CefBaseRefCounted):
        pass
cdef extern from "include/cef_load_handler.h":
    cdef cppclass CefLoadHandler(CefBaseRefCounted):
        pass
cdef extern from "include/cef_resource_handler.h":
    cdef cppclass CefResourceHandler(CefBaseRefCounted):
        pass
cdef extern from "include/cef_scheme.h":
    cdef cppclass CefSchemeHandlerFactory(CefBaseRefCounted):
        pass

# Global functions
cdef extern from "include/cef_scheme.h":
    cpp_bool CefRegisterSchemeHandlerFactory(const CefString&, const CefString&, CefRefPtr[CefSchemeHandlerFactory]) nogil
cdef extern from "include/cef_scheme.h":
    cpp_bool CefClearSchemeHandlerFactories() nogil
cdef extern from "include/cef_parser.h":
    CefString CefGetMimeType(const CefString&) nogil

# Proxies for the client classes (native/cefwrapper/generated/cefweaver_proxies.h)
cdef extern from "generated/cefweaver_proxies.h":
    cdef cppclass CwClientCallbacks:
        void* py
        void (*release)(void*) noexcept
        CefDisplayHandler* (*fn_get_display_handler)(void*) noexcept
        CefLifeSpanHandler* (*fn_get_life_span_handler)(void*) noexcept
        CefLoadHandler* (*fn_get_load_handler)(void*) noexcept
    cdef cppclass CwClientProxy(CefClient):
        CwClientProxy(const CwClientCallbacks&)
    cdef cppclass CwDisplayHandlerCallbacks:
        void* py
        void (*release)(void*) noexcept
        void (*fn_on_address_change)(void*, CefBrowser*, CefFrame*, const CefString*) noexcept
        void (*fn_on_title_change)(void*, CefBrowser*, const CefString*) noexcept
        void (*fn_on_fullscreen_mode_change)(void*, CefBrowser*, cpp_bool) noexcept
        cpp_bool (*fn_on_tooltip)(void*, CefBrowser*, CefString*) noexcept
        void (*fn_on_status_message)(void*, CefBrowser*, const CefString*) noexcept
        cpp_bool (*fn_on_console_message)(void*, CefBrowser*, int, const CefString*, const CefString*, int) noexcept
        cpp_bool (*fn_on_auto_resize)(void*, CefBrowser*, const CefSize*) noexcept
        void (*fn_on_loading_progress_change)(void*, CefBrowser*, double) noexcept
        void (*fn_on_media_access_change)(void*, CefBrowser*, cpp_bool, cpp_bool) noexcept
        cpp_bool (*fn_on_contents_bounds_change)(void*, CefBrowser*, const CefRect*) noexcept
        cpp_bool (*fn_get_root_window_screen_rect)(void*, CefBrowser*, CefRect*) noexcept
    cdef cppclass CwDisplayHandlerProxy(CefDisplayHandler):
        CwDisplayHandlerProxy(const CwDisplayHandlerCallbacks&)
    cdef cppclass CwLifeSpanHandlerCallbacks:
        void* py
        void (*release)(void*) noexcept
        void (*fn_on_before_popup_aborted)(void*, CefBrowser*, int) noexcept
        void (*fn_on_after_created)(void*, CefBrowser*) noexcept
        cpp_bool (*fn_do_close)(void*, CefBrowser*) noexcept
        void (*fn_on_before_close)(void*, CefBrowser*) noexcept
    cdef cppclass CwLifeSpanHandlerProxy(CefLifeSpanHandler):
        CwLifeSpanHandlerProxy(const CwLifeSpanHandlerCallbacks&)
    cdef cppclass CwLoadHandlerCallbacks:
        void* py
        void (*release)(void*) noexcept
        void (*fn_on_loading_state_change)(void*, CefBrowser*, cpp_bool, cpp_bool, cpp_bool) noexcept
        void (*fn_on_load_start)(void*, CefBrowser*, CefFrame*, int) noexcept
        void (*fn_on_load_end)(void*, CefBrowser*, CefFrame*, int) noexcept
        void (*fn_on_load_error)(void*, CefBrowser*, CefFrame*, int, const CefString*, const CefString*) noexcept
    cdef cppclass CwLoadHandlerProxy(CefLoadHandler):
        CwLoadHandlerProxy(const CwLoadHandlerCallbacks&)
    cdef cppclass CwResourceHandlerCallbacks:
        void* py
        void (*release)(void*) noexcept
        cpp_bool (*fn_open)(void*, CefRequest*, cpp_bool*, CefCallback*) noexcept
        cpp_bool (*fn_process_request)(void*, CefRequest*, CefCallback*) noexcept
        void (*fn_get_response_headers)(void*, CefResponse*, int64_t*, CefString*) noexcept
        cpp_bool (*fn_skip)(void*, int64_t, int64_t*, CefResourceSkipCallback*) noexcept
        cpp_bool (*fn_read)(void*, void*, int, int*, CefResourceReadCallback*) noexcept
        cpp_bool (*fn_read_response)(void*, void*, int, int*, CefCallback*) noexcept
        void (*fn_cancel)(void*) noexcept
    cdef cppclass CwResourceHandlerProxy(CefResourceHandler):
        CwResourceHandlerProxy(const CwResourceHandlerCallbacks&)
    cdef cppclass CwSchemeHandlerFactoryCallbacks:
        void* py
        void (*release)(void*) noexcept
        CefResourceHandler* (*fn_create)(void*, CefBrowser*, CefFrame*, const CefString*, CefRequest*) noexcept
    cdef cppclass CwSchemeHandlerFactoryProxy(CefSchemeHandlerFactory):
        CwSchemeHandlerFactoryProxy(const CwSchemeHandlerFactoryCallbacks&)
