# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

"""The CEF enumerations and value types (see tools/gen/emit_types.py).

Enumerations are `enum.IntEnum` (or `enum.IntFlag` for bit flags), so a member can be used
wherever CEF wants an integer, and a value CEF reports that has no member is passed on as a
plain int. Value types are `typing.NamedTuple`: they unpack, and a tuple with the same fields
works wherever one is expected.
"""

import enum
from typing import NamedTuple


class AlphaType(enum.IntEnum):
    """Describes how to interpret the alpha component of a pixel."""
    OPAQUE = 0
    PREMULTIPLIED = 1
    POSTMULTIPLIED = 2


class AxisAlignment(enum.IntEnum):
    """Specifies where along the axis the CefBoxLayout child views should be laid out. Should be kept in sync with Chromium's views::LayoutAlignment type."""
    START = 0
    CENTER = 1
    END = 2
    STRETCH = 3
    NUM_VALUES = 4


class ButtonState(enum.IntEnum):
    """Specifies the button display state."""
    NORMAL = 0
    HOVERED = 1
    PRESSED = 2
    DISABLED = 3
    NUM_VALUES = 4


class CertStatus(enum.IntFlag):
    """Supported certificate status code values. See net\\cert\\cert_status_flags.h for more information. CERT_STATUS_NONE is new in CEF because we use an enum while cert_status_flags.h uses a typedef and static const variables."""
    NONE = 0
    COMMON_NAME_INVALID = 1
    DATE_INVALID = 2
    AUTHORITY_INVALID = 4
    NO_REVOCATION_MECHANISM = 16
    UNABLE_TO_CHECK_REVOCATION = 32
    REVOKED = 64
    INVALID = 128
    WEAK_SIGNATURE_ALGORITHM = 256
    NON_UNIQUE_NAME = 1024
    WEAK_KEY = 2048
    PINNED_KEY_MISSING = 8192
    NAME_CONSTRAINT_VIOLATION = 16384
    VALIDITY_TOO_LONG = 32768
    IS_EV = 65536
    REV_CHECKING_ENABLED = 131072
    SHA1_SIGNATURE_PRESENT = 524288
    CT_COMPLIANCE_FAILED = 1048576


class ChannelLayout(enum.IntEnum):
    """Enumerates the various representations of the ordering of audio channels. Must be kept synchronized with media::ChannelLayout from Chromium. See media\\base\\channel_layout.h"""
    LAYOUT_NONE = 0
    LAYOUT_UNSUPPORTED = 1
    LAYOUT_MONO = 2
    LAYOUT_STEREO = 3
    LAYOUT_2_1 = 4
    LAYOUT_SURROUND = 5
    LAYOUT_4_0 = 6
    LAYOUT_2_2 = 7
    LAYOUT_QUAD = 8
    LAYOUT_5_0 = 9
    LAYOUT_5_1 = 10
    LAYOUT_5_0_BACK = 11
    LAYOUT_5_1_BACK = 12
    LAYOUT_7_0 = 13
    LAYOUT_7_1 = 14
    LAYOUT_7_1_WIDE = 15
    LAYOUT_STEREO_DOWNMIX = 16
    LAYOUT_2POINT1 = 17
    LAYOUT_3_1 = 18
    LAYOUT_4_1 = 19
    LAYOUT_6_0 = 20
    LAYOUT_6_0_FRONT = 21
    LAYOUT_HEXAGONAL = 22
    LAYOUT_6_1 = 23
    LAYOUT_6_1_BACK = 24
    LAYOUT_6_1_FRONT = 25
    LAYOUT_7_0_FRONT = 26
    LAYOUT_7_1_WIDE_BACK = 27
    LAYOUT_OCTAGONAL = 28
    LAYOUT_DISCRETE = 29
    LAYOUT_STEREO_AND_KEYBOARD_MIC = 30
    LAYOUT_4_1_QUAD_SIDE = 31
    LAYOUT_BITSTREAM = 32
    LAYOUT_5_1_4_DOWNMIX = 33
    LAYOUT_1_1 = 34
    LAYOUT_3_1_BACK = 35
    LAYOUT_5_1_4 = 36
    LAYOUT_7_1_4 = 37
    NUM_VALUES = 38


class ChromePageActionIconType(enum.IntEnum):
    """Chrome page action icon types. Should be kept in sync with Chromium's PageActionIconType type."""
    BOOKMARK_STAR = 0
    CLICK_TO_CALL = 1
    COOKIE_CONTROLS = 2
    FILE_SYSTEM_ACCESS = 3
    FIND = 4
    MEMORY_SAVER = 5
    INTENT_PICKER = 6
    LOCAL_CARD_MIGRATION = 7
    MANAGE_PASSWORDS = 8
    PAYMENTS_OFFER_NOTIFICATION = 9
    PRICE_TRACKING = 10
    PWA_INSTALL = 11
    QR_CODE_GENERATOR_DEPRECATED = 12
    READER_MODE_DEPRECATED = 13
    SAVE_AUTOFILL_ADDRESS = 14
    SAVE_CARD = 15
    SEND_TAB_TO_SELF_DEPRECATED = 16
    SHARING_HUB = 17
    SIDE_SEARCH_DEPRECATED = 18
    SMS_REMOTE_FETCHER = 19
    TRANSLATE = 20
    VIRTUAL_CARD_ENROLL = 21
    VIRTUAL_CARD_INFORMATION = 22
    ZOOM = 23
    SAVE_IBAN = 24
    MANDATORY_REAUTH = 25
    PRICE_INSIGHTS = 26
    READ_ANYTHING_DEPRECATED = 27
    PRODUCT_SPECIFICATIONS = 28
    LENS_OVERLAY = 29
    DISCOUNTS = 30
    OPTIMIZATION_GUIDE = 31
    COLLABORATION_MESSAGING = 32
    CHANGE_PASSWORD = 33
    LENS_OVERLAY_HOMEWORK = 34
    AI_MODE = 35
    READING_MODE = 36
    CONTEXTUAL_SIDE_PANEL = 37
    JS_OPTIMIZATIONS = 38
    RECORD_REPLAY = 39
    INDIGO = 40
    FEDERATION = 41
    GLIC = 42
    ANCHORED_CONTEXTUAL_CUE = 43
    WEB_AUTHN_AMBIENT_SIGNIN = 44
    AUTOFILL_PAYMENT = 45
    MULTISTEP_FILTER = 46
    PAYMENTS_CHURNED_USERS = 47
    FAKE_PAGE_ACTION_FOR_DEBUG = 48
    WALLET_REMINDER_NOTICE = 49
    NUM_VALUES = 50


class ChromeToolbarButtonType(enum.IntEnum):
    """Chrome toolbar button types. Should be kept in sync with CEF's internal ToolbarButtonType type."""
    CAST_DEPRECATED = 0
    DOWNLOAD_DEPRECATED = 1
    SEND_TAB_TO_SELF_DEPRECATED = 2
    SIDE_PANEL_DEPRECATED = 3
    MEDIA = 4
    TAB_SEARCH_DEPRECATED = 5
    BATTERY_SAVER = 6
    AVATAR = 7
    NUM_VALUES = 8


class ChromeToolbarType(enum.IntEnum):
    """Chrome toolbar types."""
    UNKNOWN = 0
    NONE = 1
    NORMAL = 2
    LOCATION = 3
    NUM_VALUES = 4


class ColorModel(enum.IntEnum):
    """Print job color mode values."""
    UNKNOWN = 0
    GRAY = 1
    COLOR = 2
    CMYK = 3
    CMY = 4
    KCMY = 5
    CMY_K = 6
    BLACK = 7
    GRAYSCALE = 8
    RGB = 9
    RGB16 = 10
    RGBA = 11
    COLORMODE_COLOR = 12
    COLORMODE_MONOCHROME = 13
    HP_COLOR_COLOR = 14
    HP_COLOR_BLACK = 15
    PRINTOUTMODE_NORMAL = 16
    PRINTOUTMODE_NORMAL_GRAY = 17
    PROCESSCOLORMODEL_CMYK = 18
    PROCESSCOLORMODEL_GREYSCALE = 19
    PROCESSCOLORMODEL_RGB = 20
    NUM_VALUES = 21


class ColorType(enum.IntEnum):
    """Describes how to interpret the components of a pixel."""
    RGBA_8888 = 0
    BGRA_8888 = 1
    NUM_VALUES = 2


class ColorVariant(enum.IntEnum):
    """Specifies the color variants supported by CefRequestContext::SetChromeThemeColor."""
    SYSTEM = 0
    LIGHT = 1
    DARK = 2
    TONAL_SPOT = 3
    NEUTRAL = 4
    VIBRANT = 5
    EXPRESSIVE = 6
    NUM_VALUES = 7


class ComInitMode(enum.IntEnum):
    """Windows COM initialization mode. Specifies how COM will be initialized for a new thread."""
    NONE = 0
    STA = 1
    MTA = 2


class ComponentState(enum.IntEnum):
    """Component state values. These map to update_client::ComponentState values from components/update_client/update_client.h A component is considered "installed" when its state is one of: CEF_COMPONENT_STATE_UPDATED, CEF_COMPONENT_STATE_UP_TO_DATE, or CEF_COMPONENT_STATE_RUN."""
    NEW = 0
    CHECKING = 1
    CAN_UPDATE = 2
    DOWNLOADING = 3
    DECOMPRESSING = 4
    PATCHING = 5
    UPDATING = 6
    UPDATED = 7
    UP_TO_DATE = 8
    UPDATE_ERROR = 9
    RUN = 10


class ComponentUpdateError(enum.IntEnum):
    """Component update error codes. These map to update_client::Error values from components/update_client/update_client_errors.h"""
    NONE = 0
    UPDATE_IN_PROGRESS = 1
    UPDATE_CANCELED = 2
    RETRY_LATER = 3
    SERVICE_ERROR = 4
    UPDATE_CHECK_ERROR = 5
    CRX_NOT_FOUND = 6
    INVALID_ARGUMENT = 7
    BAD_CRX_DATA_CALLBACK = 8


class ComponentUpdatePriority(enum.IntEnum):
    """Component update priority. Maps to component_updater::OnDemandUpdater::Priority."""
    BACKGROUND = 0
    FOREGROUND = 1


class CompositionUnderlineStyle(enum.IntEnum):
    """Composition underline style."""
    SOLID = 0
    DOT = 1
    DASH = 2
    NONE = 3
    NUM_VALUES = 4


class ContentSettingTypes(enum.IntEnum):
    """Supported content setting types. Some types are platform-specific or only supported with Chrome style. Should be kept in sync with Chromium's ContentSettingsType type."""
    COOKIES = 0
    IMAGES = 1
    JAVASCRIPT = 2
    POPUPS = 3
    GEOLOCATION = 4
    NOTIFICATIONS = 5
    AUTO_SELECT_CERTIFICATE = 6
    MIXEDSCRIPT = 7
    MEDIASTREAM_MIC = 8
    MEDIASTREAM_CAMERA = 9
    PROTOCOL_HANDLERS = 10
    DEPRECATED_PPAPI_BROKER = 11
    AUTOMATIC_DOWNLOADS = 12
    MIDI_SYSEX = 13
    SSL_CERT_DECISIONS = 14
    PROTECTED_MEDIA_IDENTIFIER = 15
    APP_BANNER = 16
    SITE_ENGAGEMENT = 17
    PERSISTENT_STORAGE = 18
    USB_CHOOSER_DATA = 19
    BLUETOOTH_GUARD = 20
    BACKGROUND_SYNC = 21
    AUTOPLAY = 22
    IMPORTANT_SITE_INFO = 23
    PERMISSION_AUTOBLOCKER_DATA = 24
    ADS = 25
    ADS_DATA = 26
    MIDI = 27
    PASSWORD_PROTECTION = 28
    MEDIA_ENGAGEMENT = 29
    SOUND = 30
    CLIENT_HINTS = 31
    SENSORS = 32
    DEPRECATED_ACCESSIBILITY_EVENTS = 33
    PAYMENT_HANDLER = 34
    USB_GUARD = 35
    BACKGROUND_FETCH = 36
    INTENT_PICKER_DISPLAY = 37
    IDLE_DETECTION = 38
    SERIAL_GUARD = 39
    SERIAL_CHOOSER_DATA = 40
    PERIODIC_BACKGROUND_SYNC = 41
    BLUETOOTH_SCANNING = 42
    HID_GUARD = 43
    HID_CHOOSER_DATA = 44
    WAKE_LOCK_SCREEN = 45
    WAKE_LOCK_SYSTEM = 46
    LEGACY_COOKIE_ACCESS = 47
    FILE_SYSTEM_WRITE_GUARD = 48
    NFC = 49
    BLUETOOTH_CHOOSER_DATA = 50
    CLIPBOARD_READ_WRITE = 51
    CLIPBOARD_SANITIZED_WRITE = 52
    SAFE_BROWSING_URL_CHECK_DATA = 53
    VR = 54
    AR = 55
    FILE_SYSTEM_READ_GUARD = 56
    STORAGE_ACCESS = 57
    CAMERA_PAN_TILT_ZOOM = 58
    WINDOW_MANAGEMENT = 59
    INSECURE_PRIVATE_NETWORK_DEPRECATED = 60
    LOCAL_FONTS = 61
    PERMISSION_AUTOREVOCATION_DATA = 62
    FILE_SYSTEM_LAST_PICKED_DIRECTORY = 63
    DISPLAY_CAPTURE = 64
    FILE_SYSTEM_ACCESS_CHOOSER_DATA = 65
    FEDERATED_IDENTITY_SHARING = 66
    JAVASCRIPT_JIT = 67
    HTTP_ALLOWED = 68
    FORMFILL_METADATA = 69
    DEPRECATED_FEDERATED_IDENTITY_ACTIVE_SESSION = 70
    AUTO_DARK_WEB_CONTENT = 71
    REQUEST_DESKTOP_SITE = 72
    FEDERATED_IDENTITY_API = 73
    NOTIFICATION_INTERACTIONS = 74
    REDUCED_ACCEPT_LANGUAGE = 75
    NOTIFICATION_PERMISSION_REVIEW = 76
    PRIVATE_NETWORK_GUARD_DEPRECATED = 77
    PRIVATE_NETWORK_CHOOSER_DATA_DEPRECATED = 78
    FEDERATED_IDENTITY_IDENTITY_PROVIDER_SIGNIN_STATUS = 79
    REVOKED_UNUSED_SITE_PERMISSIONS = 80
    TOP_LEVEL_STORAGE_ACCESS = 81
    FEDERATED_IDENTITY_AUTO_REAUTHN_PERMISSION = 82
    FEDERATED_IDENTITY_IDENTITY_PROVIDER_REGISTRATION = 83
    ANTI_ABUSE = 84
    THIRD_PARTY_STORAGE_PARTITIONING_DEPRECATED = 85
    HTTPS_ENFORCED = 86
    ALL_SCREEN_CAPTURE = 87
    COOKIE_CONTROLS_METADATA = 88
    TPCD_HEURISTICS_GRANTS_DEPRECATED = 89
    TPCD_METADATA_GRANTS_DEPRECATED = 90
    TPCD_TRIAL_DEPRECATED = 91
    TOP_LEVEL_TPCD_TRIAL_DEPRECATED = 92
    TOP_LEVEL_TPCD_ORIGIN_TRIAL_DEPRECATED = 93
    AUTO_PICTURE_IN_PICTURE = 94
    FILE_SYSTEM_ACCESS_EXTENDED_PERMISSION = 95
    FILE_SYSTEM_ACCESS_RESTORE_PERMISSION = 96
    CAPTURED_SURFACE_CONTROL = 97
    SMART_CARD_GUARD = 98
    SMART_CARD_DATA = 99
    WEB_PRINTING = 100
    AUTOMATIC_FULLSCREEN = 101
    SUB_APP_INSTALLATION_PROMPTS = 102
    SPEAKER_SELECTION = 103
    DIRECT_SOCKETS = 104
    KEYBOARD_LOCK = 105
    POINTER_LOCK = 106
    REVOKED_ABUSIVE_NOTIFICATION_PERMISSIONS = 107
    TRACKING_PROTECTION_DEPRECATED = 108
    DISPLAY_MEDIA_SYSTEM_AUDIO = 109
    JAVASCRIPT_OPTIMIZER = 110
    STORAGE_ACCESS_HEADER_ORIGIN_TRIAL = 111
    HAND_TRACKING = 112
    WEB_APP_INSTALLATION = 113
    DIRECT_SOCKETS_PRIVATE_NETWORK_ACCESS = 114
    LEGACY_COOKIE_SCOPE = 115
    ARE_SUSPICIOUS_NOTIFICATIONS_ALLOWLISTED_BY_USER = 116
    CONTROLLED_FRAME = 117
    REVOKED_DISRUPTIVE_NOTIFICATION_PERMISSIONS = 118
    LOCAL_NETWORK_ACCESS = 119
    ON_DEVICE_SPEECH_RECOGNITION_LANGUAGES_DOWNLOADED = 120
    INITIALIZED_TRANSLATIONS = 121
    SUSPICIOUS_NOTIFICATION_IDS = 122
    GEOLOCATION_WITH_OPTIONS = 123
    DEVICE_ATTRIBUTES = 124
    PERMISSION_ACTIONS_HISTORY = 125
    SUSPICIOUS_NOTIFICATION_SHOW_ORIGINAL = 126
    LOCAL_NETWORK = 127
    LOOPBACK_NETWORK = 128
    SUB_APPS_WITHOUT_PROMPTS = 129
    INLINE_CUE_MENU = 130
    SUSPICIOUS_SITE_WARNING_DATA = 131
    NUM_VALUES = 132


class ContentSettingValues(enum.IntEnum):
    """Supported content setting values. Should be kept in sync with Chromium's ContentSetting type."""
    DEFAULT = 0
    ALLOW = 1
    BLOCK = 2
    ASK = 3
    SESSION_ONLY = 4
    DETECT_IMPORTANT_CONTENT_DEPRECATED = 5
    NUM_VALUES = 6


class ContextMenuEditStateFlags(enum.IntFlag):
    """Supported context menu edit state bit flags. These constants match their equivalents in Chromium's ContextMenuDataEditFlags and should not be renumbered."""
    NONE = 0
    CAN_UNDO = 1
    CAN_REDO = 2
    CAN_CUT = 4
    CAN_COPY = 8
    CAN_PASTE = 16
    CAN_DELETE = 32
    CAN_SELECT_ALL = 64
    CAN_TRANSLATE = 128
    CAN_EDIT_RICHLY = 256


class ContextMenuMediaStateFlags(enum.IntFlag):
    """Supported context menu media state bit flags. These constants match their equivalents in Chromium's ContextMenuData::MediaFlags and should not be renumbered."""
    NONE = 0
    IN_ERROR = 1
    PAUSED = 2
    MUTED = 4
    LOOP = 8
    CAN_SAVE = 16
    HAS_AUDIO = 32
    CAN_TOGGLE_CONTROLS = 64
    CONTROLS = 128
    CAN_PRINT = 256
    CAN_ROTATE = 512
    CAN_PICTURE_IN_PICTURE = 1024
    PICTURE_IN_PICTURE = 2048
    CAN_LOOP = 4096


class ContextMenuMediaType(enum.IntEnum):
    """Supported context menu media types. These constants match their equivalents in Chromium's ContextMenuDataMediaType and should not be renumbered."""
    NONE = 0
    IMAGE = 1
    VIDEO = 2
    AUDIO = 3
    CANVAS = 4
    FILE = 5
    PLUGIN = 6
    NUM_VALUES = 7


class ContextMenuTypeFlags(enum.IntFlag):
    """Supported context menu type flags."""
    NONE = 0
    PAGE = 1
    FRAME = 2
    LINK = 4
    MEDIA = 8
    SELECTION = 16
    EDITABLE = 32


class CookiePriority(enum.IntEnum):
    """Cookie priority values."""
    LOW = (-1)
    MEDIUM = 0
    HIGH = 1


class CookieSameSite(enum.IntEnum):
    """Cookie same site values."""
    UNSPECIFIED = 0
    NO_RESTRICTION = 1
    LAX_MODE = 2
    STRICT_MODE = 3
    NUM_VALUES = 4


class CursorType(enum.IntEnum):
    """Cursor type values."""
    POINTER = 0
    CROSS = 1
    HAND = 2
    IBEAM = 3
    WAIT = 4
    HELP = 5
    EASTRESIZE = 6
    NORTHRESIZE = 7
    NORTHEASTRESIZE = 8
    NORTHWESTRESIZE = 9
    SOUTHRESIZE = 10
    SOUTHEASTRESIZE = 11
    SOUTHWESTRESIZE = 12
    WESTRESIZE = 13
    NORTHSOUTHRESIZE = 14
    EASTWESTRESIZE = 15
    NORTHEASTSOUTHWESTRESIZE = 16
    NORTHWESTSOUTHEASTRESIZE = 17
    COLUMNRESIZE = 18
    ROWRESIZE = 19
    MIDDLEPANNING = 20
    EASTPANNING = 21
    NORTHPANNING = 22
    NORTHEASTPANNING = 23
    NORTHWESTPANNING = 24
    SOUTHPANNING = 25
    SOUTHEASTPANNING = 26
    SOUTHWESTPANNING = 27
    WESTPANNING = 28
    MOVE = 29
    VERTICALTEXT = 30
    CELL = 31
    CONTEXTMENU = 32
    ALIAS = 33
    PROGRESS = 34
    NODROP = 35
    COPY = 36
    NONE = 37
    NOTALLOWED = 38
    ZOOMIN = 39
    ZOOMOUT = 40
    GRAB = 41
    GRABBING = 42
    MIDDLE_PANNING_VERTICAL = 43
    MIDDLE_PANNING_HORIZONTAL = 44
    CUSTOM = 45
    DND_NONE = 46
    DND_MOVE = 47
    DND_COPY = 48
    DND_LINK = 49
    NUM_VALUES = 50


class DockingMode(enum.IntEnum):
    """Docking modes supported by CefWindow::AddOverlay."""
    TOP_LEFT = 0
    TOP_RIGHT = 1
    BOTTOM_LEFT = 2
    BOTTOM_RIGHT = 3
    CUSTOM = 4
    NUM_VALUES = 5


class DomDocumentType(enum.IntEnum):
    """DOM document types."""
    UNKNOWN = 0
    HTML = 1
    XHTML = 2
    PLUGIN = 3
    NUM_VALUES = 4


class DomEventCategory(enum.IntFlag):
    """DOM event category flags."""
    UNKNOWN = 0
    UI = 1
    MOUSE = 2
    MUTATION = 4
    KEYBOARD = 8
    TEXT = 16
    COMPOSITION = 32
    DRAG = 64
    CLIPBOARD = 128
    MESSAGE = 256
    WHEEL = 512
    BEFORE_TEXT_INSERTED = 1024
    OVERFLOW = 2048
    PAGE_TRANSITION = 4096
    POPSTATE = 8192
    PROGRESS = 16384
    XMLHTTPREQUEST_PROGRESS = 32768


class DomEventPhase(enum.IntEnum):
    """DOM event processing phases."""
    UNKNOWN = 0
    CAPTURING = 1
    AT_TARGET = 2
    BUBBLING = 3
    NUM_VALUES = 4


class DomFormControlType(enum.IntEnum):
    """DOM form control types. Should be kept in sync with Chromium's blink::mojom::FormControlType type."""
    UNSUPPORTED = 0
    BUTTON_BUTTON = 1
    BUTTON_SUBMIT = 2
    BUTTON_RESET = 3
    BUTTON_POPOVER = 4
    FIELDSET = 5
    INPUT_BUTTON = 6
    INPUT_CHECKBOX = 7
    INPUT_COLOR = 8
    INPUT_DATE = 9
    INPUT_DATETIME_LOCAL = 10
    INPUT_EMAIL = 11
    INPUT_FILE = 12
    INPUT_HIDDEN = 13
    INPUT_IMAGE = 14
    INPUT_MONTH = 15
    INPUT_NUMBER = 16
    INPUT_PASSWORD = 17
    INPUT_RADIO = 18
    INPUT_RANGE = 19
    INPUT_RESET = 20
    INPUT_SEARCH = 21
    INPUT_SUBMIT = 22
    INPUT_TELEPHONE = 23
    INPUT_TEXT = 24
    INPUT_TIME = 25
    INPUT_URL = 26
    INPUT_WEEK = 27
    OUTPUT = 28
    SELECT_ONE = 29
    SELECT_MULTIPLE = 30
    TEXT_AREA = 31
    NUM_VALUES = 32


class DomNodeType(enum.IntEnum):
    """DOM node types."""
    UNSUPPORTED = 0
    ELEMENT = 1
    ATTRIBUTE = 2
    TEXT = 3
    CDATA_SECTION = 4
    PROCESSING_INSTRUCTIONS = 5
    COMMENT = 6
    DOCUMENT = 7
    DOCUMENT_TYPE = 8
    DOCUMENT_FRAGMENT = 9
    NUM_VALUES = 10


class DownloadInterruptReason(enum.IntEnum):
    """Download interrupt reasons. Should be kept in sync with Chromium's download::DownloadInterruptReason type."""
    NONE = 0
    FILE_FAILED = 1
    FILE_ACCESS_DENIED = 2
    FILE_NO_SPACE = 3
    FILE_NAME_TOO_LONG = 5
    FILE_TOO_LARGE = 6
    FILE_VIRUS_INFECTED = 7
    FILE_TRANSIENT_ERROR = 10
    FILE_BLOCKED = 11
    FILE_SECURITY_CHECK_FAILED = 12
    FILE_TOO_SHORT = 13
    FILE_HASH_MISMATCH = 14
    FILE_SAME_AS_SOURCE = 15
    NETWORK_FAILED = 20
    NETWORK_TIMEOUT = 21
    NETWORK_DISCONNECTED = 22
    NETWORK_SERVER_DOWN = 23
    NETWORK_INVALID_REQUEST = 24
    SERVER_FAILED = 30
    SERVER_NO_RANGE = 31
    SERVER_BAD_CONTENT = 33
    SERVER_UNAUTHORIZED = 34
    SERVER_CERT_PROBLEM = 35
    SERVER_FORBIDDEN = 36
    SERVER_UNREACHABLE = 37
    SERVER_CONTENT_LENGTH_MISMATCH = 38
    SERVER_CROSS_ORIGIN_REDIRECT = 39
    USER_CANCELED = 40
    USER_SHUTDOWN = 41
    CRASH = 50


class DragOperationsMask(enum.IntFlag):
    """"Verb" of a drag-and-drop operation as negotiated between the source and destination. These constants match their equivalents in WebCore's DragActions.h and should not be renumbered."""
    NONE = 0
    COPY = 1
    LINK = 2
    GENERIC = 4
    PRIVATE = 8
    MOVE = 16
    DELETE = 32
    EVERY = 4294967295


class DuplexMode(enum.IntEnum):
    """Print job duplex mode values."""
    UNKNOWN = (-1)
    SIMPLEX = 0
    LONG_EDGE = 1
    SHORT_EDGE = 2
    NUM_VALUES = 3


class ErrorCode(enum.IntEnum):
    """Supported error code values. For the complete list of error values see "include/base/internal/cef_net_error_list.h"."""
    NONE = 0
    IO_PENDING = (-1)
    FAILED = (-2)
    ABORTED = (-3)
    INVALID_ARGUMENT = (-4)
    INVALID_HANDLE = (-5)
    FILE_NOT_FOUND = (-6)
    TIMED_OUT = (-7)
    FILE_TOO_BIG = (-8)
    UNEXPECTED = (-9)
    ACCESS_DENIED = (-10)
    NOT_IMPLEMENTED = (-11)
    INSUFFICIENT_RESOURCES = (-12)
    OUT_OF_MEMORY = (-13)
    UPLOAD_FILE_CHANGED = (-14)
    SOCKET_NOT_CONNECTED = (-15)
    FILE_EXISTS = (-16)
    FILE_PATH_TOO_LONG = (-17)
    FILE_NO_SPACE = (-18)
    FILE_VIRUS_INFECTED = (-19)
    BLOCKED_BY_CLIENT = (-20)
    NETWORK_CHANGED = (-21)
    BLOCKED_BY_ADMINISTRATOR = (-22)
    SOCKET_IS_CONNECTED = (-23)
    UPLOAD_STREAM_REWIND_NOT_SUPPORTED = (-25)
    CONTEXT_SHUT_DOWN = (-26)
    BLOCKED_BY_RESPONSE = (-27)
    CLEARTEXT_NOT_PERMITTED = (-29)
    BLOCKED_BY_CSP = (-30)
    BLOCKED_BY_ORB = (-32)
    NETWORK_ACCESS_REVOKED = (-33)
    BLOCKED_BY_FINGERPRINTING_PROTECTION = (-34)
    BLOCKED_IN_INCOGNITO_BY_ADMINISTRATOR = (-35)
    LOCAL_NETWORK_PERMISSION_MISSING = (-36)
    STRICT_ECH_REQUIRED = (-37)
    CONNECTION_CLOSED = (-100)
    CONNECTION_RESET = (-101)
    CONNECTION_REFUSED = (-102)
    CONNECTION_ABORTED = (-103)
    CONNECTION_FAILED = (-104)
    NAME_NOT_RESOLVED = (-105)
    INTERNET_DISCONNECTED = (-106)
    SSL_PROTOCOL_ERROR = (-107)
    ADDRESS_INVALID = (-108)
    ADDRESS_UNREACHABLE = (-109)
    SSL_CLIENT_AUTH_CERT_NEEDED = (-110)
    TUNNEL_CONNECTION_FAILED = (-111)
    SSL_VERSION_OR_CIPHER_MISMATCH = (-113)
    SSL_RENEGOTIATION_REQUESTED = (-114)
    PROXY_AUTH_UNSUPPORTED = (-115)
    BAD_SSL_CLIENT_AUTH_CERT = (-117)
    CONNECTION_TIMED_OUT = (-118)
    HOST_RESOLVER_QUEUE_TOO_LARGE = (-119)
    SOCKS_CONNECTION_FAILED = (-120)
    SOCKS_CONNECTION_HOST_UNREACHABLE = (-121)
    ALPN_NEGOTIATION_FAILED = (-122)
    SSL_NO_RENEGOTIATION = (-123)
    WINSOCK_UNEXPECTED_WRITTEN_BYTES = (-124)
    SSL_DECOMPRESSION_FAILURE_ALERT = (-125)
    SSL_BAD_RECORD_MAC_ALERT = (-126)
    PROXY_AUTH_REQUESTED = (-127)
    PROXY_CONNECTION_FAILED = (-130)
    MANDATORY_PROXY_CONFIGURATION_FAILED = (-131)
    PRECONNECT_MAX_SOCKET_LIMIT = (-133)
    SSL_CLIENT_AUTH_PRIVATE_KEY_ACCESS_DENIED = (-134)
    SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY = (-135)
    PROXY_CERTIFICATE_INVALID = (-136)
    NAME_RESOLUTION_FAILED = (-137)
    NETWORK_ACCESS_DENIED = (-138)
    TEMPORARILY_THROTTLED = (-139)
    SSL_CLIENT_AUTH_SIGNATURE_FAILED = (-141)
    MSG_TOO_BIG = (-142)
    WS_PROTOCOL_ERROR = (-145)
    ADDRESS_IN_USE = (-147)
    SSL_PINNED_KEY_NOT_IN_CERT_CHAIN = (-150)
    CLIENT_AUTH_CERT_TYPE_UNSUPPORTED = (-151)
    SSL_DECRYPT_ERROR_ALERT = (-153)
    WS_THROTTLE_QUEUE_TOO_LARGE = (-154)
    SSL_SERVER_CERT_CHANGED = (-156)
    SSL_UNRECOGNIZED_NAME_ALERT = (-159)
    SOCKET_SET_RECEIVE_BUFFER_SIZE_ERROR = (-160)
    SOCKET_SET_SEND_BUFFER_SIZE_ERROR = (-161)
    SOCKET_RECEIVE_BUFFER_SIZE_UNCHANGEABLE = (-162)
    SOCKET_SEND_BUFFER_SIZE_UNCHANGEABLE = (-163)
    SSL_CLIENT_AUTH_CERT_BAD_FORMAT = (-164)
    ICANN_NAME_COLLISION = (-166)
    SSL_SERVER_CERT_BAD_FORMAT = (-167)
    CT_STH_PARSING_FAILED = (-168)
    CT_STH_INCOMPLETE = (-169)
    UNABLE_TO_REUSE_CONNECTION_FOR_PROXY_AUTH = (-170)
    CT_CONSISTENCY_PROOF_PARSING_FAILED = (-171)
    SSL_OBSOLETE_CIPHER = (-172)
    WS_UPGRADE = (-173)
    READ_IF_READY_NOT_IMPLEMENTED = (-174)
    NO_BUFFER_SPACE = (-176)
    SSL_CLIENT_AUTH_NO_COMMON_ALGORITHMS = (-177)
    EARLY_DATA_REJECTED = (-178)
    WRONG_VERSION_ON_EARLY_DATA = (-179)
    TLS13_DOWNGRADE_DETECTED = (-180)
    SSL_KEY_USAGE_INCOMPATIBLE = (-181)
    INVALID_ECH_CONFIG_LIST = (-182)
    ECH_NOT_NEGOTIATED = (-183)
    ECH_FALLBACK_CERTIFICATE_INVALID = (-184)
    PROXY_UNABLE_TO_CONNECT_TO_DESTINATION = (-186)
    PROXY_DELEGATE_CANCELED_CONNECT_REQUEST = (-187)
    PROXY_DELEGATE_CANCELED_CONNECT_RESPONSE = (-188)
    CONTROL_MSG_TOO_BIG = (-189)
    MULTICAST_NOT_ALLOWED = (-190)
    CERT_COMMON_NAME_INVALID = (-200)
    CERT_DATE_INVALID = (-201)
    CERT_AUTHORITY_INVALID = (-202)
    CERT_CONTAINS_ERRORS = (-203)
    CERT_NO_REVOCATION_MECHANISM = (-204)
    CERT_UNABLE_TO_CHECK_REVOCATION = (-205)
    CERT_REVOKED = (-206)
    CERT_INVALID = (-207)
    CERT_WEAK_SIGNATURE_ALGORITHM = (-208)
    CERT_NON_UNIQUE_NAME = (-210)
    CERT_WEAK_KEY = (-211)
    CERT_NAME_CONSTRAINT_VIOLATION = (-212)
    CERT_VALIDITY_TOO_LONG = (-213)
    CERTIFICATE_TRANSPARENCY_REQUIRED = (-214)
    CERT_KNOWN_INTERCEPTION_BLOCKED = (-217)
    CERT_SELF_SIGNED_LOCAL_NETWORK = (-219)
    CERT_END = (-220)
    INVALID_URL = (-300)
    DISALLOWED_URL_SCHEME = (-301)
    UNKNOWN_URL_SCHEME = (-302)
    INVALID_REDIRECT = (-303)
    TOO_MANY_REDIRECTS = (-310)
    UNSAFE_REDIRECT = (-311)
    UNSAFE_PORT = (-312)
    INVALID_RESPONSE = (-320)
    INVALID_CHUNKED_ENCODING = (-321)
    METHOD_NOT_SUPPORTED = (-322)
    UNEXPECTED_PROXY_AUTH = (-323)
    EMPTY_RESPONSE = (-324)
    RESPONSE_HEADERS_TOO_BIG = (-325)
    PAC_SCRIPT_FAILED = (-327)
    REQUEST_RANGE_NOT_SATISFIABLE = (-328)
    MALFORMED_IDENTITY = (-329)
    CONTENT_DECODING_FAILED = (-330)
    NETWORK_IO_SUSPENDED = (-331)
    NO_SUPPORTED_PROXIES = (-336)
    HTTP2_PROTOCOL_ERROR = (-337)
    INVALID_AUTH_CREDENTIALS = (-338)
    UNSUPPORTED_AUTH_SCHEME = (-339)
    ENCODING_DETECTION_FAILED = (-340)
    MISSING_AUTH_CREDENTIALS = (-341)
    UNEXPECTED_SECURITY_LIBRARY_STATUS = (-342)
    MISCONFIGURED_AUTH_ENVIRONMENT = (-343)
    UNDOCUMENTED_SECURITY_LIBRARY_STATUS = (-344)
    RESPONSE_BODY_TOO_BIG_TO_DRAIN = (-345)
    RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH = (-346)
    INCOMPLETE_HTTP2_HEADERS = (-347)
    PAC_NOT_IN_DHCP = (-348)
    RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION = (-349)
    RESPONSE_HEADERS_MULTIPLE_LOCATION = (-350)
    HTTP2_SERVER_REFUSED_STREAM = (-351)
    HTTP2_PING_FAILED = (-352)
    CONTENT_LENGTH_MISMATCH = (-354)
    INCOMPLETE_CHUNKED_ENCODING = (-355)
    QUIC_PROTOCOL_ERROR = (-356)
    RESPONSE_HEADERS_TRUNCATED = (-357)
    QUIC_HANDSHAKE_FAILED = (-358)
    HTTP2_INADEQUATE_TRANSPORT_SECURITY = (-360)
    HTTP2_FLOW_CONTROL_ERROR = (-361)
    HTTP2_FRAME_SIZE_ERROR = (-362)
    HTTP2_COMPRESSION_ERROR = (-363)
    PROXY_AUTH_REQUESTED_WITH_NO_CONNECTION = (-364)
    HTTP_1_1_REQUIRED = (-365)
    PROXY_HTTP_1_1_REQUIRED = (-366)
    PAC_SCRIPT_TERMINATED = (-367)
    INVALID_HTTP_RESPONSE = (-370)
    CONTENT_DECODING_INIT_FAILED = (-371)
    HTTP2_RST_STREAM_NO_ERROR_RECEIVED = (-372)
    TOO_MANY_RETRIES = (-375)
    HTTP2_STREAM_CLOSED = (-376)
    HTTP_RESPONSE_CODE_FAILURE = (-379)
    QUIC_CERT_ROOT_NOT_KNOWN = (-380)
    QUIC_GOAWAY_REQUEST_CAN_BE_RETRIED = (-381)
    TOO_MANY_ACCEPT_CH_RESTARTS = (-382)
    INCONSISTENT_IP_ADDRESS_SPACE = (-383)
    CACHED_IP_ADDRESS_SPACE_BLOCKED_BY_LOCAL_NETWORK_ACCESS_POLICY = (-384)
    BLOCKED_BY_LOCAL_NETWORK_ACCESS_CHECKS = (-385)
    ZSTD_WINDOW_SIZE_TOO_BIG = (-386)
    DICTIONARY_LOAD_FAILED = (-387)
    UNEXPECTED_CONTENT_DICTIONARY_HEADER = (-388)
    CACHE_MISS = (-400)
    CACHE_READ_FAILURE = (-401)
    CACHE_WRITE_FAILURE = (-402)
    CACHE_OPERATION_NOT_SUPPORTED = (-403)
    CACHE_OPEN_FAILURE = (-404)
    CACHE_CREATE_FAILURE = (-405)
    CACHE_RACE = (-406)
    CACHE_CHECKSUM_READ_FAILURE = (-407)
    CACHE_CHECKSUM_MISMATCH = (-408)
    CACHE_LOCK_TIMEOUT = (-409)
    CACHE_AUTH_FAILURE_AFTER_READ = (-410)
    CACHE_ENTRY_NOT_SUITABLE = (-411)
    CACHE_DOOM_FAILURE = (-412)
    CACHE_OPEN_OR_CREATE_FAILURE = (-413)
    CACHE_COMPRESSION_FAILURE = (-414)
    INSECURE_RESPONSE = (-501)
    NO_PRIVATE_KEY_FOR_CERT = (-502)
    ADD_USER_CERT_FAILED = (-503)
    INVALID_SIGNED_EXCHANGE = (-504)
    INVALID_WEB_BUNDLE = (-505)
    TRUST_TOKEN_OPERATION_FAILED = (-506)
    TRUST_TOKEN_OPERATION_SUCCESS_WITHOUT_SENDING_REQUEST = (-507)
    HTTPENGINE_PROVIDER_IN_USE = (-508)
    PKCS12_IMPORT_BAD_PASSWORD = (-701)
    PKCS12_IMPORT_FAILED = (-702)
    IMPORT_CA_CERT_NOT_CA = (-703)
    IMPORT_CERT_ALREADY_EXISTS = (-704)
    IMPORT_CA_CERT_FAILED = (-705)
    IMPORT_SERVER_CERT_FAILED = (-706)
    PKCS12_IMPORT_INVALID_MAC = (-707)
    PKCS12_IMPORT_INVALID_FILE = (-708)
    PKCS12_IMPORT_UNSUPPORTED = (-709)
    KEY_GENERATION_FAILED = (-710)
    PRIVATE_KEY_EXPORT_FAILED = (-712)
    SELF_SIGNED_CERT_GENERATION_FAILED = (-713)
    CERT_DATABASE_CHANGED = (-714)
    CERT_VERIFIER_CHANGED = (-716)
    DNS_MALFORMED_RESPONSE = (-800)
    DNS_SERVER_REQUIRES_TCP = (-801)
    DNS_TIMED_OUT = (-803)
    DNS_CACHE_MISS = (-804)
    DNS_SEARCH_EMPTY = (-805)
    DNS_SORT_ERROR = (-806)
    DNS_SECURE_RESOLVER_HOSTNAME_RESOLUTION_FAILED = (-808)
    DNS_NAME_HTTPS_ONLY = (-809)
    DNS_REQUEST_CANCELLED = (-810)
    DNS_NO_MATCHING_SUPPORTED_ALPN = (-811)
    DNS_SECURE_PROBE_RECORD_INVALID = (-814)
    DNS_CACHE_INVALIDATION_IN_PROGRESS = (-815)
    DNS_FORMAT_ERROR = (-816)
    DNS_SERVER_FAILURE = (-817)
    DNS_NOT_IMPLEMENTED = (-818)
    DNS_REFUSED = (-819)
    DNS_OTHER_FAILURE = (-820)
    DNS_DIRECT_ONLY = (-821)
    BLOB_INVALID_CONSTRUCTION_ARGUMENTS = (-900)
    BLOB_OUT_OF_MEMORY = (-901)
    BLOB_FILE_WRITE_FAILED = (-902)
    BLOB_SOURCE_DIED_IN_TRANSIT = (-903)
    BLOB_DEREFERENCED_WHILE_BUILDING = (-904)
    BLOB_REFERENCED_BLOB_BROKEN = (-905)
    BLOB_REFERENCED_FILE_UNAVAILABLE = (-906)


class EventFlags(enum.IntFlag):
    """Supported event bit flags."""
    NONE = 0
    CAPS_LOCK_ON = 1
    SHIFT_DOWN = 2
    CONTROL_DOWN = 4
    ALT_DOWN = 8
    LEFT_MOUSE_BUTTON = 16
    MIDDLE_MOUSE_BUTTON = 32
    RIGHT_MOUSE_BUTTON = 64
    COMMAND_DOWN = 128
    NUM_LOCK_ON = 256
    IS_KEY_PAD = 512
    IS_LEFT = 1024
    IS_RIGHT = 2048
    ALTGR_DOWN = 4096
    IS_REPEAT = 8192
    PRECISION_SCROLLING_DELTA = 16384
    SCROLL_BY_PAGE = 32768


class FileDialogMode(enum.IntEnum):
    """Supported file dialog modes."""
    OPEN = 0
    OPEN_MULTIPLE = 1
    OPEN_FOLDER = 2
    SAVE = 3
    NUM_VALUES = 4


class FocusSource(enum.IntEnum):
    """Focus sources."""
    NAVIGATION = 0
    SYSTEM = 1
    NUM_VALUES = 2


class GestureCommand(enum.IntEnum):
    """Specifies the gesture commands."""
    BACK = 0
    FORWARD = 1


class HorizontalAlignment(enum.IntEnum):
    """Specifies the horizontal text alignment mode."""
    LEFT = 0
    CENTER = 1
    RIGHT = 2


class JSDialogType(enum.IntEnum):
    """Supported JavaScript dialog types."""
    ALERT = 0
    CONFIRM = 1
    PROMPT = 2
    NUM_VALUES = 3


class JsonParserOptions(enum.IntEnum):
    """Options that can be passed to CefParseJSON."""
    RFC = 0
    ALLOW_TRAILING_COMMAS = 1


class JsonWriterOptions(enum.IntFlag):
    """Options that can be passed to CefWriteJSON."""
    DEFAULT = 0
    OMIT_BINARY_VALUES = 1
    OMIT_DOUBLE_TYPE_PRESERVATION = 2
    PRETTY_PRINT = 4


class KeyEventType(enum.IntEnum):
    """Key event types."""
    RAWKEYDOWN = 0
    KEYDOWN = 1
    KEYUP = 2
    CHAR = 3


class LogItems(enum.IntFlag):
    """Log items prepended to each log line."""
    DEFAULT = 0
    NONE = 1
    FLAG_PROCESS_ID = 2
    FLAG_THREAD_ID = 4
    FLAG_TIME_STAMP = 8
    FLAG_TICK_COUNT = 16


class LogSeverity(enum.IntEnum):
    """Log severity levels."""
    DEFAULT = 0
    VERBOSE = 1
    DEBUG = 1
    INFO = 2
    WARNING = 3
    ERROR = 4
    FATAL = 5
    DISABLE = 99


class MediaAccessPermissionTypes(enum.IntFlag):
    """Media access permissions used by OnRequestMediaAccessPermission."""
    NONE = 0
    DEVICE_AUDIO_CAPTURE = 1
    DEVICE_VIDEO_CAPTURE = 2
    DESKTOP_AUDIO_CAPTURE = 4
    DESKTOP_VIDEO_CAPTURE = 8


class MediaRouteConnectionState(enum.IntEnum):
    """Connection state for a MediaRoute object. Should be kept in sync with Chromium's blink::mojom::PresentationConnectionState type."""
    UNKNOWN = (-1)
    CONNECTING = 0
    CONNECTED = 1
    CLOSED = 2
    TERMINATED = 3
    NUM_VALUES = 4


class MediaRouteCreateResult(enum.IntEnum):
    """Result codes for CefMediaRouter::CreateRoute. Should be kept in sync with Chromium's media_router::mojom::RouteRequestResultCode type."""
    UNKNOWN_ERROR = 0
    OK = 1
    TIMED_OUT = 2
    ROUTE_NOT_FOUND = 3
    SINK_NOT_FOUND = 4
    INVALID_ORIGIN = 5
    OFF_THE_RECORD_MISMATCH_DEPRECATED = 6
    NO_SUPPORTED_PROVIDER = 7
    CANCELLED = 8
    ROUTE_ALREADY_EXISTS = 9
    DESKTOP_PICKER_FAILED = 10
    ROUTE_ALREADY_TERMINATED = 11
    REDUNDANT_REQUEST = 12
    USER_NOT_ALLOWED = 13
    NOTIFICATION_DISABLED = 14
    NUM_VALUES = 15


class MediaSinkIconType(enum.IntEnum):
    """Icon types for a MediaSink object. Should be kept in sync with Chromium's media_router::SinkIconType type."""
    CAST = 0
    CAST_AUDIO_GROUP = 1
    CAST_AUDIO = 2
    MEETING = 3
    HANGOUT = 4
    EDUCATION = 5
    WIRED_DISPLAY = 6
    GENERIC = 7
    NUM_VALUES = 8


class MenuAnchorPosition(enum.IntEnum):
    """Specifies how a menu will be anchored for non-RTL languages. The opposite position will be used for RTL languages."""
    TOPLEFT = 0
    TOPRIGHT = 1
    BOTTOMCENTER = 2
    NUM_VALUES = 3


class MenuColorType(enum.IntEnum):
    """Supported color types for menu items."""
    TEXT = 0
    TEXT_HOVERED = 1
    TEXT_ACCELERATOR = 2
    TEXT_ACCELERATOR_HOVERED = 3
    BACKGROUND = 4
    BACKGROUND_HOVERED = 5
    NUM_VALUES = 6


class MenuId(enum.IntEnum):
    """Supported menu IDs. Non-English translations can be provided for the IDS_MENU_* strings in CefResourceBundleHandler::GetLocalizedString()."""
    BACK = 100
    FORWARD = 101
    RELOAD = 102
    RELOAD_NOCACHE = 103
    STOPLOAD = 104
    UNDO = 110
    REDO = 111
    CUT = 112
    COPY = 113
    PASTE = 114
    PASTE_MATCH_STYLE = 115
    DELETE = 116
    SELECT_ALL = 117
    FIND = 130
    PRINT = 131
    VIEW_SOURCE = 132
    SPELLCHECK_SUGGESTION_0 = 200
    SPELLCHECK_SUGGESTION_1 = 201
    SPELLCHECK_SUGGESTION_2 = 202
    SPELLCHECK_SUGGESTION_3 = 203
    SPELLCHECK_SUGGESTION_4 = 204
    SPELLCHECK_SUGGESTION_LAST = 204
    NO_SPELLING_SUGGESTIONS = 205
    ADD_TO_DICTIONARY = 206
    CUSTOM_FIRST = 220
    CUSTOM_LAST = 250
    USER_FIRST = 26500
    USER_LAST = 28500


class MenuItemType(enum.IntEnum):
    """Supported menu item types."""
    NONE = 0
    COMMAND = 1
    CHECK = 2
    RADIO = 3
    SEPARATOR = 4
    SUBMENU = 5


class MessageLoopType(enum.IntEnum):
    """Message loop types. Indicates the set of asynchronous events that a message loop can process."""
    TYPE_DEFAULT = 0
    TYPE_UI = 1
    TYPE_IO = 2
    NUM_VALUES = 3


class MouseButtonType(enum.IntEnum):
    """Mouse button types."""
    LEFT = 0
    MIDDLE = 1
    RIGHT = 2


class NavigationType(enum.IntEnum):
    """Navigation types."""
    LINK_CLICKED = 0
    FORM_SUBMITTED = 1
    BACK_FORWARD = 2
    RELOAD = 3
    FORM_RESUBMITTED = 4
    OTHER = 5
    NUM_VALUES = 6


class PaintElementType(enum.IntEnum):
    """Paint element types."""
    VIEW = 0
    POPUP = 1


class PathKey(enum.IntEnum):
    """Path key values."""
    DIR_CURRENT = 0
    DIR_EXE = 1
    DIR_MODULE = 2
    DIR_TEMP = 3
    FILE_EXE = 4
    FILE_MODULE = 5
    LOCAL_APP_DATA = 6
    USER_DATA = 7
    DIR_RESOURCES = 8
    NUM_VALUES = 9


class PdfPrintMarginType(enum.IntEnum):
    """Margin type for PDF printing."""
    DEFAULT = 0
    NONE = 1
    CUSTOM = 2


class PermissionRequestResult(enum.IntEnum):
    """Permission request results."""
    ACCEPT = 0
    DENY = 1
    DISMISS = 2
    IGNORE = 3
    NUM_VALUES = 4


class PermissionRequestTypes(enum.IntFlag):
    """Permission types used with OnShowPermissionPrompt. Some types are platform-specific or only supported with Chrome style. Should be kept in sync with Chromium's permissions::RequestType type."""
    NONE = 0
    AR_SESSION = 1
    CAMERA_PAN_TILT_ZOOM = 2
    CAMERA_STREAM = 4
    CAPTURED_SURFACE_CONTROL = 8
    CLIPBOARD = 16
    TOP_LEVEL_STORAGE_ACCESS = 32
    DISK_QUOTA = 64
    LOCAL_FONTS = 128
    GEOLOCATION = 256
    HAND_TRACKING = 512
    IDENTITY_PROVIDER = 1024
    IDLE_DETECTION = 2048
    MIC_STREAM = 4096
    MIDI_SYSEX = 8192
    MULTIPLE_DOWNLOADS = 16384
    NOTIFICATIONS = 32768
    KEYBOARD_LOCK = 65536
    POINTER_LOCK = 131072
    PROTECTED_MEDIA_IDENTIFIER = 262144
    REGISTER_PROTOCOL_HANDLER = 524288
    STORAGE_ACCESS = 1048576
    VR_SESSION = 2097152
    WEB_APP_INSTALLATION = 4194304
    WINDOW_MANAGEMENT = 8388608
    FILE_SYSTEM_ACCESS = 16777216
    LOCAL_NETWORK_ACCESS_DEPRECATED = 33554432
    LOCAL_NETWORK = 67108864
    LOOPBACK_NETWORK = 134217728
    SENSORS = 268435456


class PointerType(enum.IntEnum):
    """The device type that caused the event."""
    TOUCH = 0
    MOUSE = 1
    PEN = 2
    ERASER = 3
    UNKNOWN = 4


class PostdataelementType(enum.IntEnum):
    """Post data elements may represent either bytes or files."""
    EMPTY = 0
    BYTES = 1
    FILE = 2
    NUM_VALUES = 3


class PreferencesType(enum.IntEnum):
    """Preferences type passed to CefBrowserProcessHandler::OnRegisterCustomPreferences."""
    GLOBAL = 0
    REQUEST_CONTEXT = 1
    NUM_VALUES = 2


class ProcessId(enum.IntEnum):
    """Existing process IDs."""
    BROWSER = 0
    RENDERER = 1


class QuickMenuEditStateFlags(enum.IntFlag):
    """Supported quick menu state bit flags."""
    NONE = 0
    CAN_ELLIPSIS = 1
    CAN_CUT = 2
    CAN_COPY = 4
    CAN_PASTE = 8


class ReferrerPolicy(enum.IntEnum):
    """Policy for how the Referrer HTTP header value will be sent during navigation. If the `--no-referrers` command-line flag is specified then the policy value will be ignored and the Referrer value will never be sent. Must be kept synchronized with net::URLRequest::ReferrerPolicy from Chromium."""
    CLEAR_REFERRER_ON_TRANSITION_FROM_SECURE_TO_INSECURE = 0
    DEFAULT = 0
    REDUCE_REFERRER_GRANULARITY_ON_TRANSITION_CROSS_ORIGIN = 1
    ORIGIN_ONLY_ON_TRANSITION_CROSS_ORIGIN = 2
    NEVER_CLEAR_REFERRER = 3
    ORIGIN = 4
    CLEAR_REFERRER_ON_TRANSITION_CROSS_ORIGIN = 5
    ORIGIN_CLEAR_ON_TRANSITION_FROM_SECURE_TO_INSECURE = 6
    NO_REFERRER = 7
    NUM_VALUES = 8


class ResourceType(enum.IntEnum):
    """Resource type for a request. These constants match their equivalents in Chromium's ResourceType and should not be renumbered."""
    MAIN_FRAME = 0
    SUB_FRAME = 1
    STYLESHEET = 2
    SCRIPT = 3
    IMAGE = 4
    FONT_RESOURCE = 5
    SUB_RESOURCE = 6
    OBJECT = 7
    MEDIA = 8
    WORKER = 9
    SHARED_WORKER = 10
    PREFETCH = 11
    FAVICON = 12
    XHR = 13
    PING = 14
    SERVICE_WORKER = 15
    CSP_REPORT = 16
    PLUGIN_RESOURCE = 17
    NAVIGATION_PRELOAD_MAIN_FRAME = 19
    NAVIGATION_PRELOAD_SUB_FRAME = 20
    NUM_VALUES = 21


class ResponseFilterStatus(enum.IntEnum):
    """Return values for CefResponseFilter::Filter()."""
    NEED_MORE_DATA = 0
    DONE = 1
    ERROR = 2


class Resultcode(enum.IntEnum):
    """Process result codes. This is not a comprehensive list, as result codes might also include platform-specific crash values (Posix signal or Windows hardware exception), or internal-only implementation values."""
    NORMAL_EXIT = 0
    KILLED = 1
    HUNG = 2
    KILLED_BAD_MESSAGE = 3
    GPU_DEAD_ON_ARRIVAL = 4
    CHROME_FIRST = 5
    BAD_PROCESS_TYPE = 6
    MISSING_DATA = 7
    UNSUPPORTED_PARAM = 13
    PROFILE_IN_USE = 21
    PACK_EXTENSION_ERROR = 22
    NORMAL_EXIT_PROCESS_NOTIFIED = 24
    INVALID_SANDBOX_STATE = 31
    CLOUD_POLICY_ENROLLMENT_FAILED = 32
    GPU_EXIT_ON_CONTEXT_LOST = 34
    NORMAL_EXIT_PACK_EXTENSION_SUCCESS = 36
    SYSTEM_RESOURCE_EXHAUSTED = 37
    NORMAL_EXIT_AUTO_DE_ELEVATED = 38
    TERMINATED_BY_OTHER_PROCESS_ON_COMMIT_FAILURE = 39
    INVALID_ISOLATED_BROWSER_PROCESS = 40
    CHROME_LAST = 41
    SANDBOX_FATAL_FIRST = 7006
    SANDBOX_FATAL_INTEGRITY = 7006
    SANDBOX_FATAL_DROPTOKEN = 7007
    SANDBOX_FATAL_FLUSHANDLES = 7008
    SANDBOX_FATAL_CACHEDISABLE = 7009
    SANDBOX_FATAL_CLOSEHANDLES = 7010
    SANDBOX_FATAL_MITIGATION = 7011
    SANDBOX_FATAL_MEMORY_EXCEEDED = 7012
    SANDBOX_FATAL_WARMUP = 7013
    SANDBOX_FATAL_BROKER_SHUTDOWN_HUNG = 7014
    SANDBOX_FATAL_LAST = 7015
    NUM_VALUES = 7016


class ReturnValue(enum.IntEnum):
    """Return value types."""
    CANCEL = 0
    CONTINUE = 1
    CONTINUE_ASYNC = 2


class RuntimeStyle(enum.IntEnum):
    """CEF supports both a Chrome runtime style (based on the Chrome UI layer) and an Alloy runtime style (based on the Chromium content layer). Chrome style provides the full Chrome UI and browser functionality whereas Alloy style provides less default browser functionality but adds additional client callbacks and support for windowless (off-screen) rendering. The style type is individually configured for each window/browser at creation time and different styles can be mixed during runtime. For additional comparative details on runtime styles see https://chromiumembedded.github.io/cef/architecture#cef3 Windowless rendering will always use Alloy style. Windowed rendering with a default window or client-provided parent window can configure the style via CefWindowInfo.runtime_style. Windowed rendering with the Views framework can configure the style via CefWindowDelegate::GetWindowRuntimeStyle and CefBrowserViewDelegate::GetBrowserRuntimeStyle. Alloy style Windows with the Views framework can host only Alloy style BrowserViews but Chrome style Windows can host both style BrowserViews. Additionally, a Chrome style Window can host at most one Chrome style BrowserView but potentially multiple Alloy style BrowserViews. See CefWindowInfo.runtime_style documentation for any additional platform-specific limitations."""
    DEFAULT = 0
    CHROME = 1
    ALLOY = 2


class ScaleFactor(enum.IntEnum):
    """Supported UI scale factors for the platform. SCALE_FACTOR_NONE is used for density independent resources such as string, html/js files or an image that can be used for any scale factors (such as wallpapers)."""
    NONE = 0
    _100P = 1
    _125P = 2
    _133P = 3
    _140P = 4
    _150P = 5
    _180P = 6
    _200P = 7
    _250P = 8
    _300P = 9
    NUM_VALUES = 10


class SchemeOptions(enum.IntFlag):
    """The CEF enumeration cef_scheme_options_t."""
    NONE = 0
    STANDARD = 1
    LOCAL = 2
    DISPLAY_ISOLATED = 4
    SECURE = 8
    CORS_ENABLED = 16
    CSP_BYPASSING = 32
    FETCH_ENABLED = 64


class ShowState(enum.IntEnum):
    """Show states supported by CefWindowDelegate::GetInitialShowState."""
    NORMAL = 0
    MINIMIZED = 1
    MAXIMIZED = 2
    FULLSCREEN = 3
    HIDDEN = 4
    NUM_VALUES = 5


class SslContentStatus(enum.IntEnum):
    """Supported SSL content status flags. See content/public/common/ssl_status.h for more information."""
    NORMAL_CONTENT = 0
    DISPLAYED_INSECURE_CONTENT = 1
    RAN_INSECURE_CONTENT = 2


class SslVersion(enum.IntEnum):
    """Supported SSL version values. See net/ssl/ssl_connection_status_flags.h for more information."""
    UNKNOWN = 0
    SSL2 = 1
    SSL3 = 2
    TLS1 = 3
    TLS1_1 = 4
    TLS1_2 = 5
    TLS1_3 = 6
    QUIC = 7
    NUM_VALUES = 8


class State(enum.IntEnum):
    """Represents the state of a setting."""
    DEFAULT = 0
    ENABLED = 1
    DISABLED = 2


class StorageType(enum.IntEnum):
    """Storage types."""
    LOCALSTORAGE = 0
    SESSIONSTORAGE = 1


class TaskType(enum.IntEnum):
    """Specifies the task type variants supported by CefTaskManager. Should be kept in sync with Chromium's task_manager::Task::Type type."""
    UNKNOWN = 0
    BROWSER = 1
    GPU = 2
    ZYGOTE = 3
    UTILITY = 4
    RENDERER = 5
    EXTENSION = 6
    GUEST = 7
    PLUGIN_DEPRECATED = 8
    SANDBOX_HELPER = 9
    DEDICATED_WORKER = 10
    SHARED_WORKER = 11
    SERVICE_WORKER = 12
    NUM_VALUES = 13


class TerminationStatus(enum.IntEnum):
    """Process termination status values."""
    ABNORMAL_TERMINATION = 0
    PROCESS_WAS_KILLED = 1
    PROCESS_CRASHED = 2
    PROCESS_OOM = 3
    LAUNCH_FAILED = 4
    INTEGRITY_FAILURE = 5
    NUM_VALUES = 6


class TestCertType(enum.IntEnum):
    """Certificate types supported by CefTestServer::CreateAndStart. The matching certificate file must exist in the "net/data/ssl/certificates" directory. See CefSetDataDirectoryForTests() for related configuration."""
    OK_IP = 0
    OK_DOMAIN = 1
    EXPIRED = 2
    NUM_VALUES = 3


class TextFieldCommands(enum.IntEnum):
    """Represents commands available to TextField. Should be kept in sync with Chromium's views::TextField::MenuCommands type."""
    UNKNOWN = 0
    CUT = 1
    COPY = 2
    PASTE = 3
    SELECT_ALL = 4
    SELECT_WORD = 5
    UNDO = 6
    DELETE = 7
    NUM_VALUES = 8


class TextInputMode(enum.IntEnum):
    """Input mode of a virtual keyboard. These constants match their equivalents in Chromium's text_input_mode.h and should not be renumbered. See https://html.spec.whatwg.org/#input-modalities:-the-inputmode-attribute"""
    DEFAULT = 0
    NONE = 1
    TEXT = 2
    TEL = 3
    URL = 4
    EMAIL = 5
    NUMERIC = 6
    DECIMAL = 7
    SEARCH = 8
    NUM_VALUES = 9


class TextStyle(enum.IntEnum):
    """Text style types. Should be kepy in sync with gfx::TextStyle."""
    BOLD = 0
    ITALIC = 1
    STRIKE = 2
    DIAGONAL_STRIKE = 3
    UNDERLINE = 4
    NUM_VALUES = 5


class ThreadId(enum.IntEnum):
    """Existing thread IDs."""
    UI = 0
    FILE_BACKGROUND = 1
    FILE_USER_VISIBLE = 2
    FILE_USER_BLOCKING = 3
    PROCESS_LAUNCHER = 4
    IO = 5
    RENDERER = 6
    NUM_VALUES = 7


class ThreadPriority(enum.IntEnum):
    """Thread priority values listed in increasing order of importance."""
    BACKGROUND = 0
    NORMAL = 1
    DISPLAY = 2
    REALTIME_AUDIO = 3
    NUM_VALUES = 4


class TouchEventType(enum.IntEnum):
    """Touch points states types."""
    RELEASED = 0
    PRESSED = 1
    MOVED = 2
    CANCELLED = 3


class TouchHandleStateFlags(enum.IntFlag):
    """Values indicating what state of the touch handle is set."""
    NONE = 0
    ENABLED = 1
    ORIENTATION = 2
    ORIGIN = 4
    ALPHA = 8


class TransitionType(enum.IntEnum):
    """Transition type for a request. Made up of one source value and 0 or more qualifiers."""
    LINK = 0
    EXPLICIT = 1
    AUTO_BOOKMARK = 2
    AUTO_SUBFRAME = 3
    MANUAL_SUBFRAME = 4
    GENERATED = 5
    AUTO_TOPLEVEL = 6
    FORM_SUBMIT = 7
    RELOAD = 8
    KEYWORD = 9
    KEYWORD_GENERATED = 10
    NUM_VALUES = 11
    SOURCE_MASK = 255
    BLOCKED_FLAG = 8388608
    FORWARD_BACK_FLAG = 16777216
    DIRECT_LOAD_FLAG = 33554432
    HOME_PAGE_FLAG = 67108864
    FROM_API_FLAG = 134217728
    CHAIN_START_FLAG = 268435456
    CHAIN_END_FLAG = 536870912
    CLIENT_REDIRECT_FLAG = 1073741824
    SERVER_REDIRECT_FLAG = 2147483648
    IS_REDIRECT_MASK = 3221225472
    QUALIFIER_MASK = 4294967040


class URLRequestStatus(enum.IntEnum):
    """Flags that represent CefURLRequest status."""
    UNKNOWN = 0
    SUCCESS = 1
    IO_PENDING = 2
    CANCELED = 3
    FAILED = 4
    NUM_VALUES = 5


class UriUnescapeRule(enum.IntFlag):
    """URI unescape rules passed to CefURIDecode()."""
    NONE = 0
    NORMAL = 1
    SPACES = 2
    PATH_SEPARATORS = 4
    URL_SPECIAL_CHARS_EXCEPT_PATH_SEPARATORS = 8
    REPLACE_PLUS_WITH_SPACE = 16


class UrlrequestFlags(enum.IntFlag):
    """Flags used to customize the behavior of CefURLRequest."""
    NONE = 0
    SKIP_CACHE = 1
    ONLY_FROM_CACHE = 2
    DISABLE_CACHE = 4
    ALLOW_STORED_CREDENTIALS = 8
    REPORT_UPLOAD_PROGRESS = 16
    NO_DOWNLOAD_DATA = 32
    NO_RETRY_ON_5XX = 64
    STOP_ON_REDIRECT = 128


class V8Propertyattribute(enum.IntFlag):
    """V8 property attribute values."""
    NONE = 0
    READONLY = 1
    DONTENUM = 2
    DONTDELETE = 4


class ValueType(enum.IntEnum):
    """Supported value types."""
    INVALID = 0
    NULL = 1
    BOOL = 2
    INT = 3
    DOUBLE = 4
    STRING = 5
    BINARY = 6
    DICTIONARY = 7
    LIST = 8
    NUM_VALUES = 9


class WindowOpenDisposition(enum.IntEnum):
    """The manner in which a link click should be opened. These constants match their equivalents in Chromium's window_open_disposition.h and should not be renumbered."""
    UNKNOWN = 0
    CURRENT_TAB = 1
    SINGLETON_TAB = 2
    NEW_FOREGROUND_TAB = 3
    NEW_BACKGROUND_TAB = 4
    NEW_POPUP = 5
    NEW_WINDOW = 6
    SAVE_TO_DISK = 7
    OFF_THE_RECORD = 8
    IGNORE_ACTION = 9
    SWITCH_TO_TAB = 10
    NEW_PICTURE_IN_PICTURE = 11
    NEW_SPLIT_VIEW = 12
    NUM_VALUES = 13


class XmlEncodingType(enum.IntEnum):
    """Supported XML encoding types. The parser supports ASCII, ISO-8859-1, and UTF16 (LE and BE) by default. All other types must be translated to UTF8 before being passed to the parser. If a BOM is detected and the correct decoder is available then that decoder will be used automatically."""
    NONE = 0
    UTF8 = 1
    UTF16LE = 2
    UTF16BE = 3
    ASCII = 4
    NUM_VALUES = 5


class XmlNodeType(enum.IntEnum):
    """XML node types."""
    UNSUPPORTED = 0
    PROCESSING_INSTRUCTION = 1
    DOCUMENT_TYPE = 2
    ELEMENT_START = 3
    ELEMENT_END = 4
    ATTRIBUTE = 5
    TEXT = 6
    CDATA = 7
    ENTITY_REFERENCE = 8
    WHITESPACE = 9
    COMMENT = 10
    NUM_VALUES = 11


class ZoomCommand(enum.IntEnum):
    """Specifies the zoom commands supported by CefBrowserHost::Zoom."""
    OUT = 0
    RESET = 1
    IN = 2


class AudioParameters(NamedTuple):
    """The CEF value type CefAudioParameters. Anywhere one is expected, a tuple with the same fields works too."""
    channel_layout: ChannelLayout
    sample_rate: int
    frames_per_buffer: int


class Insets(NamedTuple):
    """The CEF value type CefInsets. Anywhere one is expected, a tuple with the same fields works too."""
    top: int
    left: int
    bottom: int
    right: int


class KeyEvent(NamedTuple):
    """The CEF value type CefKeyEvent. Anywhere one is expected, a tuple with the same fields works too."""
    type: KeyEventType
    modifiers: int
    windows_key_code: int
    native_key_code: int
    is_system_key: int
    character: int
    unmodified_character: int
    focus_on_editable_field: int


class MouseEvent(NamedTuple):
    """The CEF value type CefMouseEvent. Anywhere one is expected, a tuple with the same fields works too."""
    x: int
    y: int
    modifiers: int


class Point(NamedTuple):
    """The CEF value type CefPoint. Anywhere one is expected, a tuple with the same fields works too."""
    x: int
    y: int


class PopupFeatures(NamedTuple):
    """The CEF value type CefPopupFeatures. Anywhere one is expected, a tuple with the same fields works too."""
    x: int
    x_set: int
    y: int
    y_set: int
    width: int
    width_set: int
    height: int
    height_set: int
    is_popup: int


class Range(NamedTuple):
    """The CEF value type CefRange. Anywhere one is expected, a tuple with the same fields works too."""
    from_: int
    to: int


class Rect(NamedTuple):
    """The CEF value type CefRect. Anywhere one is expected, a tuple with the same fields works too."""
    x: int
    y: int
    width: int
    height: int


class ScreenInfo(NamedTuple):
    """The CEF value type CefScreenInfo. Anywhere one is expected, a tuple with the same fields works too."""
    device_scale_factor: float
    depth: int
    depth_per_component: int
    is_monochrome: int
    rect: Rect
    available_rect: Rect


class Size(NamedTuple):
    """The CEF value type CefSize. Anywhere one is expected, a tuple with the same fields works too."""
    width: int
    height: int


class TouchEvent(NamedTuple):
    """The CEF value type CefTouchEvent. Anywhere one is expected, a tuple with the same fields works too."""
    id: int
    x: float
    y: float
    radius_x: float
    radius_y: float
    rotation_angle: float
    pressure: float
    type: TouchEventType
    modifiers: int
    pointer_type: PointerType


class TouchHandleState(NamedTuple):
    """The CEF value type CefTouchHandleState. Anywhere one is expected, a tuple with the same fields works too."""
    touch_handle_id: int
    flags: int
    enabled: int
    orientation: HorizontalAlignment
    mirror_vertical: int
    mirror_horizontal: int
    origin: Point
    alpha: float


class BoxLayoutSettings(NamedTuple):
    """The CEF value type CefBoxLayoutSettings. Anywhere one is expected, a tuple with the same fields works too."""
    horizontal: int
    inside_border_horizontal_spacing: int
    inside_border_vertical_spacing: int
    inside_border_insets: Insets
    between_child_spacing: int
    main_axis_alignment: AxisAlignment
    cross_axis_alignment: AxisAlignment
    minimum_cross_axis_size: int
    default_flex: int


class CompositionUnderline(NamedTuple):
    """The CEF value type CefCompositionUnderline. Anywhere one is expected, a tuple with the same fields works too."""
    range: Range
    color: int
    background_color: int
    thick: int
    style: CompositionUnderlineStyle


class DraggableRegion(NamedTuple):
    """The CEF value type CefDraggableRegion. Anywhere one is expected, a tuple with the same fields works too."""
    bounds: Rect
    draggable: int


__all__ = [
    "AlphaType",
    "AudioParameters",
    "AxisAlignment",
    "BoxLayoutSettings",
    "ButtonState",
    "CertStatus",
    "ChannelLayout",
    "ChromePageActionIconType",
    "ChromeToolbarButtonType",
    "ChromeToolbarType",
    "ColorModel",
    "ColorType",
    "ColorVariant",
    "ComInitMode",
    "ComponentState",
    "ComponentUpdateError",
    "ComponentUpdatePriority",
    "CompositionUnderline",
    "CompositionUnderlineStyle",
    "ContentSettingTypes",
    "ContentSettingValues",
    "ContextMenuEditStateFlags",
    "ContextMenuMediaStateFlags",
    "ContextMenuMediaType",
    "ContextMenuTypeFlags",
    "CookiePriority",
    "CookieSameSite",
    "CursorType",
    "DockingMode",
    "DomDocumentType",
    "DomEventCategory",
    "DomEventPhase",
    "DomFormControlType",
    "DomNodeType",
    "DownloadInterruptReason",
    "DragOperationsMask",
    "DraggableRegion",
    "DuplexMode",
    "ErrorCode",
    "EventFlags",
    "FileDialogMode",
    "FocusSource",
    "GestureCommand",
    "HorizontalAlignment",
    "Insets",
    "JSDialogType",
    "JsonParserOptions",
    "JsonWriterOptions",
    "KeyEvent",
    "KeyEventType",
    "LogItems",
    "LogSeverity",
    "MediaAccessPermissionTypes",
    "MediaRouteConnectionState",
    "MediaRouteCreateResult",
    "MediaSinkIconType",
    "MenuAnchorPosition",
    "MenuColorType",
    "MenuId",
    "MenuItemType",
    "MessageLoopType",
    "MouseButtonType",
    "MouseEvent",
    "NavigationType",
    "PaintElementType",
    "PathKey",
    "PdfPrintMarginType",
    "PermissionRequestResult",
    "PermissionRequestTypes",
    "Point",
    "PointerType",
    "PopupFeatures",
    "PostdataelementType",
    "PreferencesType",
    "ProcessId",
    "QuickMenuEditStateFlags",
    "Range",
    "Rect",
    "ReferrerPolicy",
    "ResourceType",
    "ResponseFilterStatus",
    "Resultcode",
    "ReturnValue",
    "RuntimeStyle",
    "ScaleFactor",
    "SchemeOptions",
    "ScreenInfo",
    "ShowState",
    "Size",
    "SslContentStatus",
    "SslVersion",
    "State",
    "StorageType",
    "TaskType",
    "TerminationStatus",
    "TestCertType",
    "TextFieldCommands",
    "TextInputMode",
    "TextStyle",
    "ThreadId",
    "ThreadPriority",
    "TouchEvent",
    "TouchEventType",
    "TouchHandleState",
    "TouchHandleStateFlags",
    "TransitionType",
    "URLRequestStatus",
    "UriUnescapeRule",
    "UrlrequestFlags",
    "V8Propertyattribute",
    "ValueType",
    "WindowOpenDisposition",
    "XmlEncodingType",
    "XmlNodeType",
    "ZoomCommand",
]
