# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class Panel(View):
    """A Panel is a container in the views hierarchy that can contain other Views
    as children. Methods must be called on the browser process UI thread unless
    otherwise indicated.
    """

    cdef CefPanel* _ptr_CefPanel(self) except NULL:
        cdef CefPanel* p = <CefPanel*>self._ref.get()
        if p == NULL:
            raise RuntimeError("Panel has no CEF object")
        return p

    def as_window(self):
        """Returns this Panel as a Window or NULL if this is not a Window."""
        cdef CefPanel* _p = self._ptr_CefPanel()
        cdef CefRefPtr[CefWindow] _r
        with nogil:
            _r = _p.AsWindow()
        return _wrap_Window(_r)

    def set_to_fill_layout(self):
        """Set this Panel's Layout to FillLayout and return the FillLayout object."""
        cdef CefPanel* _p = self._ptr_CefPanel()
        cdef CefRefPtr[CefFillLayout] _r
        with nogil:
            _r = _p.SetToFillLayout()
        return _wrap_FillLayout(_r)

    def set_to_box_layout(self, settings):
        """Set this Panel's Layout to BoxLayout and return the BoxLayout object."""
        cdef CefBoxLayoutSettings _a0
        cdef CefPanel* _p = self._ptr_CefPanel()
        cdef CefRefPtr[CefBoxLayout] _r
        _g_to_BoxLayoutSettings(settings, &_a0)
        with nogil:
            _r = _p.SetToBoxLayout(_a0)
        return _wrap_BoxLayout(_r)

    def get_layout(self):
        """Get the Layout."""
        cdef CefPanel* _p = self._ptr_CefPanel()
        cdef CefRefPtr[CefLayout] _r
        with nogil:
            _r = _p.GetLayout()
        return _wrap_Layout(_r)

    def layout(self):
        """Lay out the child Views (set their bounds based on sizing heuristics
        specific to the current Layout).
        """
        cdef CefPanel* _p = self._ptr_CefPanel()
        with nogil:
            _p.Layout()
        return None

    def add_child_view(self, View view not None):
        """Add a child View."""
        cdef CefRefPtr[CefView] _a0
        cdef CefPanel* _p = self._ptr_CefPanel()
        _a0 = view._ref
        with nogil:
            _p.AddChildView(_a0)
        return None

    def add_child_view_at(self, View view not None, int index):
        """Add a child View at the specified |index|. If |index| matches the result
        of GetChildCount() then the View will be added at the end.
        """
        cdef CefRefPtr[CefView] _a0
        cdef CefPanel* _p = self._ptr_CefPanel()
        _a0 = view._ref
        with nogil:
            _p.AddChildViewAt(_a0, index)
        return None

    def reorder_child_view(self, View view not None, int index):
        """Move the child View to the specified |index|. A negative value for |index|
        will move the View to the end.
        """
        cdef CefRefPtr[CefView] _a0
        cdef CefPanel* _p = self._ptr_CefPanel()
        _a0 = view._ref
        with nogil:
            _p.ReorderChildView(_a0, index)
        return None

    def remove_child_view(self, View view not None):
        """Remove a child View. The View can then be added to another Panel."""
        cdef CefRefPtr[CefView] _a0
        cdef CefPanel* _p = self._ptr_CefPanel()
        _a0 = view._ref
        with nogil:
            _p.RemoveChildView(_a0)
        return None

    def remove_all_child_views(self):
        """Remove all child Views. The removed Views will be deleted if the client
        holds no references to them.
        """
        cdef CefPanel* _p = self._ptr_CefPanel()
        with nogil:
            _p.RemoveAllChildViews()
        return None

    def get_child_view_count(self):
        """Returns the number of child Views."""
        cdef CefPanel* _p = self._ptr_CefPanel()
        cdef size_t _r
        with nogil:
            _r = _p.GetChildViewCount()
        return _r

    def get_child_view_at(self, int index):
        """Returns the child View at the specified |index|."""
        cdef CefPanel* _p = self._ptr_CefPanel()
        cdef CefRefPtr[CefView] _r
        with nogil:
            _r = _p.GetChildViewAt(index)
        return _wrap_View(_r)

    @staticmethod
    def create_panel(delegate):
        """Create a new Panel."""
        cdef CefRefPtr[CefPanelDelegate] _a0
        cdef CefRefPtr[CefPanel] _r
        _a0 = _g_make_PanelDelegate(delegate)
        with nogil:
            _r = CefPanel.CreatePanel(_a0)
        return _wrap_Panel(_r)


cdef object _wrap_Panel(CefRefPtr[CefPanel] ref):
    cdef CefRefPtr[CefWindow] _c0
    cdef Panel obj
    if ref.get() == NULL:
        return None
    _c0 = ref.get().AsWindow()
    if _c0.get() != NULL:
        return _wrap_Window(_c0)
    obj = Panel.__new__(Panel)
    obj._ref = CefRefPtr[CefView](<CefView*>ref.get())
    return obj


cdef inline CefPanel* _g_ref_Panel(object obj) except? NULL:
    """A reference for CEF to keep (a Panel that a handler method returns; None: nothing)."""
    cdef Panel typed
    cdef CefRefPtr[CefPanel] ref
    cdef CefPanel* raw
    if obj is None:
        return NULL
    if not isinstance(obj, Panel):
        raise TypeError("expected a Panel or None, not %s" % type(obj).__name__)
    typed = <Panel>obj
    ref = CefRefPtr[CefPanel](<CefPanel*>typed._ref.get())
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


