# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class WindowDelegate:
    """Implement this interface to handle window events. The methods of this class
    will be called on the browser process UI thread unless otherwise indicated.
    """

    def get_preferred_size(self, view):
        """Return the preferred size for |view|. The Layout will use this information
        to determine the display size.
        """
        return Size()

    def get_minimum_size(self, view):
        """Return the minimum size for |view|."""
        return Size()

    def get_maximum_size(self, view):
        """Return the maximum size for |view|."""
        return Size()

    def get_height_for_width(self, view, width):
        """Return the height necessary to display |view| with the provided |width|.
        If not specified the result of GetPreferredSize().height will be used by
        default. Override if |view|'s preferred height depends upon the width
        (for example, with Labels).
        """
        return 0

    def on_parent_view_changed(self, view, added, parent):
        """Called when the parent of |view| has changed. If |view| is being added to
        |parent| then |added| will be true. If |view| is being removed from
        |parent| then |added| will be false. If |view| is being reparented the
        remove notification will be sent before the add notification. Do not
        modify the view hierarchy in this callback.
        """
        return None

    def on_child_view_changed(self, view, added, child):
        """Called when a child of |view| has changed. If |child| is being added to
        |view| then |added| will be true. If |child| is being removed from |view|
        then |added| will be false. If |child| is being reparented the remove
        notification will be sent to the old parent before the add notification is
        sent to the new parent. Do not modify the view hierarchy in this callback.
        """
        return None

    def on_window_changed(self, view, added):
        """Called when |view| is added or removed from the CefWindow."""
        return None

    def on_layout_changed(self, view, new_bounds):
        """Called when the layout of |view| has changed."""
        return None

    def on_focus(self, view):
        """Called when |view| gains focus."""
        return None

    def on_blur(self, view):
        """Called when |view| loses focus."""
        return None

    def on_theme_changed(self, view):
        """Called when the theme for |view| has changed, after the new theme colors
        have already been applied. Views are notified via the component hierarchy
        in depth-first reverse order (children before parents).

        This will be called in the following cases:

        1. When |view|, or a parent of |view|, is added to a Window.
        2. When the native/OS or Chrome theme changes for the Window that contains
           |view|. See CefWindowDelegate::OnThemeColorsChanged documentation.
        3. When the client explicitly calls CefWindow::ThemeChanged on the Window
           that contains |view|.

        Optionally use this callback to override the new per-View theme colors by
        calling CefView::SetBackgroundColor or the appropriate component-specific
        method. See CefWindow::SetThemeColor documentation for how to customize
        additional Window theme colors.
        """
        return None

    def on_window_created(self, window):
        """Called when |window| is created."""
        return None

    def on_window_closing(self, window):
        """Called when |window| is closing."""
        return None

    def on_window_destroyed(self, window):
        """Called when |window| is destroyed. Release all references to |window| and
        do not attempt to execute any methods on |window| after this callback
        returns.
        """
        return None

    def on_window_activation_changed(self, window, active):
        """Called when |window| is activated or deactivated."""
        return None

    def on_window_bounds_changed(self, window, new_bounds):
        """Called when |window| bounds have changed. |new_bounds| will be in DIP
        screen coordinates.
        """
        return None

    def on_window_fullscreen_transition(self, window, is_completed):
        """Called when |window| is transitioning to or from fullscreen mode. On MacOS
        the transition occurs asynchronously with |is_competed| set to false when
        the transition starts and true after the transition completes. On other
        platforms the transition occurs synchronously with |is_completed| set to
        true after the transition completes. With Alloy style you must also
        implement CefDisplayHandler::OnFullscreenModeChange to handle fullscreen
        transitions initiated by browser content.
        """
        return None

    def is_window_modal_dialog(self, window):
        """Return true if |window| should be created as a window modal dialog. Only
        called when a Window is returned via GetParentWindow() with |is_menu| set
        to false. All controls in the parent Window will be disabled while
        |window| is visible. This functionality is not supported by all Linux
        window managers. Alternately, use CefWindow::ShowAsBrowserModalDialog()
        for a browser modal dialog that works on all platforms.
        """
        return False

    def get_initial_bounds(self, window):
        """Return the initial bounds for |window| in density independent pixel (DIP)
        coordinates. If this method returns an empty CefRect then
        GetPreferredSize() will be called to retrieve the size, and the window
        will be placed on the screen with origin (0,0). This method can be used in
        combination with CefView::GetBoundsInScreen() to restore the previous
        window bounds.
        """
        return Rect()

    def get_initial_show_state(self, window):
        """Return the initial show state for |window|."""
        return 0

    def is_frameless(self, window):
        """Return true if |window| should be created without a frame or title bar.
        The window will be resizable if CanResize() returns true. Use
        CefWindow::SetDraggableRegions() to specify draggable regions.
        """
        return False

    def with_standard_window_buttons(self, window):
        """Return true if |window| should be created with standard window buttons
        like close, minimize and zoom. This method is only supported on macOS.
        """
        return False

    def get_titlebar_height(self, window):
        """Return whether the titlebar height should be overridden, and sets the
        height of the titlebar in |titlebar_height|. On macOS, it can also be used
        to adjust the vertical position of the traffic light buttons in frameless
        windows. The buttons will be positioned halfway down the titlebar at a
        height of |titlebar_height| / 2.
        """
        return False, 0.0

    def accepts_first_mouse(self, window):
        """Return whether the view should accept the initial mouse-down event,
        allowing it to respond to click-through behavior. If STATE_ENABLED is
        returned, the view will be sent a mouseDown: message for an initial
        mouse-down event, activating the view with one click, instead of clicking
        first to make the window active and then clicking the view.

        This method is only supported on macOS. For more details, refer to the
        documentation of acceptsFirstMouse.
        """
        return 0

    def can_resize(self, window):
        """Return true if |window| can be resized."""
        return False

    def can_maximize(self, window):
        """Return true if |window| can be maximized."""
        return False

    def can_minimize(self, window):
        """Return true if |window| can be minimized."""
        return False

    def can_close(self, window):
        """Return true if |window| can be closed. This will be called for user-
        initiated window close actions and when CefWindow::Close() is called.
        """
        return False

    def on_accelerator(self, window, command_id):
        """Called when a keyboard accelerator registered with
        CefWindow::SetAccelerator is triggered. Return true if the accelerator was
        handled or false otherwise.
        """
        return False

    def on_key_event(self, window, event):
        """Called after all other controls in the window have had a chance to
        handle the event. |event| contains information about the keyboard event.
        Return true if the keyboard event was handled or false otherwise.
        """
        return False

    def on_theme_colors_changed(self, window, chrome_theme):
        """Called after the native/OS or Chrome theme for |window| has changed.
        |chrome_theme| will be true if the notification is for a Chrome theme.

        Native/OS theme colors are configured globally and do not need to be
        customized for each Window individually. An example of a native/OS theme
        change that triggers this callback is when the user switches between dark
        and light mode during application lifespan. Native/OS theme changes can be
        disabled by passing the `--force-dark-mode` or `--force-light-mode`
        command-line flag.

        Chrome theme colors will be applied and this callback will be triggered
        if/when a BrowserView is added to the Window's component hierarchy. Chrome
        theme colors can be configured on a per-RequestContext basis using
        CefRequestContext::SetChromeColorScheme or (Chrome style only) by
        visiting chrome://settings/manageProfile. Any theme changes using those
        mechanisms will also trigger this callback. Chrome theme colors will be
        persisted and restored from disk cache.

        This callback is not triggered on Window creation so clients that wish to
        customize the initial native/OS theme must call CefWindow::SetThemeColor
        and CefWindow::ThemeChanged before showing the first Window.

        Theme colors will be reset to standard values before this callback is
        called for the first affected Window. Call CefWindow::SetThemeColor from
        inside this callback to override a standard color or add a custom color.
        CefViewDelegate::OnThemeChanged will be called after this callback for the
        complete |window| component hierarchy.
        """
        return None

    def get_window_runtime_style(self):
        """Optionally change the runtime style for this Window. See
        cef_runtime_style_t documentation for details.
        """
        return 0

    def get_linux_window_properties(self, window):
        """Return Linux-specific window properties for correctly handling by window
        managers
        """
        return False, LinuxWindowProperties()


cdef void _WindowDelegate_get_preferred_size(void* py, CefView* view, CefSize* result) noexcept with gil:
    try:
        _r = (<object>py).get_preferred_size(_wrap_View(CefRefPtr[CefView](view)))
        _r0 = _r
        _g_to_Size(_r0, result)
    except BaseException:
        _g_report()

cdef void _WindowDelegate_get_minimum_size(void* py, CefView* view, CefSize* result) noexcept with gil:
    try:
        _r = (<object>py).get_minimum_size(_wrap_View(CefRefPtr[CefView](view)))
        _r0 = _r
        _g_to_Size(_r0, result)
    except BaseException:
        _g_report()

cdef void _WindowDelegate_get_maximum_size(void* py, CefView* view, CefSize* result) noexcept with gil:
    try:
        _r = (<object>py).get_maximum_size(_wrap_View(CefRefPtr[CefView](view)))
        _r0 = _r
        _g_to_Size(_r0, result)
    except BaseException:
        _g_report()

cdef int _WindowDelegate_get_height_for_width(void* py, CefView* view, int width) noexcept with gil:
    try:
        _r = (<object>py).get_height_for_width(_wrap_View(CefRefPtr[CefView](view)), width)
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _WindowDelegate_on_parent_view_changed(void* py, CefView* view, cpp_bool added, CefView* parent) noexcept with gil:
    try:
        _r = (<object>py).on_parent_view_changed(_wrap_View(CefRefPtr[CefView](view)), added, _wrap_View(CefRefPtr[CefView](parent)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_child_view_changed(void* py, CefView* view, cpp_bool added, CefView* child) noexcept with gil:
    try:
        _r = (<object>py).on_child_view_changed(_wrap_View(CefRefPtr[CefView](view)), added, _wrap_View(CefRefPtr[CefView](child)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_window_changed(void* py, CefView* view, cpp_bool added) noexcept with gil:
    try:
        _r = (<object>py).on_window_changed(_wrap_View(CefRefPtr[CefView](view)), added)
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_layout_changed(void* py, CefView* view, const CefRect* new_bounds) noexcept with gil:
    try:
        _r = (<object>py).on_layout_changed(_wrap_View(CefRefPtr[CefView](view)), _g_from_Rect(new_bounds))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_focus(void* py, CefView* view) noexcept with gil:
    try:
        _r = (<object>py).on_focus(_wrap_View(CefRefPtr[CefView](view)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_blur(void* py, CefView* view) noexcept with gil:
    try:
        _r = (<object>py).on_blur(_wrap_View(CefRefPtr[CefView](view)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_theme_changed(void* py, CefView* view) noexcept with gil:
    try:
        _r = (<object>py).on_theme_changed(_wrap_View(CefRefPtr[CefView](view)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_window_created(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).on_window_created(_wrap_Window(CefRefPtr[CefWindow](window)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_window_closing(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).on_window_closing(_wrap_Window(CefRefPtr[CefWindow](window)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_window_destroyed(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).on_window_destroyed(_wrap_Window(CefRefPtr[CefWindow](window)))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_window_activation_changed(void* py, CefWindow* window, cpp_bool active) noexcept with gil:
    try:
        _r = (<object>py).on_window_activation_changed(_wrap_Window(CefRefPtr[CefWindow](window)), active)
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_window_bounds_changed(void* py, CefWindow* window, const CefRect* new_bounds) noexcept with gil:
    try:
        _r = (<object>py).on_window_bounds_changed(_wrap_Window(CefRefPtr[CefWindow](window)), _g_from_Rect(new_bounds))
    except BaseException:
        _g_report()

cdef void _WindowDelegate_on_window_fullscreen_transition(void* py, CefWindow* window, cpp_bool is_completed) noexcept with gil:
    try:
        _r = (<object>py).on_window_fullscreen_transition(_wrap_Window(CefRefPtr[CefWindow](window)), is_completed)
    except BaseException:
        _g_report()

cdef cpp_bool _WindowDelegate_is_window_modal_dialog(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).is_window_modal_dialog(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _WindowDelegate_get_initial_bounds(void* py, CefWindow* window, CefRect* result) noexcept with gil:
    try:
        _r = (<object>py).get_initial_bounds(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        _g_to_Rect(_r0, result)
    except BaseException:
        _g_report()

cdef int _WindowDelegate_get_initial_show_state(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).get_initial_show_state(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return <int>_r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_is_frameless(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).is_frameless(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_with_standard_window_buttons(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).with_standard_window_buttons(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_get_titlebar_height(void* py, CefWindow* window, float* titlebar_height) noexcept with gil:
    try:
        _r = (<object>py).get_titlebar_height(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0, _r1 = _r
        titlebar_height[0] = _r1
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef int _WindowDelegate_accepts_first_mouse(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).accepts_first_mouse(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return <int>_r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_can_resize(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).can_resize(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_can_maximize(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).can_maximize(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_can_minimize(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).can_minimize(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_can_close(void* py, CefWindow* window) noexcept with gil:
    try:
        _r = (<object>py).can_close(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_on_accelerator(void* py, CefWindow* window, int command_id) noexcept with gil:
    try:
        _r = (<object>py).on_accelerator(_wrap_Window(CefRefPtr[CefWindow](window)), command_id)
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_on_key_event(void* py, CefWindow* window, const CefKeyEvent* event) noexcept with gil:
    try:
        _r = (<object>py).on_key_event(_wrap_Window(CefRefPtr[CefWindow](window)), _g_from_KeyEvent(event))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _WindowDelegate_on_theme_colors_changed(void* py, CefWindow* window, cpp_bool chrome_theme) noexcept with gil:
    try:
        _r = (<object>py).on_theme_colors_changed(_wrap_Window(CefRefPtr[CefWindow](window)), chrome_theme)
    except BaseException:
        _g_report()

cdef int _WindowDelegate_get_window_runtime_style(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_window_runtime_style()
        _r0 = _r
        return <int>_r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _WindowDelegate_get_linux_window_properties(void* py, CefWindow* window, CefLinuxWindowProperties* properties) noexcept with gil:
    try:
        _r = (<object>py).get_linux_window_properties(_wrap_Window(CefRefPtr[CefWindow](window)))
        _r0, _r1 = _r
        _g_to_LinuxWindowProperties(_r1, properties)
        return _r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefWindowDelegate] _g_make_WindowDelegate(object obj) except *:
    cdef CefRefPtr[CefWindowDelegate] ref
    cdef CwWindowDelegateCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, WindowDelegate):
        raise TypeError("expected a WindowDelegate or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "get_preferred_size", None) is not WindowDelegate.get_preferred_size:
        cb.fn_get_preferred_size = _WindowDelegate_get_preferred_size
    if getattr(cls, "get_minimum_size", None) is not WindowDelegate.get_minimum_size:
        cb.fn_get_minimum_size = _WindowDelegate_get_minimum_size
    if getattr(cls, "get_maximum_size", None) is not WindowDelegate.get_maximum_size:
        cb.fn_get_maximum_size = _WindowDelegate_get_maximum_size
    if getattr(cls, "get_height_for_width", None) is not WindowDelegate.get_height_for_width:
        cb.fn_get_height_for_width = _WindowDelegate_get_height_for_width
    if getattr(cls, "on_parent_view_changed", None) is not WindowDelegate.on_parent_view_changed:
        cb.fn_on_parent_view_changed = _WindowDelegate_on_parent_view_changed
    if getattr(cls, "on_child_view_changed", None) is not WindowDelegate.on_child_view_changed:
        cb.fn_on_child_view_changed = _WindowDelegate_on_child_view_changed
    if getattr(cls, "on_window_changed", None) is not WindowDelegate.on_window_changed:
        cb.fn_on_window_changed = _WindowDelegate_on_window_changed
    if getattr(cls, "on_layout_changed", None) is not WindowDelegate.on_layout_changed:
        cb.fn_on_layout_changed = _WindowDelegate_on_layout_changed
    if getattr(cls, "on_focus", None) is not WindowDelegate.on_focus:
        cb.fn_on_focus = _WindowDelegate_on_focus
    if getattr(cls, "on_blur", None) is not WindowDelegate.on_blur:
        cb.fn_on_blur = _WindowDelegate_on_blur
    if getattr(cls, "on_theme_changed", None) is not WindowDelegate.on_theme_changed:
        cb.fn_on_theme_changed = _WindowDelegate_on_theme_changed
    if getattr(cls, "on_window_created", None) is not WindowDelegate.on_window_created:
        cb.fn_on_window_created = _WindowDelegate_on_window_created
    if getattr(cls, "on_window_closing", None) is not WindowDelegate.on_window_closing:
        cb.fn_on_window_closing = _WindowDelegate_on_window_closing
    if getattr(cls, "on_window_destroyed", None) is not WindowDelegate.on_window_destroyed:
        cb.fn_on_window_destroyed = _WindowDelegate_on_window_destroyed
    if getattr(cls, "on_window_activation_changed", None) is not WindowDelegate.on_window_activation_changed:
        cb.fn_on_window_activation_changed = _WindowDelegate_on_window_activation_changed
    if getattr(cls, "on_window_bounds_changed", None) is not WindowDelegate.on_window_bounds_changed:
        cb.fn_on_window_bounds_changed = _WindowDelegate_on_window_bounds_changed
    if getattr(cls, "on_window_fullscreen_transition", None) is not WindowDelegate.on_window_fullscreen_transition:
        cb.fn_on_window_fullscreen_transition = _WindowDelegate_on_window_fullscreen_transition
    if getattr(cls, "is_window_modal_dialog", None) is not WindowDelegate.is_window_modal_dialog:
        cb.fn_is_window_modal_dialog = _WindowDelegate_is_window_modal_dialog
    if getattr(cls, "get_initial_bounds", None) is not WindowDelegate.get_initial_bounds:
        cb.fn_get_initial_bounds = _WindowDelegate_get_initial_bounds
    if getattr(cls, "get_initial_show_state", None) is not WindowDelegate.get_initial_show_state:
        cb.fn_get_initial_show_state = _WindowDelegate_get_initial_show_state
    if getattr(cls, "is_frameless", None) is not WindowDelegate.is_frameless:
        cb.fn_is_frameless = _WindowDelegate_is_frameless
    if getattr(cls, "with_standard_window_buttons", None) is not WindowDelegate.with_standard_window_buttons:
        cb.fn_with_standard_window_buttons = _WindowDelegate_with_standard_window_buttons
    if getattr(cls, "get_titlebar_height", None) is not WindowDelegate.get_titlebar_height:
        cb.fn_get_titlebar_height = _WindowDelegate_get_titlebar_height
    if getattr(cls, "accepts_first_mouse", None) is not WindowDelegate.accepts_first_mouse:
        cb.fn_accepts_first_mouse = _WindowDelegate_accepts_first_mouse
    if getattr(cls, "can_resize", None) is not WindowDelegate.can_resize:
        cb.fn_can_resize = _WindowDelegate_can_resize
    if getattr(cls, "can_maximize", None) is not WindowDelegate.can_maximize:
        cb.fn_can_maximize = _WindowDelegate_can_maximize
    if getattr(cls, "can_minimize", None) is not WindowDelegate.can_minimize:
        cb.fn_can_minimize = _WindowDelegate_can_minimize
    if getattr(cls, "can_close", None) is not WindowDelegate.can_close:
        cb.fn_can_close = _WindowDelegate_can_close
    if getattr(cls, "on_accelerator", None) is not WindowDelegate.on_accelerator:
        cb.fn_on_accelerator = _WindowDelegate_on_accelerator
    if getattr(cls, "on_key_event", None) is not WindowDelegate.on_key_event:
        cb.fn_on_key_event = _WindowDelegate_on_key_event
    if getattr(cls, "on_theme_colors_changed", None) is not WindowDelegate.on_theme_colors_changed:
        cb.fn_on_theme_colors_changed = _WindowDelegate_on_theme_colors_changed
    if getattr(cls, "get_window_runtime_style", None) is not WindowDelegate.get_window_runtime_style:
        cb.fn_get_window_runtime_style = _WindowDelegate_get_window_runtime_style
    if getattr(cls, "get_linux_window_properties", None) is not WindowDelegate.get_linux_window_properties:
        cb.fn_get_linux_window_properties = _WindowDelegate_get_linux_window_properties
    ref = CefRefPtr[CefWindowDelegate](<CefWindowDelegate*>new CwWindowDelegateProxy(cb))
    return ref


cdef inline CefWindowDelegate* _g_export_WindowDelegate(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefWindowDelegate] ref = _g_make_WindowDelegate(obj)
    cdef CefWindowDelegate* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


