# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class DragHandler:
    """Implement this interface to handle events related to dragging. The methods
    of this class will be called on the UI thread.
    """

    def on_drag_enter(self, browser, drag_data, mask):
        """Called when an external drag event enters the browser window. |dragData|
        contains the drag event data and |mask| represents the type of drag
        operation. Return false for default drag handling behavior or true to
        cancel the drag event.
        """
        return False

    def on_draggable_regions_changed(self, browser, frame, regions):
        """Called whenever draggable regions for the browser window change. These can
        be specified using the '-webkit-app-region: drag/no-drag' CSS-property. If
        draggable regions are never defined in a document this method will also
        never be called. If the last draggable region is removed from a document
        this method will be called with an empty vector.
        """
        return None


cdef cpp_bool _DragHandler_on_drag_enter(void* py, CefBrowser* browser, CefDragData* drag_data, int mask) noexcept with gil:
    try:
        _r = (<object>py).on_drag_enter(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_DragData(CefRefPtr[CefDragData](drag_data)), _g_enum(_types.DragOperationsMask, mask))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _DragHandler_on_draggable_regions_changed(void* py, CefBrowser* browser, CefFrame* frame, const vector[CefDraggableRegion]* regions) noexcept with gil:
    try:
        _r = (<object>py).on_draggable_regions_changed(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), _g_list_DraggableRegion(regions))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefDragHandler] _g_make_DragHandler(object obj) except *:
    cdef CefRefPtr[CefDragHandler] ref
    cdef CwDragHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, DragHandler):
        raise TypeError("expected a DragHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_drag_enter", None) is not DragHandler.on_drag_enter:
        cb.fn_on_drag_enter = _DragHandler_on_drag_enter
    if getattr(cls, "on_draggable_regions_changed", None) is not DragHandler.on_draggable_regions_changed:
        cb.fn_on_draggable_regions_changed = _DragHandler_on_draggable_regions_changed
    ref = CefRefPtr[CefDragHandler](<CefDragHandler*>new CwDragHandlerProxy(cb))
    return ref


cdef inline CefDragHandler* _g_export_DragHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefDragHandler] ref = _g_make_DragHandler(obj)
    cdef CefDragHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_DragHandler(CefRefPtr[CefDragHandler] ref):
    """The Python object that was given to CEF as this DragHandler (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfDragHandler(ref.get())
    if py == NULL:
        return None
    return <object>py


