# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class ProcessMessage:
    """Class representing a message. Can be used on any process and thread."""
    cdef CefRefPtr[CefProcessMessage] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("ProcessMessage objects are created by CEF or by a create() function")

    cdef CefProcessMessage* _ptr(self) except NULL:
        cdef CefProcessMessage* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("ProcessMessage has no CEF object")
        return p

    def is_valid(self):
        """Returns true if this object is valid. Do not call any other methods if
        this function returns false.
        """
        cdef CefProcessMessage* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsValid()
        return _r

    def is_read_only(self):
        """Returns true if the values of this object are read-only. Some APIs may
        expose read-only objects.
        """
        cdef CefProcessMessage* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsReadOnly()
        return _r

    def copy(self):
        """Returns a writable copy of this object.
        Returns nullptr when message contains a shared memory region.
        """
        cdef CefProcessMessage* _p = self._ptr()
        cdef CefRefPtr[CefProcessMessage] _r
        with nogil:
            _r = _p.Copy()
        return _wrap_ProcessMessage(_r)

    def get_name(self):
        """Returns the message name."""
        cdef CefProcessMessage* _p = self._ptr()
        cdef CefString _r
        with nogil:
            _r = _p.GetName()
        return _g_str(_r)

    def get_argument_list(self):
        """Returns the list of arguments.
        Returns nullptr when message contains a shared memory region.
        """
        cdef CefProcessMessage* _p = self._ptr()
        cdef CefRefPtr[CefListValue] _r
        with nogil:
            _r = _p.GetArgumentList()
        return _wrap_ListValue(_r)

    @staticmethod
    def create(name):
        """Create a new CefProcessMessage object with the specified name."""
        cdef CefString _a0
        cdef CefRefPtr[CefProcessMessage] _r
        _a0 = _g_cef(name)
        with nogil:
            _r = CefProcessMessage.Create(_a0)
        return _wrap_ProcessMessage(_r)


cdef object _wrap_ProcessMessage(CefRefPtr[CefProcessMessage] ref):
    cdef ProcessMessage obj
    if ref.get() == NULL:
        return None
    obj = ProcessMessage.__new__(ProcessMessage)
    obj._ref = ref
    return obj


