# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class TaskManager:
    """Class that facilitates managing the browser-related tasks.
    The methods of this class may only be called on the UI thread.
    """
    cdef CefRefPtr[CefTaskManager] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("TaskManager objects are created by CEF or by a create() function")

    cdef CefTaskManager* _ptr(self) except NULL:
        cdef CefTaskManager* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("TaskManager has no CEF object")
        return p

    def get_tasks_count(self):
        """Returns the number of tasks currently tracked by the task manager.
        Returns 0 if the method was called from the incorrect thread.
        """
        cdef CefTaskManager* _p = self._ptr()
        cdef size_t _r
        with nogil:
            _r = _p.GetTasksCount()
        return _r

    def get_task_ids_list(self):
        """Gets the list of task IDs currently tracked by the task manager. Tasks
        that share the same process id will always be consecutive. The list will
        be sorted in a way that reflects the process tree: the browser process
        will be first, followed by the gpu process if it exists. Related processes
        (e.g., a subframe process and its parent) will be kept together if
        possible. Callers can expect this ordering to be stable when a process is
        added or removed. The task IDs are unique within the application lifespan.
        Returns false if the method was called from the incorrect thread.
        """
        cdef vector[int64_t] _a0
        cdef CefTaskManager* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.GetTaskIdsList(_a0)
        return (_r, _g_list_int64_t(&_a0))

    def get_task_info(self, int64_t task_id, info):
        """Gets information about the task with |task_id|.
        Returns true if the information about the task was successfully
        retrieved and false if the |task_id| is invalid or the method was called
        from the incorrect thread.
        """
        cdef CefTaskInfo _a1
        cdef CefTaskManager* _p = self._ptr()
        cdef cpp_bool _r
        _g_to_TaskInfo(info, &_a1)
        with nogil:
            _r = _p.GetTaskInfo(task_id, _a1)
        return (_r, _g_from_TaskInfo(&_a1))

    def kill_task(self, int64_t task_id):
        """Attempts to terminate a task with |task_id|.
        Returns false if the |task_id| is invalid, the call is made from an
        incorrect thread, or if the task cannot be terminated.
        """
        cdef CefTaskManager* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.KillTask(task_id)
        return _r

    def get_task_id_for_browser_id(self, int browser_id):
        """Returns the task ID associated with the main task for |browser_id|
        (value from CefBrowser::GetIdentifier). Returns -1 if |browser_id| is
        invalid, does not currently have an associated task, or the method was
        called from the incorrect thread.
        """
        cdef CefTaskManager* _p = self._ptr()
        cdef int64_t _r
        with nogil:
            _r = _p.GetTaskIdForBrowserId(browser_id)
        return _r

    @staticmethod
    def get_task_manager():
        """Returns the global task manager object.
        Returns nullptr if the method was called from the incorrect thread.
        """
        cdef CefRefPtr[CefTaskManager] _r
        with nogil:
            _r = CefTaskManager.GetTaskManager()
        return _wrap_TaskManager(_r)


cdef object _wrap_TaskManager(CefRefPtr[CefTaskManager] ref):
    cdef TaskManager obj
    if ref.get() == NULL:
        return None
    obj = TaskManager.__new__(TaskManager)
    obj._ref = ref
    return obj


cdef inline CefTaskManager* _g_ref_TaskManager(object obj) except? NULL:
    """A reference for CEF to keep (a TaskManager that a handler method returns; None: nothing)."""
    cdef TaskManager typed
    cdef CefRefPtr[CefTaskManager] ref
    cdef CefTaskManager* raw
    if obj is None:
        return NULL
    if not isinstance(obj, TaskManager):
        raise TypeError("expected a TaskManager or None, not %s" % type(obj).__name__)
    typed = <TaskManager>obj
    ref = typed._ref
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


