# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class DevToolsMessageObserver:
    """Callback interface for CefBrowserHost::AddDevToolsMessageObserver. The
    methods of this class will be called on the browser process UI thread.
    """

    def on_dev_tools_message(self, browser, message):
        """Method that will be called on receipt of a DevTools protocol message.
        |browser| is the originating browser instance. |message| is a UTF8-encoded
        JSON dictionary representing either a method result or an event. |message|
        is only valid for the scope of this callback and should be copied if
        necessary. Return true if the message was handled or false if the message
        should be further processed and passed to the OnDevToolsMethodResult or
        OnDevToolsEvent methods as appropriate.

        Method result dictionaries include an \"id\" (int) value that identifies the
        orginating method call sent from CefBrowserHost::SendDevToolsMessage, and
        optionally either a \"result\" (dictionary) or \"error\" (dictionary) value.
        The \"error\" dictionary will contain \"code\" (int) and \"message\" (string)
        values. Event dictionaries include a \"method\" (string) value and
        optionally a \"params\" (dictionary) value. See the DevTools protocol
        documentation at https://chromedevtools.github.io/devtools-protocol/ for
        details of supported method calls and the expected \"result\" or \"params\"
        dictionary contents. JSON dictionaries can be parsed using the
        CefParseJSON function if desired, however be aware of performance
        considerations when parsing large messages (some of which may exceed 1MB
        in size).
        """
        return False

    def on_dev_tools_method_result(self, browser, message_id, success, result):
        """Method that will be called after attempted execution of a DevTools
        protocol method. |browser| is the originating browser instance.
        |message_id| is the \"id\" value that identifies the originating method call
        message. If the method succeeded |success| will be true and |result| will
        be the UTF8-encoded JSON \"result\" dictionary value (which may be empty).
        If the method failed |success| will be false and |result| will be the
        UTF8-encoded JSON \"error\" dictionary value. |result| is only valid for the
        scope of this callback and should be copied if necessary. See the
        OnDevToolsMessage documentation for additional details on |result|
        contents.
        """
        return None

    def on_dev_tools_event(self, browser, method, params):
        """Method that will be called on receipt of a DevTools protocol event.
        |browser| is the originating browser instance. |method| is the \"method\"
        value. |params| is the UTF8-encoded JSON \"params\" dictionary value (which
        may be empty). |params| is only valid for the scope of this callback and
        should be copied if necessary. See the OnDevToolsMessage documentation for
        additional details on |params| contents.
        """
        return None

    def on_dev_tools_agent_attached(self, browser):
        """Method that will be called when the DevTools agent has attached. |browser|
        is the originating browser instance. This will generally occur in response
        to the first message sent while the agent is detached.
        """
        return None

    def on_dev_tools_agent_detached(self, browser):
        """Method that will be called when the DevTools agent has detached. |browser|
        is the originating browser instance. Any method results that were pending
        before the agent became detached will not be delivered, and any active
        event subscriptions will be canceled.
        """
        return None


cdef cpp_bool _DevToolsMessageObserver_on_dev_tools_message(void* py, CefBrowser* browser, void* message, size_t message_size) noexcept with gil:
    try:
        _view_message = PyMemoryView_FromMemory(<char*>message, message_size, PyBUF_READ)
        try:
            _r = (<object>py).on_dev_tools_message(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _view_message)
        finally:
            try:
                _view_message.release()
            except BaseException:
                pass
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _DevToolsMessageObserver_on_dev_tools_method_result(void* py, CefBrowser* browser, int message_id, cpp_bool success, void* result, size_t result_size) noexcept with gil:
    try:
        _view_result = PyMemoryView_FromMemory(<char*>result, result_size, PyBUF_READ)
        try:
            _r = (<object>py).on_dev_tools_method_result(_wrap_Browser(CefRefPtr[CefBrowser](browser)), message_id, success, _view_result)
        finally:
            try:
                _view_result.release()
            except BaseException:
                pass
    except BaseException:
        _g_report()

cdef void _DevToolsMessageObserver_on_dev_tools_event(void* py, CefBrowser* browser, const CefString* method, void* params, size_t params_size) noexcept with gil:
    try:
        _view_params = PyMemoryView_FromMemory(<char*>params, params_size, PyBUF_READ)
        try:
            _r = (<object>py).on_dev_tools_event(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_str(method[0]), _view_params)
        finally:
            try:
                _view_params.release()
            except BaseException:
                pass
    except BaseException:
        _g_report()

cdef void _DevToolsMessageObserver_on_dev_tools_agent_attached(void* py, CefBrowser* browser) noexcept with gil:
    try:
        _r = (<object>py).on_dev_tools_agent_attached(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
    except BaseException:
        _g_report()

cdef void _DevToolsMessageObserver_on_dev_tools_agent_detached(void* py, CefBrowser* browser) noexcept with gil:
    try:
        _r = (<object>py).on_dev_tools_agent_detached(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefDevToolsMessageObserver] _g_make_DevToolsMessageObserver(object obj) except *:
    cdef CefRefPtr[CefDevToolsMessageObserver] ref
    cdef CwDevToolsMessageObserverCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, DevToolsMessageObserver):
        raise TypeError("expected a DevToolsMessageObserver or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_dev_tools_message", None) is not DevToolsMessageObserver.on_dev_tools_message:
        cb.fn_on_dev_tools_message = _DevToolsMessageObserver_on_dev_tools_message
    if getattr(cls, "on_dev_tools_method_result", None) is not DevToolsMessageObserver.on_dev_tools_method_result:
        cb.fn_on_dev_tools_method_result = _DevToolsMessageObserver_on_dev_tools_method_result
    if getattr(cls, "on_dev_tools_event", None) is not DevToolsMessageObserver.on_dev_tools_event:
        cb.fn_on_dev_tools_event = _DevToolsMessageObserver_on_dev_tools_event
    if getattr(cls, "on_dev_tools_agent_attached", None) is not DevToolsMessageObserver.on_dev_tools_agent_attached:
        cb.fn_on_dev_tools_agent_attached = _DevToolsMessageObserver_on_dev_tools_agent_attached
    if getattr(cls, "on_dev_tools_agent_detached", None) is not DevToolsMessageObserver.on_dev_tools_agent_detached:
        cb.fn_on_dev_tools_agent_detached = _DevToolsMessageObserver_on_dev_tools_agent_detached
    ref = CefRefPtr[CefDevToolsMessageObserver](<CefDevToolsMessageObserver*>new CwDevToolsMessageObserverProxy(cb))
    return ref


cdef inline CefDevToolsMessageObserver* _g_export_DevToolsMessageObserver(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefDevToolsMessageObserver] ref = _g_make_DevToolsMessageObserver(obj)
    cdef CefDevToolsMessageObserver* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


