# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class NavigationEntry:
    """Class used to represent an entry in navigation history."""
    cdef CefRefPtr[CefNavigationEntry] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("NavigationEntry objects are created by CEF or by a create() function")

    cdef CefNavigationEntry* _ptr(self) except NULL:
        cdef CefNavigationEntry* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("NavigationEntry has no CEF object")
        return p

    def is_valid(self):
        """Returns true if this object is valid. Do not call any other methods if
        this function returns false.
        """
        cdef CefNavigationEntry* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsValid()
        return _r

    def get_url(self):
        """Returns the actual URL of the page. For some pages this may be data: URL
        or similar. Use GetDisplayURL() to return a display-friendly version.
        """
        cdef CefNavigationEntry* _p = self._ptr()
        cdef CefString _r
        with nogil:
            _r = _p.GetURL()
        return _g_str(_r)

    def get_display_url(self):
        """Returns a display-friendly version of the URL."""
        cdef CefNavigationEntry* _p = self._ptr()
        cdef CefString _r
        with nogil:
            _r = _p.GetDisplayURL()
        return _g_str(_r)

    def get_original_url(self):
        """Returns the original URL that was entered by the user before any
        redirects.
        """
        cdef CefNavigationEntry* _p = self._ptr()
        cdef CefString _r
        with nogil:
            _r = _p.GetOriginalURL()
        return _g_str(_r)

    def get_title(self):
        """Returns the title set by the page. This value may be empty."""
        cdef CefNavigationEntry* _p = self._ptr()
        cdef CefString _r
        with nogil:
            _r = _p.GetTitle()
        return _g_str(_r)

    def get_transition_type(self):
        """Returns the transition type which indicates what the user did to move to
        this page from the previous page.
        """
        cdef CefNavigationEntry* _p = self._ptr()
        cdef cef_transition_type_t _r
        with nogil:
            _r = _p.GetTransitionType()
        return _g_enum(_types.TransitionType, <int>_r)

    def has_post_data(self):
        """Returns true if this navigation includes post data."""
        cdef CefNavigationEntry* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasPostData()
        return _r

    def get_completion_time(self):
        """Returns the time for the last known successful navigation completion. A
        navigation may be completed more than once if the page is reloaded. May be
        0 if the navigation has not yet completed.
        """
        cdef CefNavigationEntry* _p = self._ptr()
        cdef CefBaseTime _r
        with nogil:
            _r = _p.GetCompletionTime()
        return _g_from_basetime(_r.val)

    def get_http_status_code(self):
        """Returns the HTTP status code for the last known successful navigation
        response. May be 0 if the response has not yet been received or if the
        navigation has not yet completed.
        """
        cdef CefNavigationEntry* _p = self._ptr()
        cdef int _r
        with nogil:
            _r = _p.GetHttpStatusCode()
        return _r

    def get_ssl_status(self):
        """Returns the SSL information for this navigation entry."""
        cdef CefNavigationEntry* _p = self._ptr()
        cdef CefRefPtr[CefSSLStatus] _r
        with nogil:
            _r = _p.GetSSLStatus()
        return _wrap_SSLStatus(_r)


cdef object _wrap_NavigationEntry(CefRefPtr[CefNavigationEntry] ref):
    cdef NavigationEntry obj
    if ref.get() == NULL:
        return None
    obj = NavigationEntry.__new__(NavigationEntry)
    obj._ref = ref
    return obj


cdef inline CefNavigationEntry* _g_ref_NavigationEntry(object obj) except? NULL:
    """A reference for CEF to keep (a NavigationEntry that a handler method returns; None: nothing)."""
    cdef NavigationEntry typed
    cdef CefRefPtr[CefNavigationEntry] ref
    cdef CefNavigationEntry* raw
    if obj is None:
        return NULL
    if not isinstance(obj, NavigationEntry):
        raise TypeError("expected a NavigationEntry or None, not %s" % type(obj).__name__)
    typed = <NavigationEntry>obj
    ref = typed._ref
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


