# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class DisplayHandler:
    """Implement this interface to handle events related to browser display state.
    The methods of this class will be called on the UI thread.
    """

    def on_address_change(self, browser, frame, url):
        """Called when a frame's address has changed."""
        return None

    def on_title_change(self, browser, title):
        """Called when the page title changes."""
        return None

    def on_favicon_url_change(self, browser, icon_urls):
        """Called when the page icon changes."""
        return None

    def on_fullscreen_mode_change(self, browser, fullscreen):
        """Called when web content in the page has toggled fullscreen mode. If
        |fullscreen| is true the content will automatically be sized to fill the
        browser content area. If |fullscreen| is false the content will
        automatically return to its original size and position. With Alloy style
        the client is responsible for triggering the fullscreen transition (for
        example, by calling CefWindow::SetFullscreen when using Views). With
        Chrome style the fullscreen transition will be triggered automatically.
        The CefWindowDelegate::OnWindowFullscreenTransition method will be called
        during the fullscreen transition for notification purposes.
        """
        return None

    def on_tooltip(self, browser):
        """Called when the browser is about to display a tooltip. |text| contains the
        text that will be displayed in the tooltip. To handle the display of the
        tooltip yourself return true. Otherwise, you can optionally modify |text|
        and then return false to allow the browser to display the tooltip.
        When window rendering is disabled the application is responsible for
        drawing tooltips and the return value is ignored.
        """
        return False, ""

    def on_status_message(self, browser, value):
        """Called when the browser receives a status message. |value| contains the
        text that will be displayed in the status message.
        """
        return None

    def on_console_message(self, browser, level, message, source, line):
        """Called to display a console message. Return true to stop the message from
        being output to the console.
        """
        return False

    def on_auto_resize(self, browser, new_size):
        """Called when auto-resize is enabled via
        CefBrowserHost::SetAutoResizeEnabled and the contents have auto-resized.
        |new_size| will be the desired size in DIP coordinates. Return true if
        the resize was handled or false for default handling.
        """
        return False

    def on_loading_progress_change(self, browser, progress):
        """Called when the overall page loading progress has changed. |progress|
        ranges from 0.0 to 1.0.
        """
        return None

    def on_cursor_change(self, browser, type):
        """Called when the browser's cursor has changed. If |type| is CT_CUSTOM then
        |custom_cursor_info| will be populated with the custom cursor information.
        Return true if the cursor change was handled or false for default
        handling.
        """
        return False

    def on_media_access_change(self, browser, has_video_access, has_audio_access):
        """Called when the browser's access to an audio and/or video source has
        changed.
        """
        return None

    def on_contents_bounds_change(self, browser, new_bounds):
        """Called when JavaScript is requesting new bounds via window.moveTo/By() or
        window.resizeTo/By(). |new_bounds| are in DIP screen coordinates.

        With Views-hosted browsers |new_bounds| are the desired bounds for
        the containing CefWindow and may be passed directly to
        CefWindow::SetBounds. With external (client-provided) parent on macOS and
        Windows |new_bounds| are the desired frame bounds for the containing root
        window. With other non-Views browsers |new_bounds| are the desired bounds
        for the browser content only unless the client implements either
        CefDisplayHandler::GetRootWindowScreenRect for windowed browsers or
        CefRenderHandler::GetWindowScreenRect for windowless browsers. Clients may
        expand browser content bounds to window bounds using OS-specific or
        CefDisplay methods.

        Return true if this method was handled or false for default handling.
        Default move/resize behavior is only provided with Views-hosted Chrome
        style browsers.
        """
        return False

    def get_root_window_screen_rect(self, browser):
        """Called to retrieve the external (client-provided) root window rectangle in
        screen DIP coordinates. Only called for windowed browsers on Windows and
        Linux. Return true if the rectangle was provided. Return false to use the
        root window bounds on Windows or the browser content bounds on Linux. For
        additional usage details see CefBrowserHost::NotifyScreenInfoChanged.
        """
        return False, Rect()


cdef void _DisplayHandler_on_address_change(void* py, CefBrowser* browser, CefFrame* frame, const CefString* url) noexcept with gil:
    try:
        _r = (<object>py).on_address_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), _g_str(url[0]))
    except BaseException:
        _g_report()

cdef void _DisplayHandler_on_title_change(void* py, CefBrowser* browser, const CefString* title) noexcept with gil:
    try:
        _r = (<object>py).on_title_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_str(title[0]))
    except BaseException:
        _g_report()

cdef void _DisplayHandler_on_favicon_url_change(void* py, CefBrowser* browser, const vector[CefString]* icon_urls) noexcept with gil:
    try:
        _r = (<object>py).on_favicon_url_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_str_list(icon_urls))
    except BaseException:
        _g_report()

cdef void _DisplayHandler_on_fullscreen_mode_change(void* py, CefBrowser* browser, cpp_bool fullscreen) noexcept with gil:
    try:
        _r = (<object>py).on_fullscreen_mode_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), fullscreen)
    except BaseException:
        _g_report()

cdef cpp_bool _DisplayHandler_on_tooltip(void* py, CefBrowser* browser, CefString* text) noexcept with gil:
    try:
        _r = (<object>py).on_tooltip(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
        _r0, _r1 = _r
        text[0] = _g_cef(_r1)
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _DisplayHandler_on_status_message(void* py, CefBrowser* browser, const CefString* value) noexcept with gil:
    try:
        _r = (<object>py).on_status_message(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_str(value[0]))
    except BaseException:
        _g_report()

cdef cpp_bool _DisplayHandler_on_console_message(void* py, CefBrowser* browser, int level, const CefString* message, const CefString* source, int line) noexcept with gil:
    try:
        _r = (<object>py).on_console_message(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.LogSeverity, level), _g_str(message[0]), _g_str(source[0]), line)
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _DisplayHandler_on_auto_resize(void* py, CefBrowser* browser, const CefSize* new_size) noexcept with gil:
    try:
        _r = (<object>py).on_auto_resize(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_from_Size(new_size))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _DisplayHandler_on_loading_progress_change(void* py, CefBrowser* browser, double progress) noexcept with gil:
    try:
        _r = (<object>py).on_loading_progress_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), progress)
    except BaseException:
        _g_report()

cdef cpp_bool _DisplayHandler_on_cursor_change(void* py, CefBrowser* browser, int type) noexcept with gil:
    try:
        _r = (<object>py).on_cursor_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.CursorType, type))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _DisplayHandler_on_media_access_change(void* py, CefBrowser* browser, cpp_bool has_video_access, cpp_bool has_audio_access) noexcept with gil:
    try:
        _r = (<object>py).on_media_access_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), has_video_access, has_audio_access)
    except BaseException:
        _g_report()

cdef cpp_bool _DisplayHandler_on_contents_bounds_change(void* py, CefBrowser* browser, const CefRect* new_bounds) noexcept with gil:
    try:
        _r = (<object>py).on_contents_bounds_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_from_Rect(new_bounds))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _DisplayHandler_get_root_window_screen_rect(void* py, CefBrowser* browser, CefRect* rect) noexcept with gil:
    try:
        _r = (<object>py).get_root_window_screen_rect(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
        _r0, _r1 = _r
        _g_to_Rect(_r1, rect)
        return _r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefDisplayHandler] _g_make_DisplayHandler(object obj) except *:
    cdef CefRefPtr[CefDisplayHandler] ref
    cdef CwDisplayHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, DisplayHandler):
        raise TypeError("expected a DisplayHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_address_change", None) is not DisplayHandler.on_address_change:
        cb.fn_on_address_change = _DisplayHandler_on_address_change
    if getattr(cls, "on_title_change", None) is not DisplayHandler.on_title_change:
        cb.fn_on_title_change = _DisplayHandler_on_title_change
    if getattr(cls, "on_favicon_url_change", None) is not DisplayHandler.on_favicon_url_change:
        cb.fn_on_favicon_url_change = _DisplayHandler_on_favicon_url_change
    if getattr(cls, "on_fullscreen_mode_change", None) is not DisplayHandler.on_fullscreen_mode_change:
        cb.fn_on_fullscreen_mode_change = _DisplayHandler_on_fullscreen_mode_change
    if getattr(cls, "on_tooltip", None) is not DisplayHandler.on_tooltip:
        cb.fn_on_tooltip = _DisplayHandler_on_tooltip
    if getattr(cls, "on_status_message", None) is not DisplayHandler.on_status_message:
        cb.fn_on_status_message = _DisplayHandler_on_status_message
    if getattr(cls, "on_console_message", None) is not DisplayHandler.on_console_message:
        cb.fn_on_console_message = _DisplayHandler_on_console_message
    if getattr(cls, "on_auto_resize", None) is not DisplayHandler.on_auto_resize:
        cb.fn_on_auto_resize = _DisplayHandler_on_auto_resize
    if getattr(cls, "on_loading_progress_change", None) is not DisplayHandler.on_loading_progress_change:
        cb.fn_on_loading_progress_change = _DisplayHandler_on_loading_progress_change
    if getattr(cls, "on_cursor_change", None) is not DisplayHandler.on_cursor_change:
        cb.fn_on_cursor_change = _DisplayHandler_on_cursor_change
    if getattr(cls, "on_media_access_change", None) is not DisplayHandler.on_media_access_change:
        cb.fn_on_media_access_change = _DisplayHandler_on_media_access_change
    if getattr(cls, "on_contents_bounds_change", None) is not DisplayHandler.on_contents_bounds_change:
        cb.fn_on_contents_bounds_change = _DisplayHandler_on_contents_bounds_change
    if getattr(cls, "get_root_window_screen_rect", None) is not DisplayHandler.get_root_window_screen_rect:
        cb.fn_get_root_window_screen_rect = _DisplayHandler_get_root_window_screen_rect
    ref = CefRefPtr[CefDisplayHandler](<CefDisplayHandler*>new CwDisplayHandlerProxy(cb))
    return ref


cdef inline CefDisplayHandler* _g_export_DisplayHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefDisplayHandler] ref = _g_make_DisplayHandler(obj)
    cdef CefDisplayHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_DisplayHandler(CefRefPtr[CefDisplayHandler] ref):
    """The Python object that was given to CEF as this DisplayHandler (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfDisplayHandler(ref.get())
    if py == NULL:
        return None
    return <object>py


