# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class KeyboardHandler:
    """Implement this interface to handle events related to keyboard input. The
    methods of this class will be called on the UI thread.
    """

    def on_pre_key_event(self, browser, event):
        """Called before a keyboard event is sent to the renderer. |event| contains
        information about the keyboard event. |os_event| is the operating system
        event message, if any. Return true if the event was handled or false
        otherwise. If the event will be handled in OnKeyEvent() as a keyboard
        shortcut set |is_keyboard_shortcut| to true and return false.
        """
        return False, False

    def on_key_event(self, browser, event):
        """Called after the renderer and JavaScript in the page has had a chance to
        handle the event. |event| contains information about the keyboard event.
        |os_event| is the operating system event message, if any. Return true if
        the keyboard event was handled or false otherwise.
        """
        return False


cdef cpp_bool _KeyboardHandler_on_pre_key_event(void* py, CefBrowser* browser, const CefKeyEvent* event, cpp_bool* is_keyboard_shortcut) noexcept with gil:
    try:
        _r = (<object>py).on_pre_key_event(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_from_KeyEvent(event))
        _r0, _r1 = _r
        is_keyboard_shortcut[0] = _r1
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _KeyboardHandler_on_key_event(void* py, CefBrowser* browser, const CefKeyEvent* event) noexcept with gil:
    try:
        _r = (<object>py).on_key_event(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_from_KeyEvent(event))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefKeyboardHandler] _g_make_KeyboardHandler(object obj) except *:
    cdef CefRefPtr[CefKeyboardHandler] ref
    cdef CwKeyboardHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, KeyboardHandler):
        raise TypeError("expected a KeyboardHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_pre_key_event", None) is not KeyboardHandler.on_pre_key_event:
        cb.fn_on_pre_key_event = _KeyboardHandler_on_pre_key_event
    if getattr(cls, "on_key_event", None) is not KeyboardHandler.on_key_event:
        cb.fn_on_key_event = _KeyboardHandler_on_key_event
    ref = CefRefPtr[CefKeyboardHandler](<CefKeyboardHandler*>new CwKeyboardHandlerProxy(cb))
    return ref


cdef inline CefKeyboardHandler* _g_export_KeyboardHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefKeyboardHandler] ref = _g_make_KeyboardHandler(obj)
    cdef CefKeyboardHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


