# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class PrintSettings:
    """Class representing print settings."""
    cdef CefRefPtr[CefPrintSettings] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("PrintSettings objects are created by CEF or by a create() function")

    cdef CefPrintSettings* _ptr(self) except NULL:
        cdef CefPrintSettings* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("PrintSettings has no CEF object")
        return p

    def is_valid(self):
        """Returns true if this object is valid. Do not call any other methods if
        this function returns false.
        """
        cdef CefPrintSettings* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsValid()
        return _r

    def is_read_only(self):
        """Returns true if the values of this object are read-only. Some APIs may
        expose read-only objects.
        """
        cdef CefPrintSettings* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsReadOnly()
        return _r

    def set_orientation(self, bint landscape):
        """Set the page orientation."""
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.SetOrientation(landscape)
        return None

    def is_landscape(self):
        """Returns true if the orientation is landscape."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsLandscape()
        return _r

    def set_printer_printable_area(self, physical_size_device_units, printable_area_device_units, bint landscape_needs_flip):
        """Set the printer printable area in device units.
        Some platforms already provide flipped area. Set |landscape_needs_flip|
        to false on those platforms to avoid double flipping.
        """
        cdef CefSize _a0
        cdef CefRect _a1
        cdef CefPrintSettings* _p = self._ptr()
        _g_to_Size(physical_size_device_units, &_a0)
        _g_to_Rect(printable_area_device_units, &_a1)
        with nogil:
            _p.SetPrinterPrintableArea(_a0, _a1, landscape_needs_flip)
        return None

    def set_device_name(self, name):
        """Set the device name."""
        cdef CefString _a0
        cdef CefPrintSettings* _p = self._ptr()
        if name is not None:
            _a0 = _g_cef(name)
        with nogil:
            _p.SetDeviceName(_a0)
        return None

    def get_device_name(self):
        """Get the device name."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef CefString _r
        with nogil:
            _r = _p.GetDeviceName()
        return _g_str(_r)

    def set_dpi(self, int dpi):
        """Set the DPI (dots per inch)."""
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.SetDPI(dpi)
        return None

    def get_dpi(self):
        """Get the DPI (dots per inch)."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef int _r
        with nogil:
            _r = _p.GetDPI()
        return _r

    def set_page_ranges(self, ranges):
        """Set the page ranges."""
        cdef vector[CefRange] _a0
        cdef CefPrintSettings* _p = self._ptr()
        _g_vector_Range(ranges, _a0)
        with nogil:
            _p.SetPageRanges(_a0)
        return None

    def get_page_ranges_count(self):
        """Returns the number of page ranges that currently exist."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef size_t _r
        with nogil:
            _r = _p.GetPageRangesCount()
        return _r

    def get_page_ranges(self):
        """Retrieve the page ranges."""
        cdef vector[CefRange] _a0
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.GetPageRanges(_a0)
        return _g_list_Range(&_a0)

    def set_selection_only(self, bint selection_only):
        """Set whether only the selection will be printed."""
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.SetSelectionOnly(selection_only)
        return None

    def is_selection_only(self):
        """Returns true if only the selection will be printed."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsSelectionOnly()
        return _r

    def set_collate(self, bint collate):
        """Set whether pages will be collated."""
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.SetCollate(collate)
        return None

    def will_collate(self):
        """Returns true if pages will be collated."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.WillCollate()
        return _r

    def set_color_model(self, long long model):
        """Set the color model."""
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.SetColorModel(<cef_color_model_t>model)
        return None

    def get_color_model(self):
        """Get the color model."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef cef_color_model_t _r
        with nogil:
            _r = _p.GetColorModel()
        return _g_enum(_types.ColorModel, <int>_r)

    def set_copies(self, int copies):
        """Set the number of copies."""
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.SetCopies(copies)
        return None

    def get_copies(self):
        """Get the number of copies."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef int _r
        with nogil:
            _r = _p.GetCopies()
        return _r

    def set_duplex_mode(self, long long mode):
        """Set the duplex mode."""
        cdef CefPrintSettings* _p = self._ptr()
        with nogil:
            _p.SetDuplexMode(<cef_duplex_mode_t>mode)
        return None

    def get_duplex_mode(self):
        """Get the duplex mode."""
        cdef CefPrintSettings* _p = self._ptr()
        cdef cef_duplex_mode_t _r
        with nogil:
            _r = _p.GetDuplexMode()
        return _g_enum(_types.DuplexMode, <int>_r)

    @staticmethod
    def create():
        """Create a new CefPrintSettings object."""
        cdef CefRefPtr[CefPrintSettings] _r
        with nogil:
            _r = CefPrintSettings.Create()
        return _wrap_PrintSettings(_r)


cdef object _wrap_PrintSettings(CefRefPtr[CefPrintSettings] ref):
    cdef PrintSettings obj
    if ref.get() == NULL:
        return None
    obj = PrintSettings.__new__(PrintSettings)
    obj._ref = ref
    return obj


