# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class ResponseFilter:
    """Implement this interface to filter resource response content. The methods of
    this class will be called on the browser process IO thread.
    """

    def init_filter(self):
        """Initialize the response filter. Will only be called a single time. The
        filter will not be installed if this method returns false.
        """
        return False

    def filter(self, data_in, data_out):
        """Called to filter a chunk of data. Expected usage is as follows:

         1. Read input data from |data_in| and set |data_in_read| to the number of
            bytes that were read up to a maximum of |data_in_size|. |data_in| will
            be NULL if |data_in_size| is zero.
         2. Write filtered output data to |data_out| and set |data_out_written| to
            the number of bytes that were written up to a maximum of
            |data_out_size|. If no output data was written then all data must be
            read from |data_in| (user must set |data_in_read| = |data_in_size|).
         3. Return RESPONSE_FILTER_DONE if all output data was written or
            RESPONSE_FILTER_NEED_MORE_DATA if output data is still pending.

        This method will be called repeatedly until the input buffer has been
        fully read (user sets |data_in_read| = |data_in_size|) and there is no
        more input data to filter (the resource response is complete). This method
        may then be called an additional time with an empty input buffer if the
        user filled the output buffer (set |data_out_written| = |data_out_size|)
        and returned RESPONSE_FILTER_NEED_MORE_DATA to indicate that output data
        is still pending.

        Calls to this method will stop when one of the following conditions is
        met:

         1. There is no more input data to filter (the resource response is
            complete) and the user sets |data_out_written| = 0 or returns
            RESPONSE_FILTER_DONE to indicate that all data has been written, or;
         2. The user returns RESPONSE_FILTER_ERROR to indicate an error.

        Do not keep a reference to the buffers passed to this method.
        """
        return 0, 0, 0


cdef cpp_bool _ResponseFilter_init_filter(void* py) noexcept with gil:
    try:
        _r = (<object>py).init_filter()
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef int _ResponseFilter_filter(void* py, void* data_in, size_t data_in_size, size_t* data_in_read, void* data_out, size_t data_out_size, size_t* data_out_written) noexcept with gil:
    try:
        _view_data_in = PyMemoryView_FromMemory(<char*>data_in, data_in_size, PyBUF_WRITE)
        _view_data_out = PyMemoryView_FromMemory(<char*>data_out, data_out_size, PyBUF_WRITE)
        try:
            _r = (<object>py).filter(_view_data_in, _view_data_out)
        finally:
            try:
                _view_data_in.release()
            except BaseException:
                pass
            try:
                _view_data_out.release()
            except BaseException:
                pass
        _r0, _r1, _r2 = _r
        data_in_read[0] = _r1
        data_out_written[0] = _r2
        return <int>_r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefResponseFilter] _g_make_ResponseFilter(object obj) except *:
    cdef CefRefPtr[CefResponseFilter] ref
    cdef CwResponseFilterCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, ResponseFilter):
        raise TypeError("expected a ResponseFilter or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "init_filter", None) is not ResponseFilter.init_filter:
        cb.fn_init_filter = _ResponseFilter_init_filter
    if getattr(cls, "filter", None) is not ResponseFilter.filter:
        cb.fn_filter = _ResponseFilter_filter
    ref = CefRefPtr[CefResponseFilter](<CefResponseFilter*>new CwResponseFilterProxy(cb))
    return ref


cdef inline CefResponseFilter* _g_export_ResponseFilter(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefResponseFilter] ref = _g_make_ResponseFilter(obj)
    cdef CefResponseFilter* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_ResponseFilter(CefRefPtr[CefResponseFilter] ref):
    """The Python object that was given to CEF as this ResponseFilter (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfResponseFilter(ref.get())
    if py == NULL:
        return None
    return <object>py


