# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class FocusHandler:
    """Implement this interface to handle events related to focus. The methods of
    this class will be called on the UI thread.
    """

    def on_take_focus(self, browser, next):
        """Called when the browser component is about to loose focus. For instance,
        if focus was on the last HTML element and the user pressed the TAB key.
        |next| will be true if the browser is giving focus to the next component
        and false if the browser is giving focus to the previous component.
        """
        return None

    def on_set_focus(self, browser, source):
        """Called when the browser component is requesting focus. |source| indicates
        where the focus request is originating from. Return false to allow the
        focus to be set or true to cancel setting the focus.
        """
        return False

    def on_got_focus(self, browser):
        """Called when the browser component has received focus."""
        return None


cdef void _FocusHandler_on_take_focus(void* py, CefBrowser* browser, cpp_bool next) noexcept with gil:
    try:
        _r = (<object>py).on_take_focus(_wrap_Browser(CefRefPtr[CefBrowser](browser)), next)
    except BaseException:
        _g_report()

cdef cpp_bool _FocusHandler_on_set_focus(void* py, CefBrowser* browser, int source) noexcept with gil:
    try:
        _r = (<object>py).on_set_focus(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.FocusSource, source))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _FocusHandler_on_got_focus(void* py, CefBrowser* browser) noexcept with gil:
    try:
        _r = (<object>py).on_got_focus(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefFocusHandler] _g_make_FocusHandler(object obj) except *:
    cdef CefRefPtr[CefFocusHandler] ref
    cdef CwFocusHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, FocusHandler):
        raise TypeError("expected a FocusHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_take_focus", None) is not FocusHandler.on_take_focus:
        cb.fn_on_take_focus = _FocusHandler_on_take_focus
    if getattr(cls, "on_set_focus", None) is not FocusHandler.on_set_focus:
        cb.fn_on_set_focus = _FocusHandler_on_set_focus
    if getattr(cls, "on_got_focus", None) is not FocusHandler.on_got_focus:
        cb.fn_on_got_focus = _FocusHandler_on_got_focus
    ref = CefRefPtr[CefFocusHandler](<CefFocusHandler*>new CwFocusHandlerProxy(cb))
    return ref


cdef inline CefFocusHandler* _g_export_FocusHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefFocusHandler] ref = _g_make_FocusHandler(obj)
    cdef CefFocusHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


