# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class Client:
    """Implement this interface to provide handler implementations."""

    def get_context_menu_handler(self):
        """Return the handler for context menus. If no handler is provided the
        default implementation will be used.
        """
        return None

    def get_dialog_handler(self):
        """Return the handler for dialogs. If no handler is provided the default
        implementation will be used.
        """
        return None

    def get_display_handler(self):
        """Return the handler for browser display state events."""
        return None

    def get_download_handler(self):
        """Return the handler for download events. If no handler is returned
        downloads will be canceled with Alloy style and will proceed with default
        handling with Chrome style.
        """
        return None

    def get_drag_handler(self):
        """Return the handler for drag events."""
        return None

    def get_focus_handler(self):
        """Return the handler for focus events."""
        return None

    def get_permission_handler(self):
        """Return the handler for permission requests."""
        return None

    def get_js_dialog_handler(self):
        """Return the handler for JavaScript dialogs. If no handler is provided the
        default implementation will be used.
        """
        return None

    def get_keyboard_handler(self):
        """Return the handler for keyboard events."""
        return None

    def get_life_span_handler(self):
        """Return the handler for browser life span events."""
        return None

    def get_load_handler(self):
        """Return the handler for browser load status events."""
        return None

    def get_print_handler(self):
        """Return the handler for printing on Linux. If a print handler is not
        provided then printing will not be supported on the Linux platform.
        """
        return None

    def get_render_handler(self):
        """Return the handler for off-screen rendering events."""
        return None

    def get_request_handler(self):
        """Return the handler for browser request events."""
        return None

    def on_process_message_received(self, browser, frame, source_process, message):
        """Called when a new message is received from a different process. Return
        true if the message was handled or false otherwise.  It is safe to keep a
        reference to |message| outside of this callback.
        """
        return False


cdef CefContextMenuHandler* _Client_get_context_menu_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_context_menu_handler()
        _r0 = _r
        return _g_export_ContextMenuHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefDialogHandler* _Client_get_dialog_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_dialog_handler()
        _r0 = _r
        return _g_export_DialogHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefDisplayHandler* _Client_get_display_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_display_handler()
        _r0 = _r
        return _g_export_DisplayHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefDownloadHandler* _Client_get_download_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_download_handler()
        _r0 = _r
        return _g_export_DownloadHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefDragHandler* _Client_get_drag_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_drag_handler()
        _r0 = _r
        return _g_export_DragHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefFocusHandler* _Client_get_focus_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_focus_handler()
        _r0 = _r
        return _g_export_FocusHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefPermissionHandler* _Client_get_permission_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_permission_handler()
        _r0 = _r
        return _g_export_PermissionHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefJSDialogHandler* _Client_get_js_dialog_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_js_dialog_handler()
        _r0 = _r
        return _g_export_JSDialogHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefKeyboardHandler* _Client_get_keyboard_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_keyboard_handler()
        _r0 = _r
        return _g_export_KeyboardHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefLifeSpanHandler* _Client_get_life_span_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_life_span_handler()
        _r0 = _r
        return _g_export_LifeSpanHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefLoadHandler* _Client_get_load_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_load_handler()
        _r0 = _r
        return _g_export_LoadHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefPrintHandler* _Client_get_print_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_print_handler()
        _r0 = _r
        return _g_export_PrintHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefRenderHandler* _Client_get_render_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_render_handler()
        _r0 = _r
        return _g_export_RenderHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef CefRequestHandler* _Client_get_request_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_request_handler()
        _r0 = _r
        return _g_export_RequestHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef cpp_bool _Client_on_process_message_received(void* py, CefBrowser* browser, CefFrame* frame, int source_process, CefProcessMessage* message) noexcept with gil:
    try:
        _r = (<object>py).on_process_message_received(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), _g_enum(_types.ProcessId, source_process), _wrap_ProcessMessage(CefRefPtr[CefProcessMessage](message)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefClient] _g_make_Client(object obj) except *:
    cdef CefRefPtr[CefClient] ref
    cdef CwClientCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, Client):
        raise TypeError("expected a Client or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "get_context_menu_handler", None) is not Client.get_context_menu_handler:
        cb.fn_get_context_menu_handler = _Client_get_context_menu_handler
    if getattr(cls, "get_dialog_handler", None) is not Client.get_dialog_handler:
        cb.fn_get_dialog_handler = _Client_get_dialog_handler
    if getattr(cls, "get_display_handler", None) is not Client.get_display_handler:
        cb.fn_get_display_handler = _Client_get_display_handler
    if getattr(cls, "get_download_handler", None) is not Client.get_download_handler:
        cb.fn_get_download_handler = _Client_get_download_handler
    if getattr(cls, "get_drag_handler", None) is not Client.get_drag_handler:
        cb.fn_get_drag_handler = _Client_get_drag_handler
    if getattr(cls, "get_focus_handler", None) is not Client.get_focus_handler:
        cb.fn_get_focus_handler = _Client_get_focus_handler
    if getattr(cls, "get_permission_handler", None) is not Client.get_permission_handler:
        cb.fn_get_permission_handler = _Client_get_permission_handler
    if getattr(cls, "get_js_dialog_handler", None) is not Client.get_js_dialog_handler:
        cb.fn_get_js_dialog_handler = _Client_get_js_dialog_handler
    if getattr(cls, "get_keyboard_handler", None) is not Client.get_keyboard_handler:
        cb.fn_get_keyboard_handler = _Client_get_keyboard_handler
    if getattr(cls, "get_life_span_handler", None) is not Client.get_life_span_handler:
        cb.fn_get_life_span_handler = _Client_get_life_span_handler
    if getattr(cls, "get_load_handler", None) is not Client.get_load_handler:
        cb.fn_get_load_handler = _Client_get_load_handler
    if getattr(cls, "get_print_handler", None) is not Client.get_print_handler:
        cb.fn_get_print_handler = _Client_get_print_handler
    if getattr(cls, "get_render_handler", None) is not Client.get_render_handler:
        cb.fn_get_render_handler = _Client_get_render_handler
    if getattr(cls, "get_request_handler", None) is not Client.get_request_handler:
        cb.fn_get_request_handler = _Client_get_request_handler
    if getattr(cls, "on_process_message_received", None) is not Client.on_process_message_received:
        cb.fn_on_process_message_received = _Client_on_process_message_received
    ref = CefRefPtr[CefClient](<CefClient*>new CwClientProxy(cb))
    return ref


cdef inline CefClient* _g_export_Client(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefClient] ref = _g_make_Client(obj)
    cdef CefClient* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


