# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class BoxLayout(Layout):
    """A Layout manager that arranges child views vertically or horizontally in a
    side-by-side fashion with spacing around and between the child views. The
    child views are always sized according to their preferred size. If the
    host's bounds provide insufficient space, child views will be clamped.
    Excess space will not be distributed. Methods must be called on the browser
    process UI thread unless otherwise indicated.
    """

    cdef CefBoxLayout* _ptr_CefBoxLayout(self) except NULL:
        cdef CefBoxLayout* p = <CefBoxLayout*>self._ref.get()
        if p == NULL:
            raise RuntimeError("BoxLayout has no CEF object")
        return p

    def set_flex_for_view(self, View view not None, int flex):
        """Set the flex weight for the given |view|. Using the preferred size as
        the basis, free space along the main axis is distributed to views in the
        ratio of their flex weights. Similarly, if the views will overflow the
        parent, space is subtracted in these ratios. A flex of 0 means this view
        is not resized. Flex values must not be negative.
        """
        cdef CefRefPtr[CefView] _a0
        cdef CefBoxLayout* _p = self._ptr_CefBoxLayout()
        _a0 = view._ref
        with nogil:
            _p.SetFlexForView(_a0, flex)
        return None

    def clear_flex_for_view(self, View view not None):
        """Clears the flex for the given |view|, causing it to use the default flex
        specified via CefBoxLayoutSettings.default_flex.
        """
        cdef CefRefPtr[CefView] _a0
        cdef CefBoxLayout* _p = self._ptr_CefBoxLayout()
        _a0 = view._ref
        with nogil:
            _p.ClearFlexForView(_a0)
        return None


cdef object _wrap_BoxLayout(CefRefPtr[CefBoxLayout] ref):
    cdef BoxLayout obj
    if ref.get() == NULL:
        return None
    obj = BoxLayout.__new__(BoxLayout)
    obj._ref = CefRefPtr[CefLayout](<CefLayout*>ref.get())
    return obj


