# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class LoadHandler:
    """Implement this interface to handle events related to browser load status.
    The methods of this class will be called on the browser process UI thread or
    render process main thread (TID_RENDERER).
    """

    def on_loading_state_change(self, browser, is_loading, can_go_back, can_go_forward):
        """Called when the loading state has changed. This callback will be executed
        twice -- once when loading is initiated either programmatically or by user
        action, and once when loading is terminated due to completion,
        cancellation of failure. It will be called before any calls to OnLoadStart
        and after all calls to OnLoadError and/or OnLoadEnd.
        """
        return None

    def on_load_start(self, browser, frame, transition_type):
        """Called after a navigation has been committed and before the browser begins
        loading contents in the frame. The |frame| value will never be empty --
        call the IsMain() method to check if this frame is the main frame.
        |transition_type| provides information about the source of the navigation
        and an accurate value is only available in the browser process. Multiple
        frames may be loading at the same time. Sub-frames may start or continue
        loading after the main frame load has ended. This method will not be
        called for same page navigations (fragments, history state, etc.) or for
        navigations that fail or are canceled before commit. For notification of
        overall browser load status use OnLoadingStateChange instead.
        """
        return None

    def on_load_end(self, browser, frame, http_status_code):
        """Called when the browser is done loading a frame. The |frame| value will
        never be empty -- call the IsMain() method to check if this frame is the
        main frame. Multiple frames may be loading at the same time. Sub-frames
        may start or continue loading after the main frame load has ended. This
        method will not be called for same page navigations (fragments, history
        state, etc.) or for navigations that fail or are canceled before commit.
        For notification of overall browser load status use OnLoadingStateChange
        instead.
        """
        return None

    def on_load_error(self, browser, frame, error_code, error_text, failed_url):
        """Called when a navigation fails or is canceled. This method may be called
        by itself if before commit or in combination with OnLoadStart/OnLoadEnd if
        after commit. |errorCode| is the error code number, |errorText| is the
        error text and |failedUrl| is the URL that failed to load.
        See net\\base\\net_error_list.h for complete descriptions of the error
        codes.
        """
        return None


cdef void _LoadHandler_on_loading_state_change(void* py, CefBrowser* browser, cpp_bool is_loading, cpp_bool can_go_back, cpp_bool can_go_forward) noexcept with gil:
    try:
        _r = (<object>py).on_loading_state_change(_wrap_Browser(CefRefPtr[CefBrowser](browser)), is_loading, can_go_back, can_go_forward)
    except BaseException:
        _g_report()

cdef void _LoadHandler_on_load_start(void* py, CefBrowser* browser, CefFrame* frame, int transition_type) noexcept with gil:
    try:
        _r = (<object>py).on_load_start(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), _g_enum(_types.TransitionType, transition_type))
    except BaseException:
        _g_report()

cdef void _LoadHandler_on_load_end(void* py, CefBrowser* browser, CefFrame* frame, int http_status_code) noexcept with gil:
    try:
        _r = (<object>py).on_load_end(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), http_status_code)
    except BaseException:
        _g_report()

cdef void _LoadHandler_on_load_error(void* py, CefBrowser* browser, CefFrame* frame, int error_code, const CefString* error_text, const CefString* failed_url) noexcept with gil:
    try:
        _r = (<object>py).on_load_error(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), _g_enum(_types.ErrorCode, error_code), _g_str(error_text[0]), _g_str(failed_url[0]))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefLoadHandler] _g_make_LoadHandler(object obj) except *:
    cdef CefRefPtr[CefLoadHandler] ref
    cdef CwLoadHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, LoadHandler):
        raise TypeError("expected a LoadHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_loading_state_change", None) is not LoadHandler.on_loading_state_change:
        cb.fn_on_loading_state_change = _LoadHandler_on_loading_state_change
    if getattr(cls, "on_load_start", None) is not LoadHandler.on_load_start:
        cb.fn_on_load_start = _LoadHandler_on_load_start
    if getattr(cls, "on_load_end", None) is not LoadHandler.on_load_end:
        cb.fn_on_load_end = _LoadHandler_on_load_end
    if getattr(cls, "on_load_error", None) is not LoadHandler.on_load_error:
        cb.fn_on_load_error = _LoadHandler_on_load_error
    ref = CefRefPtr[CefLoadHandler](<CefLoadHandler*>new CwLoadHandlerProxy(cb))
    return ref


cdef inline CefLoadHandler* _g_export_LoadHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefLoadHandler] ref = _g_make_LoadHandler(obj)
    cdef CefLoadHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_LoadHandler(CefRefPtr[CefLoadHandler] ref):
    """The Python object that was given to CEF as this LoadHandler (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfLoadHandler(ref.get())
    if py == NULL:
        return None
    return <object>py


