# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class LabelButton(Button):
    """LabelButton is a button with optional text and/or icon. Methods must be
    called on the browser process UI thread unless otherwise indicated.
    """

    cdef CefLabelButton* _ptr_CefLabelButton(self) except NULL:
        cdef CefLabelButton* p = <CefLabelButton*>self._ref.get()
        if p == NULL:
            raise RuntimeError("LabelButton has no CEF object")
        return p

    def as_menu_button(self):
        """Returns this LabelButton as a MenuButton or NULL if this is not a
        MenuButton.
        """
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        cdef CefRefPtr[CefMenuButton] _r
        with nogil:
            _r = _p.AsMenuButton()
        return _wrap_MenuButton(_r)

    def set_text(self, text):
        """Sets the text shown on the LabelButton. By default |text| will also be
        used as the accessible name.
        """
        cdef CefString _a0
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        _a0 = _g_cef(text)
        with nogil:
            _p.SetText(_a0)
        return None

    def get_text(self):
        """Returns the text shown on the LabelButton."""
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        cdef CefString _r
        with nogil:
            _r = _p.GetText()
        return _g_str(_r)

    def set_image(self, long long button_state, Image image):
        """Sets the image shown for |button_state|. When this Button is drawn if no
        image exists for the current state then the image for
        CEF_BUTTON_STATE_NORMAL, if any, will be shown.
        """
        cdef CefRefPtr[CefImage] _a1
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        if image is not None:
            _a1 = image._ref
        with nogil:
            _p.SetImage(<cef_button_state_t>button_state, _a1)
        return None

    def get_image(self, long long button_state):
        """Returns the image shown for |button_state|. If no image exists for that
        state then the image for CEF_BUTTON_STATE_NORMAL will be returned.
        """
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        cdef CefRefPtr[CefImage] _r
        with nogil:
            _r = _p.GetImage(<cef_button_state_t>button_state)
        return _wrap_Image(_r)

    def set_text_color(self, long long for_state, cef_color_t color):
        """Sets the text color shown for the specified button |for_state| to |color|."""
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        with nogil:
            _p.SetTextColor(<cef_button_state_t>for_state, color)
        return None

    def set_enabled_text_colors(self, cef_color_t color):
        """Sets the text colors shown for the non-disabled states to |color|."""
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        with nogil:
            _p.SetEnabledTextColors(color)
        return None

    def set_font_list(self, font_list):
        """Sets the font list. The format is \"<FONT_FAMILY_LIST>,[STYLES] <SIZE>\",
        where:
        - FONT_FAMILY_LIST is a comma-separated list of font family names,
        - STYLES is an optional space-separated list of style names
          (case-sensitive \"Bold\" and \"Italic\" are supported), and
        - SIZE is an integer font size in pixels with the suffix \"px\".

        Here are examples of valid font description strings:
        - \"Arial, Helvetica, Bold Italic 14px\"
        - \"Arial, 14px\"
        """
        cdef CefString _a0
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        _a0 = _g_cef(font_list)
        with nogil:
            _p.SetFontList(_a0)
        return None

    def set_horizontal_alignment(self, long long alignment):
        """Sets the horizontal alignment; reversed in RTL. Default is
        CEF_HORIZONTAL_ALIGNMENT_CENTER.
        """
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        with nogil:
            _p.SetHorizontalAlignment(<cef_horizontal_alignment_t>alignment)
        return None

    def set_minimum_size(self, size):
        """Reset the minimum size of this LabelButton to |size|."""
        cdef CefSize _a0
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        _g_to_Size(size, &_a0)
        with nogil:
            _p.SetMinimumSize(_a0)
        return None

    def set_maximum_size(self, size):
        """Reset the maximum size of this LabelButton to |size|."""
        cdef CefSize _a0
        cdef CefLabelButton* _p = self._ptr_CefLabelButton()
        _g_to_Size(size, &_a0)
        with nogil:
            _p.SetMaximumSize(_a0)
        return None

    @staticmethod
    def create_label_button(delegate, text):
        """Create a new LabelButton. A |delegate| must be provided to handle the
        button click. |text| will be shown on the LabelButton and used as the
        default accessible name.
        """
        cdef CefRefPtr[CefButtonDelegate] _a0
        cdef CefString _a1
        cdef CefRefPtr[CefLabelButton] _r
        if delegate is None:
            raise TypeError("delegate must not be None")
        _a0 = _g_make_ButtonDelegate(delegate)
        if text is not None:
            _a1 = _g_cef(text)
        with nogil:
            _r = CefLabelButton.CreateLabelButton(_a0, _a1)
        return _wrap_LabelButton(_r)


cdef object _wrap_LabelButton(CefRefPtr[CefLabelButton] ref):
    cdef CefRefPtr[CefMenuButton] _c0
    cdef LabelButton obj
    if ref.get() == NULL:
        return None
    _c0 = ref.get().AsMenuButton()
    if _c0.get() != NULL:
        return _wrap_MenuButton(_c0)
    obj = LabelButton.__new__(LabelButton)
    obj._ref = CefRefPtr[CefView](<CefView*>ref.get())
    return obj


