# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class RenderHandler:
    """Implement this interface to handle events when window rendering is disabled.
    The methods of this class will be called on the UI thread.
    """

    def get_accessibility_handler(self):
        """Return the handler for accessibility notifications. If no handler is
        provided the default implementation will be used.
        """
        return None

    def get_root_screen_rect(self, browser):
        """Called to retrieve the root window rectangle in screen DIP coordinates.
        Return true if the rectangle was provided. If this method returns false
        the rectangle from GetViewRect will be used.
        """
        return False, Rect()

    def get_view_rect(self, browser):
        """Called to retrieve the view rectangle in screen DIP coordinates. This
        method must always provide a non-empty rectangle.
        """
        return Rect()

    def get_screen_point(self, browser, view_x, view_y):
        """Called to retrieve the translation from view DIP coordinates to screen
        coordinates. Windows/Linux should provide screen device (pixel)
        coordinates and MacOS should provide screen DIP coordinates. Return true
        if the requested coordinates were provided.
        """
        return False, 0, 0

    def get_screen_info(self, browser):
        """Called to allow the client to fill in the CefScreenInfo object with
        appropriate values. Return true if the |screen_info| structure has been
        modified.

        If the screen info rectangle is left empty the rectangle from GetViewRect
        will be used. If the rectangle is still empty or invalid popups may not be
        drawn correctly.
        """
        return False, ScreenInfo()

    def on_popup_show(self, browser, show):
        """Called when the browser wants to show or hide the popup widget. The popup
        should be shown if |show| is true and hidden if |show| is false.
        """
        return None

    def on_popup_size(self, browser, rect):
        """Called when the browser wants to move or resize the popup widget. |rect|
        contains the new location and size in view coordinates.
        """
        return None

    def on_paint(self, browser, type, dirty_rects, buffer, width, height):
        """Called when an element should be painted. Pixel values passed to this
        method are scaled relative to view coordinates based on the value of
        CefScreenInfo.device_scale_factor returned from GetScreenInfo. |type|
        indicates whether the element is the view or the popup widget. |buffer|
        contains the pixel data for the whole image. |dirtyRects| contains the set
        of rectangles in pixel coordinates that need to be repainted. |buffer|
        will be |width|*|height|*4 bytes in size and represents a BGRA image with
        an upper-left origin. This method is only called when
        CefWindowInfo::shared_texture_enabled is set to false.
        """
        return None

    def on_accelerated_paint(self, browser, type, dirty_rects, info):
        """Called when an element has been rendered to the shared texture handle.
        |type| indicates whether the element is the view or the popup widget.
        |dirtyRects| contains the set of rectangles in pixel coordinates that need
        to be repainted. |info| contains the shared handle; on Windows it is a
        HANDLE to a texture that can be opened with D3D11 OpenSharedResource1 or
        D3D12 OpenSharedHandle, on macOS it is an IOSurface pointer that can be
        opened with Metal or OpenGL, and on Linux it contains several planes, each
        with an fd to the underlying system native buffer.

        The underlying implementation uses a pool to deliver frames. As a result,
        the handle may differ every frame depending on how many frames are
        in-progress. The handle's resource cannot be cached and cannot be accessed
        outside of this callback. It should be reopened each time this callback is
        executed and the contents should be copied to a texture owned by the
        client application. The contents of |info| will be released back to the
        pool after this callback returns.
        """
        return None

    def get_touch_handle_size(self, browser, orientation):
        """Called to retrieve the size of the touch handle for the specified
        |orientation|.
        """
        return Size()

    def on_touch_handle_state_changed(self, browser, state):
        """Called when touch handle state is updated. The client is responsible for
        rendering the touch handles.
        """
        return None

    def start_dragging(self, browser, drag_data, allowed_ops, x, y):
        """Called when the user starts dragging content in the web view. Contextual
        information about the dragged content is supplied by |drag_data|.
        (|x|, |y|) is the drag start location in screen coordinates.
        OS APIs that run a system message loop may be used within the
        StartDragging call.

        Return false to abort the drag operation. Don't call any of
        CefBrowserHost::DragSource*Ended* methods after returning false.

        Return true to handle the drag operation. Call
        CefBrowserHost::DragSourceEndedAt and DragSourceSystemDragEnded either
        synchronously or asynchronously to inform the web view that the drag
        operation has ended.
        """
        return False

    def update_drag_cursor(self, browser, operation):
        """Called when the web view wants to update the mouse cursor during a
        drag & drop operation. |operation| describes the allowed operation
        (none, move, copy, link).
        """
        return None

    def on_scroll_offset_changed(self, browser, x, y):
        """Called when the scroll offset has changed."""
        return None

    def on_ime_composition_range_changed(self, browser, selected_range, character_bounds):
        """Called when the IME composition range has changed. |selected_range| is the
        range of characters that have been selected. |character_bounds| is the
        bounds of each character in view coordinates.
        """
        return None

    def on_text_selection_changed(self, browser, selected_text, selected_range):
        """Called when text selection has changed for the specified |browser|.
        |selected_text| is the currently selected text and |selected_range| is
        the character range.
        """
        return None

    def on_virtual_keyboard_requested(self, browser, input_mode):
        """Called when an on-screen keyboard should be shown or hidden for the
        specified |browser|. |input_mode| specifies what kind of keyboard
        should be opened. If |input_mode| is CEF_TEXT_INPUT_MODE_NONE, any
        existing keyboard for this browser should be hidden.
        """
        return None


cdef CefAccessibilityHandler* _RenderHandler_get_accessibility_handler(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_accessibility_handler()
        _r0 = _r
        return _g_export_AccessibilityHandler(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef cpp_bool _RenderHandler_get_root_screen_rect(void* py, CefBrowser* browser, CefRect* rect) noexcept with gil:
    try:
        _r = (<object>py).get_root_screen_rect(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
        _r0, _r1 = _r
        _g_to_Rect(_r1, rect)
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _RenderHandler_get_view_rect(void* py, CefBrowser* browser, CefRect* rect) noexcept with gil:
    try:
        _r = (<object>py).get_view_rect(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
        _r0 = _r
        _g_to_Rect(_r0, rect)
    except BaseException:
        _g_report()

cdef cpp_bool _RenderHandler_get_screen_point(void* py, CefBrowser* browser, int view_x, int view_y, int* screen_x, int* screen_y) noexcept with gil:
    try:
        _r = (<object>py).get_screen_point(_wrap_Browser(CefRefPtr[CefBrowser](browser)), view_x, view_y)
        _r0, _r1, _r2 = _r
        screen_x[0] = _r1
        screen_y[0] = _r2
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _RenderHandler_get_screen_info(void* py, CefBrowser* browser, CefScreenInfo* screen_info) noexcept with gil:
    try:
        _r = (<object>py).get_screen_info(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
        _r0, _r1 = _r
        _g_to_ScreenInfo(_r1, screen_info)
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _RenderHandler_on_popup_show(void* py, CefBrowser* browser, cpp_bool show) noexcept with gil:
    try:
        _r = (<object>py).on_popup_show(_wrap_Browser(CefRefPtr[CefBrowser](browser)), show)
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_popup_size(void* py, CefBrowser* browser, const CefRect* rect) noexcept with gil:
    try:
        _r = (<object>py).on_popup_size(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_from_Rect(rect))
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_paint(void* py, CefBrowser* browser, int type, const vector[CefRect]* dirty_rects, void* buffer, size_t buffer_size, int width, int height) noexcept with gil:
    try:
        _view_buffer = PyMemoryView_FromMemory(<char*>buffer, buffer_size, PyBUF_READ)
        try:
            _r = (<object>py).on_paint(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.PaintElementType, type), _g_list_Rect(dirty_rects), _view_buffer, width, height)
        finally:
            try:
                _view_buffer.release()
            except BaseException:
                pass
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_accelerated_paint(void* py, CefBrowser* browser, int type, const vector[CefRect]* dirty_rects, const CefAcceleratedPaintInfo* info) noexcept with gil:
    try:
        _r = (<object>py).on_accelerated_paint(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.PaintElementType, type), _g_list_Rect(dirty_rects), _g_from_AcceleratedPaintInfo(info))
    except BaseException:
        _g_report()

cdef void _RenderHandler_get_touch_handle_size(void* py, CefBrowser* browser, int orientation, CefSize* size) noexcept with gil:
    try:
        _r = (<object>py).get_touch_handle_size(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.HorizontalAlignment, orientation))
        _r0 = _r
        _g_to_Size(_r0, size)
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_touch_handle_state_changed(void* py, CefBrowser* browser, const CefTouchHandleState* state) noexcept with gil:
    try:
        _r = (<object>py).on_touch_handle_state_changed(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_from_TouchHandleState(state))
    except BaseException:
        _g_report()

cdef cpp_bool _RenderHandler_start_dragging(void* py, CefBrowser* browser, CefDragData* drag_data, int allowed_ops, int x, int y) noexcept with gil:
    try:
        _r = (<object>py).start_dragging(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_DragData(CefRefPtr[CefDragData](drag_data)), _g_enum(_types.DragOperationsMask, allowed_ops), x, y)
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _RenderHandler_update_drag_cursor(void* py, CefBrowser* browser, int operation) noexcept with gil:
    try:
        _r = (<object>py).update_drag_cursor(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.DragOperationsMask, operation))
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_scroll_offset_changed(void* py, CefBrowser* browser, double x, double y) noexcept with gil:
    try:
        _r = (<object>py).on_scroll_offset_changed(_wrap_Browser(CefRefPtr[CefBrowser](browser)), x, y)
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_ime_composition_range_changed(void* py, CefBrowser* browser, const CefRange* selected_range, const vector[CefRect]* character_bounds) noexcept with gil:
    try:
        _r = (<object>py).on_ime_composition_range_changed(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_from_Range(selected_range), _g_list_Rect(character_bounds))
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_text_selection_changed(void* py, CefBrowser* browser, const CefString* selected_text, const CefRange* selected_range) noexcept with gil:
    try:
        _r = (<object>py).on_text_selection_changed(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_str(selected_text[0]), _g_from_Range(selected_range))
    except BaseException:
        _g_report()

cdef void _RenderHandler_on_virtual_keyboard_requested(void* py, CefBrowser* browser, int input_mode) noexcept with gil:
    try:
        _r = (<object>py).on_virtual_keyboard_requested(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.TextInputMode, input_mode))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefRenderHandler] _g_make_RenderHandler(object obj) except *:
    cdef CefRefPtr[CefRenderHandler] ref
    cdef CwRenderHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, RenderHandler):
        raise TypeError("expected a RenderHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "get_accessibility_handler", None) is not RenderHandler.get_accessibility_handler:
        cb.fn_get_accessibility_handler = _RenderHandler_get_accessibility_handler
    if getattr(cls, "get_root_screen_rect", None) is not RenderHandler.get_root_screen_rect:
        cb.fn_get_root_screen_rect = _RenderHandler_get_root_screen_rect
    if getattr(cls, "get_view_rect", None) is not RenderHandler.get_view_rect:
        cb.fn_get_view_rect = _RenderHandler_get_view_rect
    if getattr(cls, "get_screen_point", None) is not RenderHandler.get_screen_point:
        cb.fn_get_screen_point = _RenderHandler_get_screen_point
    if getattr(cls, "get_screen_info", None) is not RenderHandler.get_screen_info:
        cb.fn_get_screen_info = _RenderHandler_get_screen_info
    if getattr(cls, "on_popup_show", None) is not RenderHandler.on_popup_show:
        cb.fn_on_popup_show = _RenderHandler_on_popup_show
    if getattr(cls, "on_popup_size", None) is not RenderHandler.on_popup_size:
        cb.fn_on_popup_size = _RenderHandler_on_popup_size
    if getattr(cls, "on_paint", None) is not RenderHandler.on_paint:
        cb.fn_on_paint = _RenderHandler_on_paint
    if getattr(cls, "on_accelerated_paint", None) is not RenderHandler.on_accelerated_paint:
        cb.fn_on_accelerated_paint = _RenderHandler_on_accelerated_paint
    if getattr(cls, "get_touch_handle_size", None) is not RenderHandler.get_touch_handle_size:
        cb.fn_get_touch_handle_size = _RenderHandler_get_touch_handle_size
    if getattr(cls, "on_touch_handle_state_changed", None) is not RenderHandler.on_touch_handle_state_changed:
        cb.fn_on_touch_handle_state_changed = _RenderHandler_on_touch_handle_state_changed
    if getattr(cls, "start_dragging", None) is not RenderHandler.start_dragging:
        cb.fn_start_dragging = _RenderHandler_start_dragging
    if getattr(cls, "update_drag_cursor", None) is not RenderHandler.update_drag_cursor:
        cb.fn_update_drag_cursor = _RenderHandler_update_drag_cursor
    if getattr(cls, "on_scroll_offset_changed", None) is not RenderHandler.on_scroll_offset_changed:
        cb.fn_on_scroll_offset_changed = _RenderHandler_on_scroll_offset_changed
    if getattr(cls, "on_ime_composition_range_changed", None) is not RenderHandler.on_ime_composition_range_changed:
        cb.fn_on_ime_composition_range_changed = _RenderHandler_on_ime_composition_range_changed
    if getattr(cls, "on_text_selection_changed", None) is not RenderHandler.on_text_selection_changed:
        cb.fn_on_text_selection_changed = _RenderHandler_on_text_selection_changed
    if getattr(cls, "on_virtual_keyboard_requested", None) is not RenderHandler.on_virtual_keyboard_requested:
        cb.fn_on_virtual_keyboard_requested = _RenderHandler_on_virtual_keyboard_requested
    ref = CefRefPtr[CefRenderHandler](<CefRenderHandler*>new CwRenderHandlerProxy(cb))
    return ref


cdef inline CefRenderHandler* _g_export_RenderHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefRenderHandler] ref = _g_make_RenderHandler(obj)
    cdef CefRenderHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_RenderHandler(CefRefPtr[CefRenderHandler] ref):
    """The Python object that was given to CEF as this RenderHandler (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfRenderHandler(ref.get())
    if py == NULL:
        return None
    return <object>py


