# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class Image:
    """Container for a single image represented at different scale factors. All
    image representations should be the same size in density independent pixel
    (DIP) units. For example, if the image at scale factor 1.0 is 100x100 pixels
    then the image at scale factor 2.0 should be 200x200 pixels -- both images
    will display with a DIP size of 100x100 units. The methods of this class can
    be called on any browser process thread.
    """
    cdef CefRefPtr[CefImage] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("Image objects are created by CEF or by a create() function")

    cdef CefImage* _ptr(self) except NULL:
        cdef CefImage* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("Image has no CEF object")
        return p

    def is_empty(self):
        """Returns true if this Image is empty."""
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsEmpty()
        return _r

    def is_same(self, Image that not None):
        """Returns true if this Image and |that| Image share the same underlying
        storage. Will also return true if both images are empty.
        """
        cdef CefRefPtr[CefImage] _a0
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        _a0 = that._ref
        with nogil:
            _r = _p.IsSame(_a0)
        return _r

    def add_bitmap(self, float scale_factor, int pixel_width, int pixel_height, long long color_type, long long alpha_type, pixel_data):
        """Add a bitmap image representation for |scale_factor|. Only 32-bit
        RGBA/BGRA formats are supported. |pixel_width| and |pixel_height| are the
        bitmap representation size in pixel coordinates. |pixel_data| is the array
        of pixel data and should be |pixel_width| x |pixel_height| x 4 bytes in
        size. |color_type| and |alpha_type| values specify the pixel format.
        """
        cdef const unsigned char[::1] _v5
        cdef const void* _a5 = NULL
        cdef size_t _n5 = 0
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        if pixel_data is None:
            raise TypeError("pixel_data must be bytes-like, not None")
        _v5 = pixel_data
        _n5 = _v5.shape[0]
        if _n5:
            _a5 = &_v5[0]
        with nogil:
            _r = _p.AddBitmap(scale_factor, pixel_width, pixel_height, <cef_color_type_t>color_type, <cef_alpha_type_t>alpha_type, _a5, _n5)
        return _r

    def add_png(self, float scale_factor, png_data):
        """Add a PNG image representation for |scale_factor|. |png_data| is the image
        data of size |png_data_size|. Any alpha transparency in the PNG data will
        be maintained.
        """
        cdef const unsigned char[::1] _v1
        cdef const void* _a1 = NULL
        cdef size_t _n1 = 0
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        if png_data is None:
            raise TypeError("png_data must be bytes-like, not None")
        _v1 = png_data
        _n1 = _v1.shape[0]
        if _n1:
            _a1 = &_v1[0]
        with nogil:
            _r = _p.AddPNG(scale_factor, _a1, _n1)
        return _r

    def add_jpeg(self, float scale_factor, jpeg_data):
        """Create a JPEG image representation for |scale_factor|. |jpeg_data| is the
        image data of size |jpeg_data_size|. The JPEG format does not support
        transparency so the alpha byte will be set to 0xFF for all pixels.
        """
        cdef const unsigned char[::1] _v1
        cdef const void* _a1 = NULL
        cdef size_t _n1 = 0
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        if jpeg_data is None:
            raise TypeError("jpeg_data must be bytes-like, not None")
        _v1 = jpeg_data
        _n1 = _v1.shape[0]
        if _n1:
            _a1 = &_v1[0]
        with nogil:
            _r = _p.AddJPEG(scale_factor, _a1, _n1)
        return _r

    def get_width(self):
        """Returns the image width in density independent pixel (DIP) units."""
        cdef CefImage* _p = self._ptr()
        cdef size_t _r
        with nogil:
            _r = _p.GetWidth()
        return _r

    def get_height(self):
        """Returns the image height in density independent pixel (DIP) units."""
        cdef CefImage* _p = self._ptr()
        cdef size_t _r
        with nogil:
            _r = _p.GetHeight()
        return _r

    def has_representation(self, float scale_factor):
        """Returns true if this image contains a representation for |scale_factor|."""
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasRepresentation(scale_factor)
        return _r

    def remove_representation(self, float scale_factor):
        """Removes the representation for |scale_factor|. Returns true on success."""
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.RemoveRepresentation(scale_factor)
        return _r

    def get_representation_info(self, float scale_factor):
        """Returns information for the representation that most closely matches
        |scale_factor|. |actual_scale_factor| is the actual scale factor for the
        representation. |pixel_width| and |pixel_height| are the representation
        size in pixel coordinates. Returns true on success.
        """
        cdef float _a1
        cdef int _a2
        cdef int _a3
        cdef CefImage* _p = self._ptr()
        cdef cpp_bool _r
        _a1 = 0
        _a2 = 0
        _a3 = 0
        with nogil:
            _r = _p.GetRepresentationInfo(scale_factor, _a1, _a2, _a3)
        return (_r, _a1, _a2, _a3)

    def get_as_bitmap(self, float scale_factor, long long color_type, long long alpha_type):
        """Returns the bitmap representation that most closely matches
        |scale_factor|. Only 32-bit RGBA/BGRA formats are supported. |color_type|
        and |alpha_type| values specify the desired output pixel format.
        |pixel_width| and |pixel_height| are the output representation size in
        pixel coordinates. Returns a CefBinaryValue containing the pixel data on
        success or NULL on failure.
        """
        cdef int _a3
        cdef int _a4
        cdef CefImage* _p = self._ptr()
        cdef CefRefPtr[CefBinaryValue] _r
        _a3 = 0
        _a4 = 0
        with nogil:
            _r = _p.GetAsBitmap(scale_factor, <cef_color_type_t>color_type, <cef_alpha_type_t>alpha_type, _a3, _a4)
        return (_wrap_BinaryValue(_r), _a3, _a4)

    def get_as_png(self, float scale_factor, bint with_transparency):
        """Returns the PNG representation that most closely matches |scale_factor|.
        If |with_transparency| is true any alpha transparency in the image will be
        represented in the resulting PNG data. |pixel_width| and |pixel_height|
        are the output representation size in pixel coordinates. Returns a
        CefBinaryValue containing the PNG image data on success or NULL on
        failure.
        """
        cdef int _a2
        cdef int _a3
        cdef CefImage* _p = self._ptr()
        cdef CefRefPtr[CefBinaryValue] _r
        _a2 = 0
        _a3 = 0
        with nogil:
            _r = _p.GetAsPNG(scale_factor, with_transparency, _a2, _a3)
        return (_wrap_BinaryValue(_r), _a2, _a3)

    def get_as_jpeg(self, float scale_factor, int quality):
        """Returns the JPEG representation that most closely matches |scale_factor|.
        |quality| determines the compression level with 0 == lowest and 100 ==
        highest. The JPEG format does not support alpha transparency and the alpha
        channel, if any, will be discarded. |pixel_width| and |pixel_height| are
        the output representation size in pixel coordinates. Returns a
        CefBinaryValue containing the JPEG image data on success or NULL on
        failure.
        """
        cdef int _a2
        cdef int _a3
        cdef CefImage* _p = self._ptr()
        cdef CefRefPtr[CefBinaryValue] _r
        _a2 = 0
        _a3 = 0
        with nogil:
            _r = _p.GetAsJPEG(scale_factor, quality, _a2, _a3)
        return (_wrap_BinaryValue(_r), _a2, _a3)

    @staticmethod
    def create_image():
        """Create a new CefImage. It will initially be empty. Use the Add*() methods
        to add representations at different scale factors.
        """
        if not _cef_started:
            raise RuntimeError("an Image can only be made after CefApp.initialize()")
        cdef CefRefPtr[CefImage] _r
        with nogil:
            _r = CefImage.CreateImage()
        return _wrap_Image(_r)


cdef object _wrap_Image(CefRefPtr[CefImage] ref):
    cdef Image obj
    if ref.get() == NULL:
        return None
    obj = Image.__new__(Image)
    obj._ref = ref
    return obj


cdef inline CefImage* _g_ref_Image(object obj) except? NULL:
    """A reference for CEF to keep (a Image that a handler method returns; None: nothing)."""
    cdef Image typed
    cdef CefRefPtr[CefImage] ref
    cdef CefImage* raw
    if obj is None:
        return NULL
    if not isinstance(obj, Image):
        raise TypeError("expected a Image or None, not %s" % type(obj).__name__)
    typed = <Image>obj
    ref = typed._ref
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


