# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class ScrollView(View):
    """A ScrollView will show horizontal and/or vertical scrollbars when necessary
    based on the size of the attached content view. Methods must be called on
    the browser process UI thread unless otherwise indicated.
    """

    cdef CefScrollView* _ptr_CefScrollView(self) except NULL:
        cdef CefScrollView* p = <CefScrollView*>self._ref.get()
        if p == NULL:
            raise RuntimeError("ScrollView has no CEF object")
        return p

    def set_content_view(self, View view not None):
        """Set the content View. The content View must have a specified size (e.g.
        via CefView::SetBounds or CefViewDelegate::GetPreferredSize).
        """
        cdef CefRefPtr[CefView] _a0
        cdef CefScrollView* _p = self._ptr_CefScrollView()
        _a0 = view._ref
        with nogil:
            _p.SetContentView(_a0)
        return None

    def get_content_view(self):
        """Returns the content View."""
        cdef CefScrollView* _p = self._ptr_CefScrollView()
        cdef CefRefPtr[CefView] _r
        with nogil:
            _r = _p.GetContentView()
        return _wrap_View(_r)

    def get_visible_content_rect(self):
        """Returns the visible region of the content View."""
        cdef CefScrollView* _p = self._ptr_CefScrollView()
        cdef CefRect _r
        with nogil:
            _r = _p.GetVisibleContentRect()
        return _g_from_Rect(&_r)

    def has_horizontal_scrollbar(self):
        """Returns true if the horizontal scrollbar is currently showing."""
        cdef CefScrollView* _p = self._ptr_CefScrollView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasHorizontalScrollbar()
        return _r

    def get_horizontal_scrollbar_height(self):
        """Returns the height of the horizontal scrollbar."""
        cdef CefScrollView* _p = self._ptr_CefScrollView()
        cdef int _r
        with nogil:
            _r = _p.GetHorizontalScrollbarHeight()
        return _r

    def has_vertical_scrollbar(self):
        """Returns true if the vertical scrollbar is currently showing."""
        cdef CefScrollView* _p = self._ptr_CefScrollView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasVerticalScrollbar()
        return _r

    def get_vertical_scrollbar_width(self):
        """Returns the width of the vertical scrollbar."""
        cdef CefScrollView* _p = self._ptr_CefScrollView()
        cdef int _r
        with nogil:
            _r = _p.GetVerticalScrollbarWidth()
        return _r

    @staticmethod
    def create_scroll_view(delegate):
        """Create a new ScrollView."""
        cdef CefRefPtr[CefViewDelegate] _a0
        cdef CefRefPtr[CefScrollView] _r
        _a0 = _g_make_ViewDelegate(delegate)
        with nogil:
            _r = CefScrollView.CreateScrollView(_a0)
        return _wrap_ScrollView(_r)


cdef object _wrap_ScrollView(CefRefPtr[CefScrollView] ref):
    cdef ScrollView obj
    if ref.get() == NULL:
        return None
    obj = ScrollView.__new__(ScrollView)
    obj._ref = CefRefPtr[CefView](<CefView*>ref.get())
    return obj


cdef inline CefScrollView* _g_ref_ScrollView(object obj) except? NULL:
    """A reference for CEF to keep (a ScrollView that a handler method returns; None: nothing)."""
    cdef ScrollView typed
    cdef CefRefPtr[CefScrollView] ref
    cdef CefScrollView* raw
    if obj is None:
        return NULL
    if not isinstance(obj, ScrollView):
        raise TypeError("expected a ScrollView or None, not %s" % type(obj).__name__)
    typed = <ScrollView>obj
    ref = CefRefPtr[CefScrollView](<CefScrollView*>typed._ref.get())
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


