# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class PreferenceObserver:
    """Implemented by the client to observe preference changes and registered via
    CefPreferenceManager::AddPreferenceObserver. The methods of this class will
    be called on the browser process UI thread.
    """

    def on_preference_changed(self, name):
        """Called when a preference has changed. The new value can be retrieved using
        CefPreferenceManager::GetPreference.
        """
        return None


cdef void _PreferenceObserver_on_preference_changed(void* py, const CefString* name) noexcept with gil:
    try:
        _r = (<object>py).on_preference_changed(_g_str(name[0]))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefPreferenceObserver] _g_make_PreferenceObserver(object obj) except *:
    cdef CefRefPtr[CefPreferenceObserver] ref
    cdef CwPreferenceObserverCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, PreferenceObserver):
        raise TypeError("expected a PreferenceObserver or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_preference_changed", None) is not PreferenceObserver.on_preference_changed:
        cb.fn_on_preference_changed = _PreferenceObserver_on_preference_changed
    ref = CefRefPtr[CefPreferenceObserver](<CefPreferenceObserver*>new CwPreferenceObserverProxy(cb))
    return ref


cdef inline CefPreferenceObserver* _g_export_PreferenceObserver(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefPreferenceObserver] ref = _g_make_PreferenceObserver(obj)
    cdef CefPreferenceObserver* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_PreferenceObserver(CefRefPtr[CefPreferenceObserver] ref):
    """The Python object that was given to CEF as this PreferenceObserver (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfPreferenceObserver(ref.get())
    if py == NULL:
        return None
    return <object>py


