# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class View:
    """A View is a rectangle within the views View hierarchy. It is the base class
    for all Views. All size and position values are in density independent
    pixels (DIP) unless otherwise indicated. Methods must be called on the
    browser process UI thread unless otherwise indicated.
    """
    cdef CefRefPtr[CefView] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("View objects are created by CEF or by a create() function")

    cdef CefView* _ptr_CefView(self) except NULL:
        cdef CefView* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("View has no CEF object")
        return p

    def as_browser_view(self):
        """Returns this View as a BrowserView or NULL if this is not a BrowserView."""
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefBrowserView] _r
        with nogil:
            _r = _p.AsBrowserView()
        return _wrap_BrowserView(_r)

    def as_button(self):
        """Returns this View as a Button or NULL if this is not a Button."""
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefButton] _r
        with nogil:
            _r = _p.AsButton()
        return _wrap_Button(_r)

    def as_panel(self):
        """Returns this View as a Panel or NULL if this is not a Panel."""
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefPanel] _r
        with nogil:
            _r = _p.AsPanel()
        return _wrap_Panel(_r)

    def as_scroll_view(self):
        """Returns this View as a ScrollView or NULL if this is not a ScrollView."""
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefScrollView] _r
        with nogil:
            _r = _p.AsScrollView()
        return _wrap_ScrollView(_r)

    def as_textfield(self):
        """Returns this View as a Textfield or NULL if this is not a Textfield."""
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefTextfield] _r
        with nogil:
            _r = _p.AsTextfield()
        return _wrap_Textfield(_r)

    def get_type_string(self):
        """Returns the type of this View as a string. Used primarily for testing
        purposes.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefString _r
        with nogil:
            _r = _p.GetTypeString()
        return _g_str(_r)

    def to_string(self, bint include_children):
        """Returns a string representation of this View which includes the type and
        various type-specific identifying attributes. If |include_children| is
        true any child Views will also be included. Used primarily for testing
        purposes.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefString _r
        with nogil:
            _r = _p.ToString(include_children)
        return _g_str(_r)

    def is_valid(self):
        """Returns true if this View is valid."""
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsValid()
        return _r

    def is_attached(self):
        """Returns true if this View is currently attached to another View. A View
        can only be attached to one View at a time.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsAttached()
        return _r

    def is_same(self, View that not None):
        """Returns true if this View is the same as |that| View."""
        cdef CefRefPtr[CefView] _a0
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        _a0 = that._ref
        with nogil:
            _r = _p.IsSame(_a0)
        return _r

    def get_window(self):
        """Returns the top-level Window hosting this View, if any."""
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefWindow] _r
        with nogil:
            _r = _p.GetWindow()
        return _wrap_Window(_r)

    def get_id(self):
        """Returns the ID for this View."""
        cdef CefView* _p = self._ptr_CefView()
        cdef int _r
        with nogil:
            _r = _p.GetID()
        return _r

    def set_id(self, int id):
        """Sets the ID for this View. ID should be unique within the subtree that you
        intend to search for it. 0 is the default ID for views.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.SetID(id)
        return None

    def get_group_id(self):
        """Returns the group id of this View, or -1 if not set."""
        cdef CefView* _p = self._ptr_CefView()
        cdef int _r
        with nogil:
            _r = _p.GetGroupID()
        return _r

    def set_group_id(self, int group_id):
        """A group id is used to tag Views which are part of the same logical group.
        Focus can be moved between views with the same group using the arrow keys.
        The group id is immutable once it's set.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.SetGroupID(group_id)
        return None

    def get_parent_view(self):
        """Returns the View that contains this View, if any."""
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefView] _r
        with nogil:
            _r = _p.GetParentView()
        return _wrap_View(_r)

    def get_view_for_id(self, int id):
        """Recursively descends the view tree starting at this View, and returns the
        first child that it encounters with the given ID. Returns NULL if no
        matching child view is found.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRefPtr[CefView] _r
        with nogil:
            _r = _p.GetViewForID(id)
        return _wrap_View(_r)

    def set_bounds(self, bounds):
        """Sets the bounds (size and position) of this View. |bounds| is in parent
        coordinates, or DIP screen coordinates if there is no parent.
        """
        cdef CefRect _a0
        cdef CefView* _p = self._ptr_CefView()
        _g_to_Rect(bounds, &_a0)
        with nogil:
            _p.SetBounds(_a0)
        return None

    def get_bounds(self):
        """Returns the bounds (size and position) of this View in parent coordinates,
        or DIP screen coordinates if there is no parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRect _r
        with nogil:
            _r = _p.GetBounds()
        return _g_from_Rect(&_r)

    def get_bounds_in_screen(self):
        """Returns the bounds (size and position) of this View in DIP screen
        coordinates.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefRect _r
        with nogil:
            _r = _p.GetBoundsInScreen()
        return _g_from_Rect(&_r)

    def set_size(self, size):
        """Sets the size of this View without changing the position. |size| in
        parent coordinates, or DIP screen coordinates if there is no parent.
        """
        cdef CefSize _a0
        cdef CefView* _p = self._ptr_CefView()
        _g_to_Size(size, &_a0)
        with nogil:
            _p.SetSize(_a0)
        return None

    def get_size(self):
        """Returns the size of this View in parent coordinates, or DIP screen
        coordinates if there is no parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefSize _r
        with nogil:
            _r = _p.GetSize()
        return _g_from_Size(&_r)

    def set_position(self, position):
        """Sets the position of this View without changing the size. |position| is in
        parent coordinates, or DIP screen coordinates if there is no parent.
        """
        cdef CefPoint _a0
        cdef CefView* _p = self._ptr_CefView()
        _g_to_Point(position, &_a0)
        with nogil:
            _p.SetPosition(_a0)
        return None

    def get_position(self):
        """Returns the position of this View. Position is in parent coordinates, or
        DIP screen coordinates if there is no parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefPoint _r
        with nogil:
            _r = _p.GetPosition()
        return _g_from_Point(&_r)

    def set_insets(self, insets):
        """Sets the insets for this View. |insets| is in parent coordinates, or DIP
        screen coordinates if there is no parent.
        """
        cdef CefInsets _a0
        cdef CefView* _p = self._ptr_CefView()
        _g_to_Insets(insets, &_a0)
        with nogil:
            _p.SetInsets(_a0)
        return None

    def get_insets(self):
        """Returns the insets for this View in parent coordinates, or DIP screen
        coordinates if there is no parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefInsets _r
        with nogil:
            _r = _p.GetInsets()
        return _g_from_Insets(&_r)

    def get_preferred_size(self):
        """Returns the size this View would like to be if enough space is available.
        Size is in parent coordinates, or DIP screen coordinates if there is no
        parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefSize _r
        with nogil:
            _r = _p.GetPreferredSize()
        return _g_from_Size(&_r)

    def size_to_preferred_size(self):
        """Size this View to its preferred size. Size is in parent coordinates, or
        DIP screen coordinates if there is no parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.SizeToPreferredSize()
        return None

    def get_minimum_size(self):
        """Returns the minimum size for this View. Size is in parent coordinates, or
        DIP screen coordinates if there is no parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefSize _r
        with nogil:
            _r = _p.GetMinimumSize()
        return _g_from_Size(&_r)

    def get_maximum_size(self):
        """Returns the maximum size for this View. Size is in parent coordinates, or
        DIP screen coordinates if there is no parent.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef CefSize _r
        with nogil:
            _r = _p.GetMaximumSize()
        return _g_from_Size(&_r)

    def get_height_for_width(self, int width):
        """Returns the height necessary to display this View with the provided width."""
        cdef CefView* _p = self._ptr_CefView()
        cdef int _r
        with nogil:
            _r = _p.GetHeightForWidth(width)
        return _r

    def invalidate_layout(self):
        """Indicate that this View and all parent Views require a re-layout. This
        ensures the next call to Layout() will propagate to this View even if the
        bounds of parent Views do not change.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.InvalidateLayout()
        return None

    def set_visible(self, bint visible):
        """Sets whether this View is visible. Windows are hidden by default and other
        views are visible by default. This View and any parent views must be set
        as visible for this View to be drawn in a Window. If this View is set as
        hidden then it and any child views will not be drawn and, if any of those
        views currently have focus, then focus will also be cleared. Painting is
        scheduled as needed. If this View is a Window then calling this method is
        equivalent to calling the Window Show() and Hide() methods.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.SetVisible(visible)
        return None

    def is_visible(self):
        """Returns whether this View is visible. A view may be visible but still not
        drawn in a Window if any parent views are hidden. If this View is a Window
        then a return value of true indicates that this Window is currently
        visible to the user on-screen. If this View is not a Window then call
        IsDrawn() to determine whether this View and all parent views are visible
        and will be drawn.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsVisible()
        return _r

    def is_drawn(self):
        """Returns whether this View is visible and drawn in a Window. A view is
        drawn if it and all parent views are visible. If this View is a Window
        then calling this method is equivalent to calling IsVisible(). Otherwise,
        to determine if the containing Window is visible to the user on-screen
        call IsVisible() on the Window.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsDrawn()
        return _r

    def set_enabled(self, bint enabled):
        """Set whether this View is enabled. A disabled View does not receive
        keyboard or mouse inputs. If |enabled| differs from the current value the
        View will be repainted. Also, clears focus if the focused View is
        disabled.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.SetEnabled(enabled)
        return None

    def is_enabled(self):
        """Returns whether this View is enabled."""
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsEnabled()
        return _r

    def set_focusable(self, bint focusable):
        """Sets whether this View is capable of taking focus. It will clear focus if
        the focused View is set to be non-focusable. This is false by default so
        that a View used as a container does not get the focus.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.SetFocusable(focusable)
        return None

    def is_focusable(self):
        """Returns true if this View is focusable, enabled and drawn."""
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsFocusable()
        return _r

    def is_accessibility_focusable(self):
        """Return whether this View is focusable when the user requires full keyboard
        access, even though it may not be normally focusable.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsAccessibilityFocusable()
        return _r

    def has_focus(self):
        """Returns true if this View has focus in the context of the containing
        Window. Check both this method and CefWindow::IsActive to determine global
        keyboard focus.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasFocus()
        return _r

    def request_focus(self):
        """Request focus for this View in the context of the containing Window. If
        this View is focusable it will become the focused View. Any focus changes
        while a Window is not active may be applied after that Window next becomes
        active.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.RequestFocus()
        return None

    def set_background_color(self, cef_color_t color):
        """Sets the background color for this View. The background color will be
        automatically reset when CefViewDelegate::OnThemeChanged is called.
        """
        cdef CefView* _p = self._ptr_CefView()
        with nogil:
            _p.SetBackgroundColor(color)
        return None

    def get_background_color(self):
        """Returns the background color for this View. If the background color is
        unset then the current `GetThemeColor(CEF_ColorPrimaryBackground)` value
        will be returned. If this View belongs to an overlay (created with
        CefWindow::AddOverlayView), and the background color is unset, then a
        value of transparent (0) will be returned.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef cef_color_t _r
        with nogil:
            _r = _p.GetBackgroundColor()
        return _r

    def get_theme_color(self, int color_id):
        """Returns the current theme color associated with |color_id|, or the
        placeholder color (red) if unset. See cef_color_ids.h for standard ID
        values. Standard colors can be overridden and custom colors can be added
        using CefWindow::SetThemeColor.
        """
        cdef CefView* _p = self._ptr_CefView()
        cdef cef_color_t _r
        with nogil:
            _r = _p.GetThemeColor(color_id)
        return _r

    def convert_point_to_screen(self, point):
        """Convert |point| from this View's coordinate system to DIP screen
        coordinates. This View must belong to a Window when calling this method.
        Returns true if the conversion is successful or false otherwise. Use
        CefDisplay::ConvertPointToPixels() after calling this method if further
        conversion to display-specific pixel coordinates is desired.
        """
        cdef CefPoint _a0
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        _g_to_Point(point, &_a0)
        with nogil:
            _r = _p.ConvertPointToScreen(_a0)
        return (_r, _g_from_Point(&_a0))

    def convert_point_from_screen(self, point):
        """Convert |point| to this View's coordinate system from DIP screen
        coordinates. This View must belong to a Window when calling this method.
        Returns true if the conversion is successful or false otherwise. Use
        CefDisplay::ConvertPointFromPixels() before calling this method if
        conversion from display-specific pixel coordinates is necessary.
        """
        cdef CefPoint _a0
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        _g_to_Point(point, &_a0)
        with nogil:
            _r = _p.ConvertPointFromScreen(_a0)
        return (_r, _g_from_Point(&_a0))

    def convert_point_to_window(self, point):
        """Convert |point| from this View's coordinate system to that of the Window.
        This View must belong to a Window when calling this method. Returns true
        if the conversion is successful or false otherwise.
        """
        cdef CefPoint _a0
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        _g_to_Point(point, &_a0)
        with nogil:
            _r = _p.ConvertPointToWindow(_a0)
        return (_r, _g_from_Point(&_a0))

    def convert_point_from_window(self, point):
        """Convert |point| to this View's coordinate system from that of the Window.
        This View must belong to a Window when calling this method. Returns true
        if the conversion is successful or false otherwise.
        """
        cdef CefPoint _a0
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        _g_to_Point(point, &_a0)
        with nogil:
            _r = _p.ConvertPointFromWindow(_a0)
        return (_r, _g_from_Point(&_a0))

    def convert_point_to_view(self, View view not None, point):
        """Convert |point| from this View's coordinate system to that of |view|.
        |view| needs to be in the same Window but not necessarily the same view
        hierarchy. Returns true if the conversion is successful or false
        otherwise.
        """
        cdef CefRefPtr[CefView] _a0
        cdef CefPoint _a1
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        _a0 = view._ref
        _g_to_Point(point, &_a1)
        with nogil:
            _r = _p.ConvertPointToView(_a0, _a1)
        return (_r, _g_from_Point(&_a1))

    def convert_point_from_view(self, View view not None, point):
        """Convert |point| to this View's coordinate system from that |view|. |view|
        needs to be in the same Window but not necessarily the same view
        hierarchy. Returns true if the conversion is successful or false
        otherwise.
        """
        cdef CefRefPtr[CefView] _a0
        cdef CefPoint _a1
        cdef CefView* _p = self._ptr_CefView()
        cdef cpp_bool _r
        _a0 = view._ref
        _g_to_Point(point, &_a1)
        with nogil:
            _r = _p.ConvertPointFromView(_a0, _a1)
        return (_r, _g_from_Point(&_a1))


cdef object _wrap_View(CefRefPtr[CefView] ref):
    cdef CefRefPtr[CefBrowserView] _c0
    cdef CefRefPtr[CefButton] _c1
    cdef CefRefPtr[CefPanel] _c2
    cdef CefRefPtr[CefScrollView] _c3
    cdef CefRefPtr[CefTextfield] _c4
    cdef View obj
    if ref.get() == NULL:
        return None
    _c0 = ref.get().AsBrowserView()
    if _c0.get() != NULL:
        return _wrap_BrowserView(_c0)
    _c1 = ref.get().AsButton()
    if _c1.get() != NULL:
        return _wrap_Button(_c1)
    _c2 = ref.get().AsPanel()
    if _c2.get() != NULL:
        return _wrap_Panel(_c2)
    _c3 = ref.get().AsScrollView()
    if _c3.get() != NULL:
        return _wrap_ScrollView(_c3)
    _c4 = ref.get().AsTextfield()
    if _c4.get() != NULL:
        return _wrap_Textfield(_c4)
    obj = View.__new__(View)
    obj._ref = ref
    return obj


