# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class BrowserViewDelegate:
    """Implement this interface to handle BrowserView events. The methods of this
    class will be called on the browser process UI thread unless otherwise
    indicated.
    """

    def get_preferred_size(self, view):
        """Return the preferred size for |view|. The Layout will use this information
        to determine the display size.
        """
        return Size()

    def get_minimum_size(self, view):
        """Return the minimum size for |view|."""
        return Size()

    def get_maximum_size(self, view):
        """Return the maximum size for |view|."""
        return Size()

    def get_height_for_width(self, view, width):
        """Return the height necessary to display |view| with the provided |width|.
        If not specified the result of GetPreferredSize().height will be used by
        default. Override if |view|'s preferred height depends upon the width
        (for example, with Labels).
        """
        return 0

    def on_parent_view_changed(self, view, added, parent):
        """Called when the parent of |view| has changed. If |view| is being added to
        |parent| then |added| will be true. If |view| is being removed from
        |parent| then |added| will be false. If |view| is being reparented the
        remove notification will be sent before the add notification. Do not
        modify the view hierarchy in this callback.
        """
        return None

    def on_child_view_changed(self, view, added, child):
        """Called when a child of |view| has changed. If |child| is being added to
        |view| then |added| will be true. If |child| is being removed from |view|
        then |added| will be false. If |child| is being reparented the remove
        notification will be sent to the old parent before the add notification is
        sent to the new parent. Do not modify the view hierarchy in this callback.
        """
        return None

    def on_window_changed(self, view, added):
        """Called when |view| is added or removed from the CefWindow."""
        return None

    def on_layout_changed(self, view, new_bounds):
        """Called when the layout of |view| has changed."""
        return None

    def on_focus(self, view):
        """Called when |view| gains focus."""
        return None

    def on_blur(self, view):
        """Called when |view| loses focus."""
        return None

    def on_theme_changed(self, view):
        """Called when the theme for |view| has changed, after the new theme colors
        have already been applied. Views are notified via the component hierarchy
        in depth-first reverse order (children before parents).

        This will be called in the following cases:

        1. When |view|, or a parent of |view|, is added to a Window.
        2. When the native/OS or Chrome theme changes for the Window that contains
           |view|. See CefWindowDelegate::OnThemeColorsChanged documentation.
        3. When the client explicitly calls CefWindow::ThemeChanged on the Window
           that contains |view|.

        Optionally use this callback to override the new per-View theme colors by
        calling CefView::SetBackgroundColor or the appropriate component-specific
        method. See CefWindow::SetThemeColor documentation for how to customize
        additional Window theme colors.
        """
        return None

    def on_browser_created(self, browser_view, browser):
        """Called when |browser| associated with |browser_view| is created. This
        method will be called after CefLifeSpanHandler::OnAfterCreated() is called
        for |browser| and before OnPopupBrowserViewCreated() is called for
        |browser|'s parent delegate if |browser| is a popup.
        """
        return None

    def on_browser_destroyed(self, browser_view, browser):
        """Called when |browser| associated with |browser_view| is destroyed. Release
        all references to |browser| and do not attempt to execute any methods on
        |browser| after this callback returns. This method will be called before
        CefLifeSpanHandler::OnBeforeClose() is called for |browser|.
        """
        return None

    def get_delegate_for_popup_browser_view(self, browser_view, settings, client, is_devtools):
        """Called before a new popup BrowserView is created. The popup originated
        from |browser_view|. |settings| and |client| are the values returned from
        CefLifeSpanHandler::OnBeforePopup(). |is_devtools| will be true if the
        popup will be a DevTools browser. Return the delegate that will be used
        for the new popup BrowserView.
        """
        return None

    def on_popup_browser_view_created(self, browser_view, popup_browser_view, is_devtools):
        """Called after |popup_browser_view| is created. This method will be called
        after CefLifeSpanHandler::OnAfterCreated() and OnBrowserCreated() are
        called for the new popup browser. The popup originated from
        |browser_view|. |is_devtools| will be true if the popup is a DevTools
        browser. Optionally add |popup_browser_view| to the views hierarchy
        yourself and return true. Otherwise return false and a default CefWindow
        will be created for the popup.
        """
        return False

    def get_chrome_toolbar_type(self, browser_view):
        """Returns the Chrome toolbar type that will be available via
        CefBrowserView::GetChromeToolbar(). See that method for related
        documentation.
        """
        return 0

    def use_frameless_window_for_picture_in_picture(self, browser_view):
        """Return true to create frameless windows for Document picture-in-picture
        popups. Content in frameless windows should specify draggable regions
        using \"-webkit-app-region: drag\" CSS.
        """
        return False

    def allow_move_for_picture_in_picture(self, browser_view):
        """Return true to allow the use of JavaScript moveTo/By() and resizeTo/By()
        (without user activation) with Document picture-in-picture popups.
        """
        return False

    def allow_picture_in_picture_without_user_activation(self, browser_view):
        """Return true to allow opening Document picture-in-picture without
        user activation. Default is false (user activation required).
        """
        return False

    def on_gesture_command(self, browser_view, gesture_command):
        """Called when |browser_view| receives a gesture command. Return true to
        handle (or disable) a |gesture_command| or false to propagate the gesture
        to the browser for default handling. With Chrome style these commands can
        also be handled via CefCommandHandler::OnChromeCommand.
        """
        return False

    def get_browser_runtime_style(self):
        """Optionally change the runtime style for this BrowserView. See
        cef_runtime_style_t documentation for details.
        """
        return 0


cdef void _BrowserViewDelegate_get_preferred_size(void* py, CefView* view, CefSize* result) noexcept with gil:
    try:
        _r = (<object>py).get_preferred_size(_wrap_View(CefRefPtr[CefView](view)))
        _r0 = _r
        _g_to_Size(_r0, result)
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_get_minimum_size(void* py, CefView* view, CefSize* result) noexcept with gil:
    try:
        _r = (<object>py).get_minimum_size(_wrap_View(CefRefPtr[CefView](view)))
        _r0 = _r
        _g_to_Size(_r0, result)
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_get_maximum_size(void* py, CefView* view, CefSize* result) noexcept with gil:
    try:
        _r = (<object>py).get_maximum_size(_wrap_View(CefRefPtr[CefView](view)))
        _r0 = _r
        _g_to_Size(_r0, result)
    except BaseException:
        _g_report()

cdef int _BrowserViewDelegate_get_height_for_width(void* py, CefView* view, int width) noexcept with gil:
    try:
        _r = (<object>py).get_height_for_width(_wrap_View(CefRefPtr[CefView](view)), width)
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _BrowserViewDelegate_on_parent_view_changed(void* py, CefView* view, cpp_bool added, CefView* parent) noexcept with gil:
    try:
        _r = (<object>py).on_parent_view_changed(_wrap_View(CefRefPtr[CefView](view)), added, _wrap_View(CefRefPtr[CefView](parent)))
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_child_view_changed(void* py, CefView* view, cpp_bool added, CefView* child) noexcept with gil:
    try:
        _r = (<object>py).on_child_view_changed(_wrap_View(CefRefPtr[CefView](view)), added, _wrap_View(CefRefPtr[CefView](child)))
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_window_changed(void* py, CefView* view, cpp_bool added) noexcept with gil:
    try:
        _r = (<object>py).on_window_changed(_wrap_View(CefRefPtr[CefView](view)), added)
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_layout_changed(void* py, CefView* view, const CefRect* new_bounds) noexcept with gil:
    try:
        _r = (<object>py).on_layout_changed(_wrap_View(CefRefPtr[CefView](view)), _g_from_Rect(new_bounds))
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_focus(void* py, CefView* view) noexcept with gil:
    try:
        _r = (<object>py).on_focus(_wrap_View(CefRefPtr[CefView](view)))
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_blur(void* py, CefView* view) noexcept with gil:
    try:
        _r = (<object>py).on_blur(_wrap_View(CefRefPtr[CefView](view)))
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_theme_changed(void* py, CefView* view) noexcept with gil:
    try:
        _r = (<object>py).on_theme_changed(_wrap_View(CefRefPtr[CefView](view)))
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_browser_created(void* py, CefBrowserView* browser_view, CefBrowser* browser) noexcept with gil:
    try:
        _r = (<object>py).on_browser_created(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)), _wrap_Browser(CefRefPtr[CefBrowser](browser)))
    except BaseException:
        _g_report()

cdef void _BrowserViewDelegate_on_browser_destroyed(void* py, CefBrowserView* browser_view, CefBrowser* browser) noexcept with gil:
    try:
        _r = (<object>py).on_browser_destroyed(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)), _wrap_Browser(CefRefPtr[CefBrowser](browser)))
    except BaseException:
        _g_report()

cdef CefBrowserViewDelegate* _BrowserViewDelegate_get_delegate_for_popup_browser_view(void* py, CefBrowserView* browser_view, const CefBrowserSettings* settings, CefClient* client, cpp_bool is_devtools) noexcept with gil:
    try:
        _r = (<object>py).get_delegate_for_popup_browser_view(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)), _g_from_BrowserSettings(settings), _g_unexport_Client(CefRefPtr[CefClient](client)), is_devtools)
        _r0 = _r
        return _g_export_BrowserViewDelegate(_r0)
    except BaseException:
        _g_report()
        return NULL

cdef cpp_bool _BrowserViewDelegate_on_popup_browser_view_created(void* py, CefBrowserView* browser_view, CefBrowserView* popup_browser_view, cpp_bool is_devtools) noexcept with gil:
    try:
        _r = (<object>py).on_popup_browser_view_created(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)), _wrap_BrowserView(CefRefPtr[CefBrowserView](popup_browser_view)), is_devtools)
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef int _BrowserViewDelegate_get_chrome_toolbar_type(void* py, CefBrowserView* browser_view) noexcept with gil:
    try:
        _r = (<object>py).get_chrome_toolbar_type(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)))
        _r0 = _r
        return <int>_r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _BrowserViewDelegate_use_frameless_window_for_picture_in_picture(void* py, CefBrowserView* browser_view) noexcept with gil:
    try:
        _r = (<object>py).use_frameless_window_for_picture_in_picture(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _BrowserViewDelegate_allow_move_for_picture_in_picture(void* py, CefBrowserView* browser_view) noexcept with gil:
    try:
        _r = (<object>py).allow_move_for_picture_in_picture(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _BrowserViewDelegate_allow_picture_in_picture_without_user_activation(void* py, CefBrowserView* browser_view) noexcept with gil:
    try:
        _r = (<object>py).allow_picture_in_picture_without_user_activation(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _BrowserViewDelegate_on_gesture_command(void* py, CefBrowserView* browser_view, int gesture_command) noexcept with gil:
    try:
        _r = (<object>py).on_gesture_command(_wrap_BrowserView(CefRefPtr[CefBrowserView](browser_view)), _g_enum(_types.GestureCommand, gesture_command))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef int _BrowserViewDelegate_get_browser_runtime_style(void* py) noexcept with gil:
    try:
        _r = (<object>py).get_browser_runtime_style()
        _r0 = _r
        return <int>_r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefBrowserViewDelegate] _g_make_BrowserViewDelegate(object obj) except *:
    cdef CefRefPtr[CefBrowserViewDelegate] ref
    cdef CwBrowserViewDelegateCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, BrowserViewDelegate):
        raise TypeError("expected a BrowserViewDelegate or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "get_preferred_size", None) is not BrowserViewDelegate.get_preferred_size:
        cb.fn_get_preferred_size = _BrowserViewDelegate_get_preferred_size
    if getattr(cls, "get_minimum_size", None) is not BrowserViewDelegate.get_minimum_size:
        cb.fn_get_minimum_size = _BrowserViewDelegate_get_minimum_size
    if getattr(cls, "get_maximum_size", None) is not BrowserViewDelegate.get_maximum_size:
        cb.fn_get_maximum_size = _BrowserViewDelegate_get_maximum_size
    if getattr(cls, "get_height_for_width", None) is not BrowserViewDelegate.get_height_for_width:
        cb.fn_get_height_for_width = _BrowserViewDelegate_get_height_for_width
    if getattr(cls, "on_parent_view_changed", None) is not BrowserViewDelegate.on_parent_view_changed:
        cb.fn_on_parent_view_changed = _BrowserViewDelegate_on_parent_view_changed
    if getattr(cls, "on_child_view_changed", None) is not BrowserViewDelegate.on_child_view_changed:
        cb.fn_on_child_view_changed = _BrowserViewDelegate_on_child_view_changed
    if getattr(cls, "on_window_changed", None) is not BrowserViewDelegate.on_window_changed:
        cb.fn_on_window_changed = _BrowserViewDelegate_on_window_changed
    if getattr(cls, "on_layout_changed", None) is not BrowserViewDelegate.on_layout_changed:
        cb.fn_on_layout_changed = _BrowserViewDelegate_on_layout_changed
    if getattr(cls, "on_focus", None) is not BrowserViewDelegate.on_focus:
        cb.fn_on_focus = _BrowserViewDelegate_on_focus
    if getattr(cls, "on_blur", None) is not BrowserViewDelegate.on_blur:
        cb.fn_on_blur = _BrowserViewDelegate_on_blur
    if getattr(cls, "on_theme_changed", None) is not BrowserViewDelegate.on_theme_changed:
        cb.fn_on_theme_changed = _BrowserViewDelegate_on_theme_changed
    if getattr(cls, "on_browser_created", None) is not BrowserViewDelegate.on_browser_created:
        cb.fn_on_browser_created = _BrowserViewDelegate_on_browser_created
    if getattr(cls, "on_browser_destroyed", None) is not BrowserViewDelegate.on_browser_destroyed:
        cb.fn_on_browser_destroyed = _BrowserViewDelegate_on_browser_destroyed
    if getattr(cls, "get_delegate_for_popup_browser_view", None) is not BrowserViewDelegate.get_delegate_for_popup_browser_view:
        cb.fn_get_delegate_for_popup_browser_view = _BrowserViewDelegate_get_delegate_for_popup_browser_view
    if getattr(cls, "on_popup_browser_view_created", None) is not BrowserViewDelegate.on_popup_browser_view_created:
        cb.fn_on_popup_browser_view_created = _BrowserViewDelegate_on_popup_browser_view_created
    if getattr(cls, "get_chrome_toolbar_type", None) is not BrowserViewDelegate.get_chrome_toolbar_type:
        cb.fn_get_chrome_toolbar_type = _BrowserViewDelegate_get_chrome_toolbar_type
    if getattr(cls, "use_frameless_window_for_picture_in_picture", None) is not BrowserViewDelegate.use_frameless_window_for_picture_in_picture:
        cb.fn_use_frameless_window_for_picture_in_picture = _BrowserViewDelegate_use_frameless_window_for_picture_in_picture
    if getattr(cls, "allow_move_for_picture_in_picture", None) is not BrowserViewDelegate.allow_move_for_picture_in_picture:
        cb.fn_allow_move_for_picture_in_picture = _BrowserViewDelegate_allow_move_for_picture_in_picture
    if getattr(cls, "allow_picture_in_picture_without_user_activation", None) is not BrowserViewDelegate.allow_picture_in_picture_without_user_activation:
        cb.fn_allow_picture_in_picture_without_user_activation = _BrowserViewDelegate_allow_picture_in_picture_without_user_activation
    if getattr(cls, "on_gesture_command", None) is not BrowserViewDelegate.on_gesture_command:
        cb.fn_on_gesture_command = _BrowserViewDelegate_on_gesture_command
    if getattr(cls, "get_browser_runtime_style", None) is not BrowserViewDelegate.get_browser_runtime_style:
        cb.fn_get_browser_runtime_style = _BrowserViewDelegate_get_browser_runtime_style
    ref = CefRefPtr[CefBrowserViewDelegate](<CefBrowserViewDelegate*>new CwBrowserViewDelegateProxy(cb))
    return ref


cdef inline CefBrowserViewDelegate* _g_export_BrowserViewDelegate(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefBrowserViewDelegate] ref = _g_make_BrowserViewDelegate(obj)
    cdef CefBrowserViewDelegate* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_BrowserViewDelegate(CefRefPtr[CefBrowserViewDelegate] ref):
    """The Python object that was given to CEF as this BrowserViewDelegate (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfBrowserViewDelegate(ref.get())
    if py == NULL:
        return None
    return <object>py


