# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class Callback:
    """Generic callback interface used for asynchronous continuation."""
    cdef CefRefPtr[CefCallback] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("Callback objects are created by CEF or by a create() function")

    cdef CefCallback* _ptr(self) except NULL:
        cdef CefCallback* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("Callback has no CEF object")
        return p

    def continue_(self):
        """Continue processing."""
        cdef CefCallback* _p = self._ptr()
        with nogil:
            _p.Continue()
        return None

    def cancel(self):
        """Cancel processing."""
        cdef CefCallback* _p = self._ptr()
        with nogil:
            _p.Cancel()
        return None


cdef object _wrap_Callback(CefRefPtr[CefCallback] ref):
    cdef Callback obj
    if ref.get() == NULL:
        return None
    obj = Callback.__new__(Callback)
    obj._ref = ref
    return obj


class CompletionCallback:
    """Generic callback interface used for asynchronous completion."""

    def on_complete(self):
        """Method that will be called once the task is complete."""
        return None


cdef void _CompletionCallback_on_complete(void* py) noexcept with gil:
    try:
        _r = (<object>py).on_complete()
    except BaseException:
        _g_report()


cdef CefRefPtr[CefCompletionCallback] _g_make_CompletionCallback(object obj) except *:
    cdef CefRefPtr[CefCompletionCallback] ref
    cdef CwCompletionCallbackCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, CompletionCallback):
        raise TypeError("expected a CompletionCallback or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_complete", None) is not CompletionCallback.on_complete:
        cb.fn_on_complete = _CompletionCallback_on_complete
    ref = CefRefPtr[CefCompletionCallback](<CefCompletionCallback*>new CwCompletionCallbackProxy(cb))
    return ref


cdef inline CefCompletionCallback* _g_export_CompletionCallback(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefCompletionCallback] ref = _g_make_CompletionCallback(obj)
    cdef CefCompletionCallback* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


