# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class MenuModelDelegate:
    """Implement this interface to handle menu model events. The methods of this
    class will be called on the browser process UI thread unless otherwise
    indicated.
    """

    def execute_command(self, menu_model, command_id, event_flags):
        """Perform the action associated with the specified |command_id| and
        optional |event_flags|.
        """
        return None

    def mouse_outside_menu(self, menu_model, screen_point):
        """Called when the user moves the mouse outside the menu and over the owning
        window.
        """
        return None

    def unhandled_open_submenu(self, menu_model, is_rtl):
        """Called on unhandled open submenu keyboard commands. |is_rtl| will be true
        if the menu is displaying a right-to-left language.
        """
        return None

    def unhandled_close_submenu(self, menu_model, is_rtl):
        """Called on unhandled close submenu keyboard commands. |is_rtl| will be true
        if the menu is displaying a right-to-left language.
        """
        return None

    def menu_will_show(self, menu_model):
        """The menu is about to show."""
        return None

    def menu_closed(self, menu_model):
        """The menu has closed."""
        return None

    def format_label(self, menu_model):
        """Optionally modify a menu item label. Return true if |label| was modified."""
        return False, ""


cdef void _MenuModelDelegate_execute_command(void* py, CefMenuModel* menu_model, int command_id, int event_flags) noexcept with gil:
    try:
        _r = (<object>py).execute_command(_wrap_MenuModel(CefRefPtr[CefMenuModel](menu_model)), command_id, _g_enum(_types.EventFlags, event_flags))
    except BaseException:
        _g_report()

cdef void _MenuModelDelegate_mouse_outside_menu(void* py, CefMenuModel* menu_model, const CefPoint* screen_point) noexcept with gil:
    try:
        _r = (<object>py).mouse_outside_menu(_wrap_MenuModel(CefRefPtr[CefMenuModel](menu_model)), _g_from_Point(screen_point))
    except BaseException:
        _g_report()

cdef void _MenuModelDelegate_unhandled_open_submenu(void* py, CefMenuModel* menu_model, cpp_bool is_rtl) noexcept with gil:
    try:
        _r = (<object>py).unhandled_open_submenu(_wrap_MenuModel(CefRefPtr[CefMenuModel](menu_model)), is_rtl)
    except BaseException:
        _g_report()

cdef void _MenuModelDelegate_unhandled_close_submenu(void* py, CefMenuModel* menu_model, cpp_bool is_rtl) noexcept with gil:
    try:
        _r = (<object>py).unhandled_close_submenu(_wrap_MenuModel(CefRefPtr[CefMenuModel](menu_model)), is_rtl)
    except BaseException:
        _g_report()

cdef void _MenuModelDelegate_menu_will_show(void* py, CefMenuModel* menu_model) noexcept with gil:
    try:
        _r = (<object>py).menu_will_show(_wrap_MenuModel(CefRefPtr[CefMenuModel](menu_model)))
    except BaseException:
        _g_report()

cdef void _MenuModelDelegate_menu_closed(void* py, CefMenuModel* menu_model) noexcept with gil:
    try:
        _r = (<object>py).menu_closed(_wrap_MenuModel(CefRefPtr[CefMenuModel](menu_model)))
    except BaseException:
        _g_report()

cdef cpp_bool _MenuModelDelegate_format_label(void* py, CefMenuModel* menu_model, CefString* label) noexcept with gil:
    try:
        _r = (<object>py).format_label(_wrap_MenuModel(CefRefPtr[CefMenuModel](menu_model)))
        _r0, _r1 = _r
        label[0] = _g_cef(_r1)
        return _r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefMenuModelDelegate] _g_make_MenuModelDelegate(object obj) except *:
    cdef CefRefPtr[CefMenuModelDelegate] ref
    cdef CwMenuModelDelegateCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, MenuModelDelegate):
        raise TypeError("expected a MenuModelDelegate or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "execute_command", None) is not MenuModelDelegate.execute_command:
        cb.fn_execute_command = _MenuModelDelegate_execute_command
    if getattr(cls, "mouse_outside_menu", None) is not MenuModelDelegate.mouse_outside_menu:
        cb.fn_mouse_outside_menu = _MenuModelDelegate_mouse_outside_menu
    if getattr(cls, "unhandled_open_submenu", None) is not MenuModelDelegate.unhandled_open_submenu:
        cb.fn_unhandled_open_submenu = _MenuModelDelegate_unhandled_open_submenu
    if getattr(cls, "unhandled_close_submenu", None) is not MenuModelDelegate.unhandled_close_submenu:
        cb.fn_unhandled_close_submenu = _MenuModelDelegate_unhandled_close_submenu
    if getattr(cls, "menu_will_show", None) is not MenuModelDelegate.menu_will_show:
        cb.fn_menu_will_show = _MenuModelDelegate_menu_will_show
    if getattr(cls, "menu_closed", None) is not MenuModelDelegate.menu_closed:
        cb.fn_menu_closed = _MenuModelDelegate_menu_closed
    if getattr(cls, "format_label", None) is not MenuModelDelegate.format_label:
        cb.fn_format_label = _MenuModelDelegate_format_label
    ref = CefRefPtr[CefMenuModelDelegate](<CefMenuModelDelegate*>new CwMenuModelDelegateProxy(cb))
    return ref


cdef inline CefMenuModelDelegate* _g_export_MenuModelDelegate(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefMenuModelDelegate] ref = _g_make_MenuModelDelegate(obj)
    cdef CefMenuModelDelegate* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


