# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class StringVisitor:
    """Implement this interface to receive string values asynchronously."""

    def visit(self, string):
        """Method that will be executed."""
        return None


cdef void _StringVisitor_visit(void* py, const CefString* string) noexcept with gil:
    try:
        _r = (<object>py).visit(_g_str(string[0]))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefStringVisitor] _g_make_StringVisitor(object obj) except *:
    cdef CefRefPtr[CefStringVisitor] ref
    cdef CwStringVisitorCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, StringVisitor):
        raise TypeError("expected a StringVisitor or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "visit", None) is not StringVisitor.visit:
        cb.fn_visit = _StringVisitor_visit
    ref = CefRefPtr[CefStringVisitor](<CefStringVisitor*>new CwStringVisitorProxy(cb))
    return ref


cdef inline CefStringVisitor* _g_export_StringVisitor(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefStringVisitor] ref = _g_make_StringVisitor(obj)
    cdef CefStringVisitor* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_StringVisitor(CefRefPtr[CefStringVisitor] ref):
    """The Python object that was given to CEF as this StringVisitor (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfStringVisitor(ref.get())
    if py == NULL:
        return None
    return <object>py


