# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class Registration:
    """Generic callback interface used for managing the lifespan of a registration."""
    cdef CefRefPtr[CefRegistration] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("Registration objects are created by CEF or by a create() function")

    cdef CefRegistration* _ptr(self) except NULL:
        cdef CefRegistration* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("Registration has no CEF object")
        return p


cdef object _wrap_Registration(CefRefPtr[CefRegistration] ref):
    cdef Registration obj
    if ref.get() == NULL:
        return None
    obj = Registration.__new__(Registration)
    obj._ref = ref
    return obj


cdef inline CefRegistration* _g_ref_Registration(object obj) except? NULL:
    """A reference for CEF to keep (a Registration that a handler method returns; None: nothing)."""
    cdef Registration typed
    cdef CefRefPtr[CefRegistration] ref
    cdef CefRegistration* raw
    if obj is None:
        return NULL
    if not isinstance(obj, Registration):
        raise TypeError("expected a Registration or None, not %s" % type(obj).__name__)
    typed = <Registration>obj
    ref = typed._ref
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


