# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class Browser:
    """Class used to represent a browser. When used in the browser process the
    methods of this class may be called on any thread unless otherwise indicated
    in the comments. When used in the render process the methods of this class
    may only be called on the main thread.
    """
    cdef CefRefPtr[CefBrowser] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("Browser objects are created by CEF or by a create() function")

    cdef CefBrowser* _ptr(self) except NULL:
        cdef CefBrowser* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("Browser has no CEF object")
        return p

    def is_valid(self):
        """True if this object is currently valid. This will return false after
        CefLifeSpanHandler::OnBeforeClose is called.
        """
        cdef CefBrowser* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsValid()
        return _r

    def get_host(self):
        """Returns the browser host object. This method can only be called in the
        browser process.
        """
        cdef CefBrowser* _p = self._ptr()
        cdef CefRefPtr[CefBrowserHost] _r
        with nogil:
            _r = _p.GetHost()
        return _wrap_BrowserHost(_r)

    def can_go_back(self):
        """Returns true if the browser can navigate backwards."""
        cdef CefBrowser* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.CanGoBack()
        return _r

    def go_back(self):
        """Navigate backwards."""
        cdef CefBrowser* _p = self._ptr()
        with nogil:
            _p.GoBack()
        return None

    def can_go_forward(self):
        """Returns true if the browser can navigate forwards."""
        cdef CefBrowser* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.CanGoForward()
        return _r

    def go_forward(self):
        """Navigate forwards."""
        cdef CefBrowser* _p = self._ptr()
        with nogil:
            _p.GoForward()
        return None

    def is_loading(self):
        """Returns true if the browser is currently loading."""
        cdef CefBrowser* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsLoading()
        return _r

    def reload(self):
        """Reload the current page."""
        cdef CefBrowser* _p = self._ptr()
        with nogil:
            _p.Reload()
        return None

    def reload_ignore_cache(self):
        """Reload the current page ignoring any cached data."""
        cdef CefBrowser* _p = self._ptr()
        with nogil:
            _p.ReloadIgnoreCache()
        return None

    def stop_load(self):
        """Stop loading the page."""
        cdef CefBrowser* _p = self._ptr()
        with nogil:
            _p.StopLoad()
        return None

    def get_identifier(self):
        """Returns the globally unique identifier for this browser. This value is
        also used as the tabId for extension APIs.
        """
        cdef CefBrowser* _p = self._ptr()
        cdef int _r
        with nogil:
            _r = _p.GetIdentifier()
        return _r

    def is_same(self, Browser that not None):
        """Returns true if this object is pointing to the same handle as |that|
        object.
        """
        cdef CefRefPtr[CefBrowser] _a0
        cdef CefBrowser* _p = self._ptr()
        cdef cpp_bool _r
        _a0 = that._ref
        with nogil:
            _r = _p.IsSame(_a0)
        return _r

    def is_popup(self):
        """Returns true if the browser is a popup."""
        cdef CefBrowser* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsPopup()
        return _r

    def has_document(self):
        """Returns true if a document has been loaded in the browser."""
        cdef CefBrowser* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasDocument()
        return _r

    def get_main_frame(self):
        """Returns the main (top-level) frame for the browser. In the browser process
        this will return a valid object until after
        CefLifeSpanHandler::OnBeforeClose is called. In the renderer process this
        will return NULL if the main frame is hosted in a different renderer
        process (e.g. for cross-origin sub-frames). The main frame object will
        change during cross-origin navigation or re-navigation after renderer
        process termination (due to crashes, etc).
        """
        cdef CefBrowser* _p = self._ptr()
        cdef CefRefPtr[CefFrame] _r
        with nogil:
            _r = _p.GetMainFrame()
        return _wrap_Frame(_r)

    def get_focused_frame(self):
        """Returns the focused frame for the browser."""
        cdef CefBrowser* _p = self._ptr()
        cdef CefRefPtr[CefFrame] _r
        with nogil:
            _r = _p.GetFocusedFrame()
        return _wrap_Frame(_r)

    def get_frame_by_identifier(self, identifier):
        """Returns the frame with the specified identifier, or NULL if not found."""
        cdef CefString _a0
        cdef CefBrowser* _p = self._ptr()
        cdef CefRefPtr[CefFrame] _r
        _a0 = _g_cef(identifier)
        with nogil:
            _r = _p.GetFrameByIdentifier(_a0)
        return _wrap_Frame(_r)

    def get_frame_by_name(self, name):
        """Returns the frame with the specified name, or NULL if not found."""
        cdef CefString _a0
        cdef CefBrowser* _p = self._ptr()
        cdef CefRefPtr[CefFrame] _r
        if name is not None:
            _a0 = _g_cef(name)
        with nogil:
            _r = _p.GetFrameByName(_a0)
        return _wrap_Frame(_r)

    def get_frame_count(self):
        """Returns the number of frames that currently exist."""
        cdef CefBrowser* _p = self._ptr()
        cdef size_t _r
        with nogil:
            _r = _p.GetFrameCount()
        return _r

    def get_frame_identifiers(self):
        """Returns the identifiers of all existing frames."""
        cdef vector[CefString] _a0
        cdef CefBrowser* _p = self._ptr()
        with nogil:
            _p.GetFrameIdentifiers(_a0)
        return _g_str_list(&_a0)

    def get_frame_names(self):
        """Returns the names of all existing frames."""
        cdef vector[CefString] _a0
        cdef CefBrowser* _p = self._ptr()
        with nogil:
            _p.GetFrameNames(_a0)
        return _g_str_list(&_a0)


cdef object _wrap_Browser(CefRefPtr[CefBrowser] ref):
    cdef Browser obj
    if ref.get() == NULL:
        return None
    obj = Browser.__new__(Browser)
    obj._ref = ref
    return obj


cdef class BrowserHost:
    """Class used to represent the browser process aspects of a browser. The
    methods of this class can only be called in the browser process. They may be
    called on any thread in that process unless otherwise indicated in the
    comments.
    """
    cdef CefRefPtr[CefBrowserHost] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("BrowserHost objects are created by CEF or by a create() function")

    cdef CefBrowserHost* _ptr(self) except NULL:
        cdef CefBrowserHost* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("BrowserHost has no CEF object")
        return p

    def get_browser(self):
        """Returns the hosted browser object."""
        cdef CefBrowserHost* _p = self._ptr()
        cdef CefRefPtr[CefBrowser] _r
        with nogil:
            _r = _p.GetBrowser()
        return _wrap_Browser(_r)

    def close_browser(self, bint force_close):
        """Request that the browser close. Closing a browser is a multi-stage process
        that may complete either synchronously or asynchronously, and involves
        callbacks such as CefLifeSpanHandler::DoClose (Alloy style only),
        CefLifeSpanHandler::OnBeforeClose, and a top-level window close handler
        such as CefWindowDelegate::CanClose (or platform-specific equivalent). In
        some cases a close request may be delayed or canceled by the user. Using
        TryCloseBrowser() instead of CloseBrowser() is recommended for most use
        cases. See CefLifeSpanHandler::DoClose() documentation for detailed usage
        and examples.

        If |force_close| is false then JavaScript unload handlers, if any, may be
        fired and the close may be delayed or canceled by the user. If
        |force_close| is true then the user will not be prompted and the close
        will proceed immediately (possibly asynchronously). If browser close is
        delayed and not canceled the default behavior is to call the top-level
        window close handler once the browser is ready to be closed. This default
        behavior can be changed for Alloy style browsers by implementing
        CefLifeSpanHandler::DoClose(). IsReadyToBeClosed() can be used to detect
        mandatory browser close events when customizing close behavior on the
        browser process UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.CloseBrowser(force_close)
        return None

    def try_close_browser(self):
        """Helper for closing a browser. This is similar in behavior to
        CLoseBrowser(false) but returns a boolean to reflect the immediate close
        status. Call this method from a top-level window close handler such as
        CefWindowDelegate::CanClose (or platform-specific equivalent) to request
        that the browser close, and return the result to indicate if the window
        close should proceed. Returns false if the close will be delayed
        (JavaScript unload handlers triggered but still pending) or true if the
        close will proceed immediately (possibly asynchronously). See
        CloseBrowser() documentation for additional usage information. This method
        must be called on the browser process UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.TryCloseBrowser()
        return _r

    def is_ready_to_be_closed(self):
        """Returns true if the browser is ready to be closed, meaning that the close
        has already been initiated and that JavaScript unload handlers have
        already executed or should be ignored. This can be used from a top-level
        window close handler such as CefWindowDelegate::CanClose (or
        platform-specific equivalent) to distringuish between potentially
        cancelable browser close events (like the user clicking the top-level
        window close button before browser close has started) and mandatory
        browser close events (like JavaScript `window.close()` or after browser
        close has started in response to [Try]CloseBrowser()). Not completing the
        browser close for mandatory close events (when this method returns true)
        will leave the browser in a partially closed state that interferes with
        proper functioning. See CloseBrowser() documentation for additional usage
        information. This method must be called on the browser process UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsReadyToBeClosed()
        return _r

    def set_focus(self, bint focus):
        """Set whether the browser is focused."""
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SetFocus(focus)
        return None

    def get_window_handle(self):
        """Retrieve the window handle (if any) for this browser. If this browser is
        wrapped in a CefBrowserView this method should be called on the browser
        process UI thread and it will return the handle for the top-level native
        window.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cef_window_handle_t _r
        with nogil:
            _r = _p.GetWindowHandle()
        return _r

    def get_opener_window_handle(self):
        """Retrieve the window handle (if any) of the browser that opened this
        browser. Will return NULL for non-popup browsers or if this browser is
        wrapped in a CefBrowserView. This method can be used in combination with
        custom handling of modal windows.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cef_window_handle_t _r
        with nogil:
            _r = _p.GetOpenerWindowHandle()
        return _r

    def get_opener_identifier(self):
        """Retrieve the unique identifier of the browser that opened this browser.
        Will return 0 for non-popup browsers.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef int _r
        with nogil:
            _r = _p.GetOpenerIdentifier()
        return _r

    def has_view(self):
        """Returns true if this browser is wrapped in a CefBrowserView."""
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasView()
        return _r

    def get_request_context(self):
        """Returns the request context for this browser."""
        cdef CefBrowserHost* _p = self._ptr()
        cdef CefRefPtr[CefRequestContext] _r
        with nogil:
            _r = _p.GetRequestContext()
        return _wrap_RequestContext(_r)

    def can_zoom(self, long long command):
        """Returns true if this browser can execute the specified zoom command. This
        method can only be called on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.CanZoom(<cef_zoom_command_t>command)
        return _r

    def zoom(self, long long command):
        """Execute a zoom command in this browser. If called on the UI thread the
        change will be applied immediately. Otherwise, the change will be applied
        asynchronously on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.Zoom(<cef_zoom_command_t>command)
        return None

    def get_default_zoom_level(self):
        """Get the default zoom level. This value will be 0.0 by default but can be
        configured. This method can only be called on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef double _r
        with nogil:
            _r = _p.GetDefaultZoomLevel()
        return _r

    def get_zoom_level(self):
        """Get the current zoom level. This method can only be called on the UI
        thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef double _r
        with nogil:
            _r = _p.GetZoomLevel()
        return _r

    def set_zoom_level(self, double zoom_level):
        """Change the zoom level to the specified value. Specify 0.0 to reset the
        zoom level to the default. If called on the UI thread the change will be
        applied immediately. Otherwise, the change will be applied asynchronously
        on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SetZoomLevel(zoom_level)
        return None

    def run_file_dialog(self, long long mode, title, default_file_path, accept_filters, callback):
        """Call to run a file chooser dialog. Only a single file chooser dialog may
        be pending at any given time. |mode| represents the type of dialog to
        display. |title| to the title to be used for the dialog and may be empty
        to show the default title (\"Open\" or \"Save\" depending on the mode).
        |default_file_path| is the path with optional directory and/or file name
        component that will be initially selected in the dialog. |accept_filters|
        are used to restrict the selectable file types and may any combination of
        (a) valid lower-cased MIME types (e.g. \"text/*\" or \"image/*\"), (b)
        individual file extensions (e.g.
        \".txt\" or \".png\"), or (c) combined description and file extension
        delimited using \"|\" and \";\" (e.g. \"Image Types|.png;.gif;.jpg\").
        |callback| will be executed after the dialog is dismissed or immediately
        if another dialog is already pending. The dialog will be initiated
        asynchronously on the UI thread.
        """
        cdef CefString _a1
        cdef CefString _a2
        cdef vector[CefString] _a3
        cdef CefRefPtr[CefRunFileDialogCallback] _a4
        cdef CefBrowserHost* _p = self._ptr()
        if title is not None:
            _a1 = _g_cef(title)
        if default_file_path is not None:
            _a2 = _g_cef(default_file_path)
        _g_str_vector(accept_filters, _a3)
        if callback is None:
            raise TypeError("callback must not be None")
        _a4 = _g_make_RunFileDialogCallback(callback)
        with nogil:
            _p.RunFileDialog(<cef_file_dialog_mode_t>mode, _a1, _a2, _a3, _a4)
        return None

    def start_download(self, url):
        """Download the file at |url| using CefDownloadHandler."""
        cdef CefString _a0
        cdef CefBrowserHost* _p = self._ptr()
        _a0 = _g_cef(url)
        with nogil:
            _p.StartDownload(_a0)
        return None

    def download_image(self, image_url, bint is_favicon, uint32_t max_image_size, bint bypass_cache, callback):
        """Download |image_url| and execute |callback| on completion with the images
        received from the renderer. If |is_favicon| is true then cookies are not
        sent and not accepted during download. Images with density independent
        pixel (DIP) sizes larger than |max_image_size| are filtered out from the
        image results. Versions of the image at different scale factors may be
        downloaded up to the maximum scale factor supported by the system. If
        there are no image results <= |max_image_size| then the smallest image is
        resized to |max_image_size| and is the only result. A |max_image_size| of
        0 means unlimited. If |bypass_cache| is true then |image_url| is requested
        from the server even if it is present in the browser cache.
        """
        cdef CefString _a0
        cdef CefRefPtr[CefDownloadImageCallback] _a4
        cdef CefBrowserHost* _p = self._ptr()
        _a0 = _g_cef(image_url)
        if callback is None:
            raise TypeError("callback must not be None")
        _a4 = _g_make_DownloadImageCallback(callback)
        with nogil:
            _p.DownloadImage(_a0, is_favicon, max_image_size, bypass_cache, _a4)
        return None

    def print(self):
        """Print the current browser contents."""
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.Print()
        return None

    def print_to_pdf(self, path, settings, callback):
        """Print the current browser contents to the PDF file specified by |path| and
        execute |callback| on completion. The caller is responsible for deleting
        |path| when done. For PDF printing to work on Linux you must implement the
        CefPrintHandler::GetPdfPaperSize method.
        """
        cdef CefString _a0
        cdef CefPdfPrintSettings _a1
        cdef CefRefPtr[CefPdfPrintCallback] _a2
        cdef CefBrowserHost* _p = self._ptr()
        _a0 = _g_cef(path)
        _g_to_PdfPrintSettings(settings, &_a1)
        _a2 = _g_make_PdfPrintCallback(callback)
        with nogil:
            _p.PrintToPDF(_a0, _a1, _a2)
        return None

    def find(self, search_text, bint forward, bint match_case, bint find_next):
        """Search for |searchText|. |forward| indicates whether to search forward or
        backward within the page. |matchCase| indicates whether the search should
        be case-sensitive. |findNext| indicates whether this is the first request
        or a follow-up. The search will be restarted if |searchText| or
        |matchCase| change. The search will be stopped if |searchText| is empty.
        The CefFindHandler instance, if any, returned via
        CefClient::GetFindHandler will be called to report find results.
        """
        cdef CefString _a0
        cdef CefBrowserHost* _p = self._ptr()
        _a0 = _g_cef(search_text)
        with nogil:
            _p.Find(_a0, forward, match_case, find_next)
        return None

    def stop_finding(self, bint clear_selection):
        """Cancel all searches that are currently going on."""
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.StopFinding(clear_selection)
        return None

    def close_dev_tools(self):
        """Explicitly close the associated DevTools browser, if any."""
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.CloseDevTools()
        return None

    def has_dev_tools(self):
        """Returns true if this browser currently has an associated DevTools browser.
        Must be called on the browser process UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasDevTools()
        return _r

    def send_dev_tools_message(self, message):
        """Send a method call message over the DevTools protocol. |message| must be a
        UTF8-encoded JSON dictionary that contains \"id\" (int), \"method\" (string)
        and \"params\" (dictionary, optional) values. See the DevTools protocol
        documentation at https://chromedevtools.github.io/devtools-protocol/ for
        details of supported methods and the expected \"params\" dictionary
        contents. |message| will be copied if necessary. This method will return
        true if called on the UI thread and the message was successfully submitted
        for validation, otherwise false. Validation will be applied asynchronously
        and any messages that fail due to formatting errors or missing parameters
        may be discarded without notification. Prefer ExecuteDevToolsMethod if a
        more structured approach to message formatting is desired.

        Every valid method call will result in an asynchronous method result or
        error message that references the sent message \"id\". Event messages are
        received while notifications are enabled (for example, between method
        calls for \"Page.enable\" and \"Page.disable\"). All received messages will be
        delivered to the observer(s) registered with AddDevToolsMessageObserver.
        See CefDevToolsMessageObserver::OnDevToolsMessage documentation for
        details of received message contents.

        Usage of the SendDevToolsMessage, ExecuteDevToolsMethod and
        AddDevToolsMessageObserver methods does not require an active DevTools
        front-end or remote-debugging session. Other active DevTools sessions will
        continue to function independently. However, any modification of global
        browser state by one session may not be reflected in the UI of other
        sessions.

        Communication with the DevTools front-end (when displayed) can be logged
        for development purposes by passing the
        `--devtools-protocol-log-file=<path>` command-line flag.
        """
        cdef const unsigned char[::1] _v0
        cdef const void* _a0 = NULL
        cdef size_t _n0 = 0
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        if message is None:
            raise TypeError("message must be bytes-like, not None")
        _v0 = message
        _n0 = _v0.shape[0]
        if _n0:
            _a0 = &_v0[0]
        with nogil:
            _r = _p.SendDevToolsMessage(_a0, _n0)
        return _r

    def execute_dev_tools_method(self, int message_id, method, DictionaryValue params):
        """Execute a method call over the DevTools protocol. This is a more
        structured version of SendDevToolsMessage. |message_id| is an incremental
        number that uniquely identifies the message (pass 0 to have the next
        number assigned automatically based on previous values). |method| is the
        method name. |params| are the method parameters, which may be empty. See
        the DevTools protocol documentation (linked above) for details of
        supported methods and the expected |params| dictionary contents. This
        method will return the assigned message ID if called on the UI thread and
        the message was successfully submitted for validation, otherwise 0. See
        the SendDevToolsMessage documentation for additional usage information.
        """
        cdef CefString _a1
        cdef CefRefPtr[CefDictionaryValue] _a2
        cdef CefBrowserHost* _p = self._ptr()
        cdef int _r
        _a1 = _g_cef(method)
        if params is not None:
            _a2 = params._ref
        with nogil:
            _r = _p.ExecuteDevToolsMethod(message_id, _a1, _a2)
        return _r

    def add_dev_tools_message_observer(self, observer):
        """Add an observer for DevTools protocol messages (method results and
        events). The observer will remain registered until the returned
        Registration object is destroyed. See the SendDevToolsMessage
        documentation for additional usage information.
        """
        cdef CefRefPtr[CefDevToolsMessageObserver] _a0
        cdef CefBrowserHost* _p = self._ptr()
        cdef CefRefPtr[CefRegistration] _r
        if observer is None:
            raise TypeError("observer must not be None")
        _a0 = _g_make_DevToolsMessageObserver(observer)
        with nogil:
            _r = _p.AddDevToolsMessageObserver(_a0)
        return _wrap_Registration(_r)

    def replace_misspelling(self, word):
        """If a misspelled word is currently selected in an editable node calling
        this method will replace it with the specified |word|.
        """
        cdef CefString _a0
        cdef CefBrowserHost* _p = self._ptr()
        _a0 = _g_cef(word)
        with nogil:
            _p.ReplaceMisspelling(_a0)
        return None

    def add_word_to_dictionary(self, word):
        """Add the specified |word| to the spelling dictionary."""
        cdef CefString _a0
        cdef CefBrowserHost* _p = self._ptr()
        _a0 = _g_cef(word)
        with nogil:
            _p.AddWordToDictionary(_a0)
        return None

    def is_window_rendering_disabled(self):
        """Returns true if window rendering is disabled."""
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsWindowRenderingDisabled()
        return _r

    def was_resized(self):
        """Notify the browser that the widget has been resized. The browser will
        first call CefRenderHandler::GetViewRect to get the new size and then call
        CefRenderHandler::OnPaint asynchronously with the updated regions. This
        method is only used when window rendering is disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.WasResized()
        return None

    def was_hidden(self, bint hidden):
        """Notify the browser that it has been hidden or shown. Layouting and
        CefRenderHandler::OnPaint notification will stop when the browser is
        hidden. This method is only used when window rendering is disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.WasHidden(hidden)
        return None

    def notify_screen_info_changed(self):
        """Notify the browser that screen information has changed. Updated
        information will be sent to the renderer process to configure screen size
        and position values used by CSS and JavaScript (window.deviceScaleFactor,
        window.screenX/Y, window.outerWidth/Height, etc.). For background see
        https://chromiumembedded.github.io/cef/general_usage#coordinate-systems

        This method is used with (a) windowless rendering and (b) windowed
        rendering with external (client-provided) root window.

        With windowless rendering the browser will call
        CefRenderHandler::GetScreenInfo, CefRenderHandler::GetRootScreenRect and
        CefRenderHandler::GetViewRect. This simulates moving or resizing the root
        window in the current display, moving the root window from one display to
        another, or changing the properties of the current display.

        With windowed rendering the browser will call
        CefDisplayHandler::GetRootWindowScreenRect and use the associated
        display properties.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.NotifyScreenInfoChanged()
        return None

    def invalidate(self, long long type):
        """Invalidate the view. The browser will call CefRenderHandler::OnPaint
        asynchronously. This method is only used when window rendering is
        disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.Invalidate(<cef_paint_element_type_t>type)
        return None

    def send_external_begin_frame(self):
        """Issue a BeginFrame request to Chromium.  Only valid when
        CefWindowInfo::external_begin_frame_enabled is set to true.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SendExternalBeginFrame()
        return None

    def send_key_event(self, event):
        """Send a key event to the browser."""
        cdef CefKeyEvent _a0
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_KeyEvent(event, &_a0)
        with nogil:
            _p.SendKeyEvent(_a0)
        return None

    def send_mouse_click_event(self, event, long long type, bint mouse_up, int click_count):
        """Send a mouse click event to the browser. The |x| and |y| coordinates are
        relative to the upper-left corner of the view.
        """
        cdef CefMouseEvent _a0
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_MouseEvent(event, &_a0)
        with nogil:
            _p.SendMouseClickEvent(_a0, <cef_mouse_button_type_t>type, mouse_up, click_count)
        return None

    def send_mouse_move_event(self, event, bint mouse_leave):
        """Send a mouse move event to the browser. The |x| and |y| coordinates are
        relative to the upper-left corner of the view.
        """
        cdef CefMouseEvent _a0
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_MouseEvent(event, &_a0)
        with nogil:
            _p.SendMouseMoveEvent(_a0, mouse_leave)
        return None

    def send_mouse_wheel_event(self, event, int delta_x, int delta_y):
        """Send a mouse wheel event to the browser. The |x| and |y| coordinates are
        relative to the upper-left corner of the view. The |deltaX| and |deltaY|
        values represent the movement delta in the X and Y directions
        respectively. In order to scroll inside select popups with window
        rendering disabled CefRenderHandler::GetScreenPoint should be implemented
        properly.
        """
        cdef CefMouseEvent _a0
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_MouseEvent(event, &_a0)
        with nogil:
            _p.SendMouseWheelEvent(_a0, delta_x, delta_y)
        return None

    def send_touch_event(self, event):
        """Send a touch event to the browser for a windowless browser."""
        cdef CefTouchEvent _a0
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_TouchEvent(event, &_a0)
        with nogil:
            _p.SendTouchEvent(_a0)
        return None

    def send_capture_lost_event(self):
        """Send a capture lost event to the browser."""
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SendCaptureLostEvent()
        return None

    def notify_move_or_resize_started(self):
        """Notify the browser that the window hosting it is about to be moved or
        resized. This method is only used on Windows and Linux.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.NotifyMoveOrResizeStarted()
        return None

    def get_windowless_frame_rate(self):
        """Returns the maximum rate in frames per second (fps) that
        CefRenderHandler::OnPaint will be called for a windowless browser. The
        actual fps may be lower if the browser cannot generate frames at the
        requested rate. The minimum value is 1 and the default value is 30. This
        method can only be called on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef int _r
        with nogil:
            _r = _p.GetWindowlessFrameRate()
        return _r

    def set_windowless_frame_rate(self, int frame_rate):
        """Set the maximum rate in frames per second (fps) that CefRenderHandler::
        OnPaint will be called for a windowless browser. The actual fps may be
        lower if the browser cannot generate frames at the requested rate. The
        minimum value is 1 and the default value is 30. Can also be set at browser
        creation via CefBrowserSettings.windowless_frame_rate.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SetWindowlessFrameRate(frame_rate)
        return None

    def ime_set_composition(self, text, underlines, replacement_range, selection_range):
        """Begins a new composition or updates the existing composition. Blink has a
        special node (a composition node) that allows the input method to change
        text without affecting other DOM nodes. |text| is the optional text that
        will be inserted into the composition node. |underlines| is an optional
        set of ranges that will be underlined in the resulting text.
        |replacement_range| is an optional range of the existing text that will be
        replaced. |selection_range| is an optional range of the resulting text
        that will be selected after insertion or replacement. The
        |replacement_range| value is only used on OS X.

        This method may be called multiple times as the composition changes. When
        the client is done making changes the composition should either be
        canceled or completed. To cancel the composition call
        ImeCancelComposition. To complete the composition call either
        ImeCommitText or ImeFinishComposingText. Completion is usually signaled
        when:

        1. The client receives a WM_IME_COMPOSITION message with a GCS_RESULTSTR
           flag (on Windows), or;
        2. The client receives a \"commit\" signal of GtkIMContext (on Linux), or;
        3. insertText of NSTextInput is called (on Mac).

        This method is only used when window rendering is disabled.
        """
        cdef CefString _a0
        cdef vector[CefCompositionUnderline] _a1
        cdef CefRange _a2
        cdef CefRange _a3
        cdef CefBrowserHost* _p = self._ptr()
        if text is not None:
            _a0 = _g_cef(text)
        _g_vector_CompositionUnderline(underlines, _a1)
        _g_to_Range(replacement_range, &_a2)
        _g_to_Range(selection_range, &_a3)
        with nogil:
            _p.ImeSetComposition(_a0, _a1, _a2, _a3)
        return None

    def ime_commit_text(self, text, replacement_range, int relative_cursor_pos):
        """Completes the existing composition by optionally inserting the specified
        |text| into the composition node. |replacement_range| is an optional range
        of the existing text that will be replaced. |relative_cursor_pos| is where
        the cursor will be positioned relative to the current cursor position. See
        comments on ImeSetComposition for usage. The |replacement_range| and
        |relative_cursor_pos| values are only used on OS X.
        This method is only used when window rendering is disabled.
        """
        cdef CefString _a0
        cdef CefRange _a1
        cdef CefBrowserHost* _p = self._ptr()
        if text is not None:
            _a0 = _g_cef(text)
        _g_to_Range(replacement_range, &_a1)
        with nogil:
            _p.ImeCommitText(_a0, _a1, relative_cursor_pos)
        return None

    def ime_finish_composing_text(self, bint keep_selection):
        """Completes the existing composition by applying the current composition
        node contents. If |keep_selection| is false the current selection, if any,
        will be discarded. See comments on ImeSetComposition for usage. This
        method is only used when window rendering is disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.ImeFinishComposingText(keep_selection)
        return None

    def ime_cancel_composition(self):
        """Cancels the existing composition and discards the composition node
        contents without applying them. See comments on ImeSetComposition for
        usage.
        This method is only used when window rendering is disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.ImeCancelComposition()
        return None

    def drag_target_drag_enter(self, DragData drag_data not None, event, long long allowed_ops):
        """Call this method when the user drags the mouse into the web view (before
        calling DragTargetDragOver/DragTargetLeave/DragTargetDrop).
        |drag_data| should not contain file contents as this type of data is not
        allowed to be dragged into the web view. File contents can be removed
        using CefDragData::ResetFileContents (for example, if |drag_data| comes
        from CefRenderHandler::StartDragging). This method is only used when
        window rendering is disabled.
        """
        cdef CefRefPtr[CefDragData] _a0
        cdef CefMouseEvent _a1
        cdef CefBrowserHost* _p = self._ptr()
        _a0 = drag_data._ref
        _g_to_MouseEvent(event, &_a1)
        with nogil:
            _p.DragTargetDragEnter(_a0, _a1, <cef_drag_operations_mask_t>allowed_ops)
        return None

    def drag_target_drag_over(self, event, long long allowed_ops):
        """Call this method each time the mouse is moved across the web view during
        a drag operation (after calling DragTargetDragEnter and before calling
        DragTargetDragLeave/DragTargetDrop).
        This method is only used when window rendering is disabled.
        """
        cdef CefMouseEvent _a0
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_MouseEvent(event, &_a0)
        with nogil:
            _p.DragTargetDragOver(_a0, <cef_drag_operations_mask_t>allowed_ops)
        return None

    def drag_target_drag_leave(self):
        """Call this method when the user drags the mouse out of the web view (after
        calling DragTargetDragEnter).
        This method is only used when window rendering is disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.DragTargetDragLeave()
        return None

    def drag_target_drop(self, event):
        """Call this method when the user completes the drag operation by dropping
        the object onto the web view (after calling DragTargetDragEnter).
        The object being dropped is |drag_data|, given as an argument to
        the previous DragTargetDragEnter call.
        This method is only used when window rendering is disabled.
        """
        cdef CefMouseEvent _a0
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_MouseEvent(event, &_a0)
        with nogil:
            _p.DragTargetDrop(_a0)
        return None

    def drag_source_ended_at(self, int x, int y, long long op):
        """Call this method when the drag operation started by a
        CefRenderHandler::StartDragging call has ended either in a drop or
        by being cancelled. |x| and |y| are mouse coordinates relative to the
        upper-left corner of the view. If the web view is both the drag source
        and the drag target then all DragTarget* methods should be called before
        DragSource* mthods.
        This method is only used when window rendering is disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.DragSourceEndedAt(x, y, <cef_drag_operations_mask_t>op)
        return None

    def drag_source_system_drag_ended(self):
        """Call this method when the drag operation started by a
        CefRenderHandler::StartDragging call has completed. This method may be
        called immediately without first calling DragSourceEndedAt to cancel a
        drag operation. If the web view is both the drag source and the drag
        target then all DragTarget* methods should be called before DragSource*
        mthods.
        This method is only used when window rendering is disabled.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.DragSourceSystemDragEnded()
        return None

    def set_accessibility_state(self, long long accessibility_state):
        """Set accessibility state for all frames. |accessibility_state| may be
        default, enabled or disabled. If |accessibility_state| is STATE_DEFAULT
        then accessibility will be disabled by default and the state may be
        further controlled with the \"force-renderer-accessibility\" and
        \"disable-renderer-accessibility\" command-line switches. If
        |accessibility_state| is STATE_ENABLED then accessibility will be enabled.
        If |accessibility_state| is STATE_DISABLED then accessibility will be
        completely disabled.

        For windowed browsers accessibility will be enabled in Complete mode
        (which corresponds to kAccessibilityModeComplete in Chromium). In this
        mode all platform accessibility objects will be created and managed by
        Chromium's internal implementation. The client needs only to detect the
        screen reader and call this method appropriately. For example, on macOS
        the client can handle the @\"AXEnhancedUserInterface\" accessibility
        attribute to detect VoiceOver state changes and on Windows the client can
        handle WM_GETOBJECT with OBJID_CLIENT to detect accessibility readers.

        For windowless browsers accessibility will be enabled in TreeOnly mode
        (which corresponds to kAccessibilityModeWebContentsOnly in Chromium). In
        this mode renderer accessibility is enabled, the full tree is computed,
        and events are passed to CefAccessibiltyHandler, but platform
        accessibility objects are not created. The client may implement platform
        accessibility objects using CefAccessibiltyHandler callbacks if desired.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SetAccessibilityState(<cef_state_t>accessibility_state)
        return None

    def set_auto_resize_enabled(self, bint enabled, min_size, max_size):
        """Enable notifications of auto resize via CefDisplayHandler::OnAutoResize.
        Notifications are disabled by default. |min_size| and |max_size| define
        the range of allowed sizes.
        """
        cdef CefSize _a1
        cdef CefSize _a2
        cdef CefBrowserHost* _p = self._ptr()
        _g_to_Size(min_size, &_a1)
        _g_to_Size(max_size, &_a2)
        with nogil:
            _p.SetAutoResizeEnabled(enabled, _a1, _a2)
        return None

    def set_audio_muted(self, bint mute):
        """Set whether the browser's audio is muted."""
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SetAudioMuted(mute)
        return None

    def is_audio_muted(self):
        """Returns true if the browser's audio is muted.  This method can only be
        called on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsAudioMuted()
        return _r

    def is_fullscreen(self):
        """Returns true if the renderer is currently in browser fullscreen. This
        differs from window fullscreen in that browser fullscreen is entered using
        the JavaScript Fullscreen API and modifies CSS attributes such as the
        ::backdrop pseudo-element and :fullscreen pseudo-class. This method can
        only be called on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsFullscreen()
        return _r

    def exit_fullscreen(self, bint will_cause_resize):
        """Requests the renderer to exit browser fullscreen. In most cases exiting
        window fullscreen should also exit browser fullscreen. With Alloy
        style this method should be called in response to a user action such as
        clicking the green traffic light button on MacOS
        (CefWindowDelegate::OnWindowFullscreenTransition callback) or pressing the
        \"ESC\" key (CefKeyboardHandler::OnPreKeyEvent callback). With Chrome
        style these standard exit actions are handled internally but
        new/additional user actions can use this method. Set |will_cause_resize|
        to true if exiting browser fullscreen will cause a view resize.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.ExitFullscreen(will_cause_resize)
        return None

    def can_execute_chrome_command(self, int command_id):
        """Returns true if a Chrome command is supported and enabled. Use the
        cef_id_for_command_id_name() function for version-safe mapping of command
        IDC names from cef_command_ids.h to version-specific numerical
        |command_id| values. This method can only be called on the UI thread. Only
        used with Chrome style.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.CanExecuteChromeCommand(command_id)
        return _r

    def execute_chrome_command(self, int command_id, long long disposition):
        """Execute a Chrome command. Use the cef_id_for_command_id_name()
        function for version-safe mapping of command IDC names from
        cef_command_ids.h to version-specific numerical |command_id| values.
        |disposition| provides information about the intended command target. Only
        used with Chrome style.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.ExecuteChromeCommand(command_id, <cef_window_open_disposition_t>disposition)
        return None

    def is_render_process_unresponsive(self):
        """Returns true if the render process associated with this browser is
        currently unresponsive as indicated by a lack of input event processing
        for at least 15 seconds. To receive associated state change notifications
        and optionally handle an unresponsive render process implement
        CefRequestHandler::OnRenderProcessUnresponsive. This method can only be
        called on the UI thread.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsRenderProcessUnresponsive()
        return _r

    def get_runtime_style(self):
        """Returns the runtime style for this browser (ALLOY or CHROME). See
        cef_runtime_style_t documentation for details.
        """
        cdef CefBrowserHost* _p = self._ptr()
        cdef cef_runtime_style_t _r
        with nogil:
            _r = _p.GetRuntimeStyle()
        return _g_enum(_types.RuntimeStyle, <int>_r)

    def set_ax_viewport_collapse(self, bint enabled):
        """Enable or disable CDP accessibility tree viewport collapse for this
        browser. When enabled, off-screen landmarks and headings are serialized
        as summaries and other off-screen nodes are pruned. Overrides the
        CefBrowserSettings.ax_viewport_collapse value. If called on the UI thread
        the change will be applied immediately. Otherwise, the change will be
        applied asynchronously on the UI thread.
        WARNING: This collapses the CDP accessibility tree and disables CDP
        dynamic tree updates (nodesUpdated events). The DevTools Accessibility
        panel will show an incomplete tree. Platform screen readers (NVDA, JAWS,
        VoiceOver) are unaffected - they use a separate code path.
        """
        cdef CefBrowserHost* _p = self._ptr()
        with nogil:
            _p.SetAxViewportCollapse(enabled)
        return None

    @staticmethod
    def get_browser_by_identifier(int browser_id):
        """Returns the browser (if any) with the specified identifier."""
        cdef CefRefPtr[CefBrowser] _r
        with nogil:
            _r = CefBrowserHost.GetBrowserByIdentifier(browser_id)
        return _wrap_Browser(_r)


cdef object _wrap_BrowserHost(CefRefPtr[CefBrowserHost] ref):
    cdef BrowserHost obj
    if ref.get() == NULL:
        return None
    obj = BrowserHost.__new__(BrowserHost)
    obj._ref = ref
    return obj


class DownloadImageCallback:
    """Callback interface for CefBrowserHost::DownloadImage. The methods of this
    class will be called on the browser process UI thread.
    """

    def on_download_image_finished(self, image_url, http_status_code, image):
        """Method that will be executed when the image download has completed.
        |image_url| is the URL that was downloaded and |http_status_code| is the
        resulting HTTP status code. |image| is the resulting image, possibly at
        multiple scale factors, or empty if the download failed.
        """
        return None


cdef void _DownloadImageCallback_on_download_image_finished(void* py, const CefString* image_url, int http_status_code, CefImage* image) noexcept with gil:
    try:
        _r = (<object>py).on_download_image_finished(_g_str(image_url[0]), http_status_code, _wrap_Image(CefRefPtr[CefImage](image)))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefDownloadImageCallback] _g_make_DownloadImageCallback(object obj) except *:
    cdef CefRefPtr[CefDownloadImageCallback] ref
    cdef CwDownloadImageCallbackCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, DownloadImageCallback):
        raise TypeError("expected a DownloadImageCallback or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_download_image_finished", None) is not DownloadImageCallback.on_download_image_finished:
        cb.fn_on_download_image_finished = _DownloadImageCallback_on_download_image_finished
    ref = CefRefPtr[CefDownloadImageCallback](<CefDownloadImageCallback*>new CwDownloadImageCallbackProxy(cb))
    return ref


cdef inline CefDownloadImageCallback* _g_export_DownloadImageCallback(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefDownloadImageCallback] ref = _g_make_DownloadImageCallback(obj)
    cdef CefDownloadImageCallback* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


class PdfPrintCallback:
    """Callback interface for CefBrowserHost::PrintToPDF. The methods of this class
    will be called on the browser process UI thread.
    """

    def on_pdf_print_finished(self, path, ok):
        """Method that will be executed when the PDF printing has completed. |path|
        is the output path. |ok| will be true if the printing completed
        successfully or false otherwise.
        """
        return None


cdef void _PdfPrintCallback_on_pdf_print_finished(void* py, const CefString* path, cpp_bool ok) noexcept with gil:
    try:
        _r = (<object>py).on_pdf_print_finished(_g_str(path[0]), ok)
    except BaseException:
        _g_report()


cdef CefRefPtr[CefPdfPrintCallback] _g_make_PdfPrintCallback(object obj) except *:
    cdef CefRefPtr[CefPdfPrintCallback] ref
    cdef CwPdfPrintCallbackCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, PdfPrintCallback):
        raise TypeError("expected a PdfPrintCallback or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_pdf_print_finished", None) is not PdfPrintCallback.on_pdf_print_finished:
        cb.fn_on_pdf_print_finished = _PdfPrintCallback_on_pdf_print_finished
    ref = CefRefPtr[CefPdfPrintCallback](<CefPdfPrintCallback*>new CwPdfPrintCallbackProxy(cb))
    return ref


cdef inline CefPdfPrintCallback* _g_export_PdfPrintCallback(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefPdfPrintCallback] ref = _g_make_PdfPrintCallback(obj)
    cdef CefPdfPrintCallback* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


class RunFileDialogCallback:
    """Callback interface for CefBrowserHost::RunFileDialog. The methods of this
    class will be called on the browser process UI thread.
    """

    def on_file_dialog_dismissed(self, file_paths):
        """Called asynchronously after the file dialog is dismissed.
        |file_paths| will be a single value or a list of values depending on the
        dialog mode. If the selection was cancelled |file_paths| will be empty.
        """
        return None


cdef void _RunFileDialogCallback_on_file_dialog_dismissed(void* py, const vector[CefString]* file_paths) noexcept with gil:
    try:
        _r = (<object>py).on_file_dialog_dismissed(_g_str_list(file_paths))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefRunFileDialogCallback] _g_make_RunFileDialogCallback(object obj) except *:
    cdef CefRefPtr[CefRunFileDialogCallback] ref
    cdef CwRunFileDialogCallbackCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, RunFileDialogCallback):
        raise TypeError("expected a RunFileDialogCallback or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_file_dialog_dismissed", None) is not RunFileDialogCallback.on_file_dialog_dismissed:
        cb.fn_on_file_dialog_dismissed = _RunFileDialogCallback_on_file_dialog_dismissed
    ref = CefRefPtr[CefRunFileDialogCallback](<CefRunFileDialogCallback*>new CwRunFileDialogCallbackProxy(cb))
    return ref


cdef inline CefRunFileDialogCallback* _g_export_RunFileDialogCallback(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefRunFileDialogCallback] ref = _g_make_RunFileDialogCallback(obj)
    cdef CefRunFileDialogCallback* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


