# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class Textfield(View):
    """A Textfield supports editing of text. This control is custom rendered with
    no platform-specific code. Methods must be called on the browser process UI
    thread unless otherwise indicated.
    """

    cdef CefTextfield* _ptr_CefTextfield(self) except NULL:
        cdef CefTextfield* p = <CefTextfield*>self._ref.get()
        if p == NULL:
            raise RuntimeError("Textfield has no CEF object")
        return p

    def set_password_input(self, bint password_input):
        """Sets whether the text will be displayed as asterisks."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        with nogil:
            _p.SetPasswordInput(password_input)
        return None

    def is_password_input(self):
        """Returns true if the text will be displayed as asterisks."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsPasswordInput()
        return _r

    def set_read_only(self, bint read_only):
        """Sets whether the text will read-only."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        with nogil:
            _p.SetReadOnly(read_only)
        return None

    def is_read_only(self):
        """Returns true if the text is read-only."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsReadOnly()
        return _r

    def get_text(self):
        """Returns the currently displayed text."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef CefString _r
        with nogil:
            _r = _p.GetText()
        return _g_str(_r)

    def set_text(self, text):
        """Sets the contents to |text|. The cursor will be moved to end of the text
        if the current position is outside of the text range.
        """
        cdef CefString _a0
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _a0 = _g_cef(text)
        with nogil:
            _p.SetText(_a0)
        return None

    def append_text(self, text):
        """Appends |text| to the previously-existing text."""
        cdef CefString _a0
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _a0 = _g_cef(text)
        with nogil:
            _p.AppendText(_a0)
        return None

    def insert_or_replace_text(self, text):
        """Inserts |text| at the current cursor position replacing any selected text."""
        cdef CefString _a0
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _a0 = _g_cef(text)
        with nogil:
            _p.InsertOrReplaceText(_a0)
        return None

    def has_selection(self):
        """Returns true if there is any selected text."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef cpp_bool _r
        with nogil:
            _r = _p.HasSelection()
        return _r

    def get_selected_text(self):
        """Returns the currently selected text."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef CefString _r
        with nogil:
            _r = _p.GetSelectedText()
        return _g_str(_r)

    def select_all(self, bint reversed):
        """Selects all text. If |reversed| is true the range will end at the logical
        beginning of the text; this generally shows the leading portion of text
        that overflows its display area.
        """
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        with nogil:
            _p.SelectAll(reversed)
        return None

    def clear_selection(self):
        """Clears the text selection and sets the caret to the end."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        with nogil:
            _p.ClearSelection()
        return None

    def get_selected_range(self):
        """Returns the selected logical text range."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef CefRange _r
        with nogil:
            _r = _p.GetSelectedRange()
        return _g_from_Range(&_r)

    def select_range(self, range):
        """Selects the specified logical text range."""
        cdef CefRange _a0
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _g_to_Range(range, &_a0)
        with nogil:
            _p.SelectRange(_a0)
        return None

    def get_cursor_position(self):
        """Returns the current cursor position."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef size_t _r
        with nogil:
            _r = _p.GetCursorPosition()
        return _r

    def set_font_list(self, font_list):
        """Sets the font list. The format is \"<FONT_FAMILY_LIST>,[STYLES] <SIZE>\",
        where:
        - FONT_FAMILY_LIST is a comma-separated list of font family names,
        - STYLES is an optional space-separated list of style names
          (case-sensitive \"Bold\" and \"Italic\" are supported), and
        - SIZE is an integer font size in pixels with the suffix \"px\".

        Here are examples of valid font description strings:
        - \"Arial, Helvetica, Bold Italic 14px\"
        - \"Arial, 14px\"
        """
        cdef CefString _a0
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _a0 = _g_cef(font_list)
        with nogil:
            _p.SetFontList(_a0)
        return None

    def apply_text_color(self, cef_color_t color, range):
        """Applies |color| to the specified |range| without changing the default
        color. If |range| is empty the color will be set on the complete text
        contents.
        """
        cdef CefRange _a1
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _g_to_Range(range, &_a1)
        with nogil:
            _p.ApplyTextColor(color, _a1)
        return None

    def apply_text_style(self, long long style, bint add, range):
        """Applies |style| to the specified |range| without changing the default
        style. If |add| is true the style will be added, otherwise the style will
        be removed. If |range| is empty the style will be set on the complete text
        contents.
        """
        cdef CefRange _a2
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _g_to_Range(range, &_a2)
        with nogil:
            _p.ApplyTextStyle(<cef_text_style_t>style, add, _a2)
        return None

    def is_command_enabled(self, long long command_id):
        """Returns true if the action associated with the specified command id is
        enabled. See additional comments on ExecuteCommand().
        """
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef cpp_bool _r
        with nogil:
            _r = _p.IsCommandEnabled(<cef_text_field_commands_t>command_id)
        return _r

    def execute_command(self, long long command_id):
        """Performs the action associated with the specified command id."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        with nogil:
            _p.ExecuteCommand(<cef_text_field_commands_t>command_id)
        return None

    def clear_edit_history(self):
        """Clears Edit history."""
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        with nogil:
            _p.ClearEditHistory()
        return None

    def set_placeholder_text(self, text):
        """Sets the placeholder text that will be displayed when the Textfield is
        empty.
        """
        cdef CefString _a0
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _a0 = _g_cef(text)
        with nogil:
            _p.SetPlaceholderText(_a0)
        return None

    def get_placeholder_text(self):
        """Returns the placeholder text that will be displayed when the Textfield is
        empty.
        """
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        cdef CefString _r
        with nogil:
            _r = _p.GetPlaceholderText()
        return _g_str(_r)

    def set_accessible_name(self, name):
        """Set the accessible name that will be exposed to assistive technology (AT)."""
        cdef CefString _a0
        cdef CefTextfield* _p = self._ptr_CefTextfield()
        _a0 = _g_cef(name)
        with nogil:
            _p.SetAccessibleName(_a0)
        return None

    @staticmethod
    def create_textfield(delegate):
        """Create a new Textfield."""
        cdef CefRefPtr[CefTextfieldDelegate] _a0
        cdef CefRefPtr[CefTextfield] _r
        _a0 = _g_make_TextfieldDelegate(delegate)
        with nogil:
            _r = CefTextfield.CreateTextfield(_a0)
        return _wrap_Textfield(_r)


cdef object _wrap_Textfield(CefRefPtr[CefTextfield] ref):
    cdef Textfield obj
    if ref.get() == NULL:
        return None
    obj = Textfield.__new__(Textfield)
    obj._ref = CefRefPtr[CefView](<CefView*>ref.get())
    return obj


