# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class FileDialogCallback:
    """Callback interface for asynchronous continuation of file dialog requests."""
    cdef CefRefPtr[CefFileDialogCallback] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("FileDialogCallback objects are created by CEF or by a create() function")

    cdef CefFileDialogCallback* _ptr(self) except NULL:
        cdef CefFileDialogCallback* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("FileDialogCallback has no CEF object")
        return p

    def continue_(self, file_paths):
        """Continue the file selection. |file_paths| should be a single value or a
        list of values depending on the dialog mode. An empty |file_paths| value
        is treated the same as calling Cancel().
        """
        cdef vector[CefString] _a0
        cdef CefFileDialogCallback* _p = self._ptr()
        _g_str_vector(file_paths, _a0)
        with nogil:
            _p.Continue(_a0)
        return None

    def cancel(self):
        """Cancel the file selection."""
        cdef CefFileDialogCallback* _p = self._ptr()
        with nogil:
            _p.Cancel()
        return None


cdef object _wrap_FileDialogCallback(CefRefPtr[CefFileDialogCallback] ref):
    cdef FileDialogCallback obj
    if ref.get() == NULL:
        return None
    obj = FileDialogCallback.__new__(FileDialogCallback)
    obj._ref = ref
    return obj


class DialogHandler:
    """Implement this interface to handle dialog events. The methods of this class
    will be called on the browser process UI thread.
    """

    def on_file_dialog(self, browser, mode, title, default_file_path, accept_filters, accept_extensions, accept_descriptions, callback):
        """Called to run a file chooser dialog. |mode| represents the type of dialog
        to display. |title| to the title to be used for the dialog and may be
        empty to show the default title (\"Open\" or \"Save\" depending on the mode).
        |default_file_path| is the path with optional directory and/or file name
        component that should be initially selected in the dialog.
        |accept_filters| are used to restrict the selectable file types and may be
        any combination of valid lower-cased MIME types (e.g. \"text/*\" or
        \"image/*\") and individual file extensions (e.g. \".txt\" or \".png\").
        |accept_extensions| provides the semicolon-delimited expansion of MIME
        types to file extensions (if known, or empty string otherwise).
        |accept_descriptions| provides the descriptions for MIME types (if known,
        or empty string otherwise). For example, the \"image/*\" mime type might
        have extensions \".png;.jpg;.bmp;...\" and description \"Image Files\".
        |accept_filters|, |accept_extensions| and |accept_descriptions| will all
        be the same size. To display a custom dialog return true and execute
        |callback| either inline or at a later time. To display the default dialog
        return false. If this method returns false it may be called an additional
        time for the same dialog (both before and after MIME type expansion).
        """
        return False


cdef cpp_bool _DialogHandler_on_file_dialog(void* py, CefBrowser* browser, int mode, const CefString* title, const CefString* default_file_path, const vector[CefString]* accept_filters, const vector[CefString]* accept_extensions, const vector[CefString]* accept_descriptions, CefFileDialogCallback* callback) noexcept with gil:
    try:
        _r = (<object>py).on_file_dialog(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_enum(_types.FileDialogMode, mode), _g_str(title[0]), _g_str(default_file_path[0]), _g_str_list(accept_filters), _g_str_list(accept_extensions), _g_str_list(accept_descriptions), _wrap_FileDialogCallback(CefRefPtr[CefFileDialogCallback](callback)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0


cdef CefRefPtr[CefDialogHandler] _g_make_DialogHandler(object obj) except *:
    cdef CefRefPtr[CefDialogHandler] ref
    cdef CwDialogHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, DialogHandler):
        raise TypeError("expected a DialogHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_file_dialog", None) is not DialogHandler.on_file_dialog:
        cb.fn_on_file_dialog = _DialogHandler_on_file_dialog
    ref = CefRefPtr[CefDialogHandler](<CefDialogHandler*>new CwDialogHandlerProxy(cb))
    return ref


cdef inline CefDialogHandler* _g_export_DialogHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefDialogHandler] ref = _g_make_DialogHandler(obj)
    cdef CefDialogHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


