# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class SchemeHandlerFactory:
    """Class that creates CefResourceHandler instances for handling scheme
    requests. The methods of this class will always be called on the IO thread.
    """

    def create(self, browser, frame, scheme_name, request):
        """Return a new resource handler instance to handle the request or an empty
        reference to allow default handling of the request. |browser| and |frame|
        will be the browser window and frame respectively that originated the
        request or NULL if the request did not originate from a browser window
        (for example, if the request came from CefURLRequest). The |request|
        object passed to this method cannot be modified.
        """
        return None


cdef CefResourceHandler* _SchemeHandlerFactory_create(void* py, CefBrowser* browser, CefFrame* frame, const CefString* scheme_name, CefRequest* request) noexcept with gil:
    try:
        _r = (<object>py).create(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), _g_str(scheme_name[0]), _wrap_Request(CefRefPtr[CefRequest](request)))
        _r0 = _r
        return _g_export_ResourceHandler(_r0)
    except BaseException:
        _g_report()
        return NULL


cdef CefRefPtr[CefSchemeHandlerFactory] _g_make_SchemeHandlerFactory(object obj) except *:
    cdef CefRefPtr[CefSchemeHandlerFactory] ref
    cdef CwSchemeHandlerFactoryCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, SchemeHandlerFactory):
        raise TypeError("expected a SchemeHandlerFactory or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "create", None) is not SchemeHandlerFactory.create:
        cb.fn_create = _SchemeHandlerFactory_create
    ref = CefRefPtr[CefSchemeHandlerFactory](<CefSchemeHandlerFactory*>new CwSchemeHandlerFactoryProxy(cb))
    return ref


cdef inline CefSchemeHandlerFactory* _g_export_SchemeHandlerFactory(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefSchemeHandlerFactory] ref = _g_make_SchemeHandlerFactory(obj)
    cdef CefSchemeHandlerFactory* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_SchemeHandlerFactory(CefRefPtr[CefSchemeHandlerFactory] ref):
    """The Python object that was given to CEF as this SchemeHandlerFactory (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfSchemeHandlerFactory(ref.get())
    if py == NULL:
        return None
    return <object>py


