# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class SSLInfo:
    """Class representing SSL information."""
    cdef CefRefPtr[CefSSLInfo] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("SSLInfo objects are created by CEF or by a create() function")

    cdef CefSSLInfo* _ptr(self) except NULL:
        cdef CefSSLInfo* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("SSLInfo has no CEF object")
        return p

    def get_cert_status(self):
        """Returns a bitmask containing any and all problems verifying the server
        certificate.
        """
        cdef CefSSLInfo* _p = self._ptr()
        cdef cef_cert_status_t _r
        with nogil:
            _r = _p.GetCertStatus()
        return _g_enum(_types.CertStatus, <int>_r)


cdef object _wrap_SSLInfo(CefRefPtr[CefSSLInfo] ref):
    cdef SSLInfo obj
    if ref.get() == NULL:
        return None
    obj = SSLInfo.__new__(SSLInfo)
    obj._ref = ref
    return obj


