# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class PrintDialogCallback:
    """Callback interface for asynchronous continuation of print dialog requests."""
    cdef CefRefPtr[CefPrintDialogCallback] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("PrintDialogCallback objects are created by CEF or by a create() function")

    cdef CefPrintDialogCallback* _ptr(self) except NULL:
        cdef CefPrintDialogCallback* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("PrintDialogCallback has no CEF object")
        return p

    def continue_(self, PrintSettings settings not None):
        """Continue printing with the specified |settings|."""
        cdef CefRefPtr[CefPrintSettings] _a0
        cdef CefPrintDialogCallback* _p = self._ptr()
        _a0 = settings._ref
        with nogil:
            _p.Continue(_a0)
        return None

    def cancel(self):
        """Cancel the printing."""
        cdef CefPrintDialogCallback* _p = self._ptr()
        with nogil:
            _p.Cancel()
        return None


cdef object _wrap_PrintDialogCallback(CefRefPtr[CefPrintDialogCallback] ref):
    cdef PrintDialogCallback obj
    if ref.get() == NULL:
        return None
    obj = PrintDialogCallback.__new__(PrintDialogCallback)
    obj._ref = ref
    return obj


cdef inline CefPrintDialogCallback* _g_ref_PrintDialogCallback(object obj) except? NULL:
    """A reference for CEF to keep (a PrintDialogCallback that a handler method returns; None: nothing)."""
    cdef PrintDialogCallback typed
    cdef CefRefPtr[CefPrintDialogCallback] ref
    cdef CefPrintDialogCallback* raw
    if obj is None:
        return NULL
    if not isinstance(obj, PrintDialogCallback):
        raise TypeError("expected a PrintDialogCallback or None, not %s" % type(obj).__name__)
    typed = <PrintDialogCallback>obj
    ref = typed._ref
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef class PrintJobCallback:
    """Callback interface for asynchronous continuation of print job requests."""
    cdef CefRefPtr[CefPrintJobCallback] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("PrintJobCallback objects are created by CEF or by a create() function")

    cdef CefPrintJobCallback* _ptr(self) except NULL:
        cdef CefPrintJobCallback* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("PrintJobCallback has no CEF object")
        return p

    def continue_(self):
        """Indicate completion of the print job."""
        cdef CefPrintJobCallback* _p = self._ptr()
        with nogil:
            _p.Continue()
        return None


cdef object _wrap_PrintJobCallback(CefRefPtr[CefPrintJobCallback] ref):
    cdef PrintJobCallback obj
    if ref.get() == NULL:
        return None
    obj = PrintJobCallback.__new__(PrintJobCallback)
    obj._ref = ref
    return obj


cdef inline CefPrintJobCallback* _g_ref_PrintJobCallback(object obj) except? NULL:
    """A reference for CEF to keep (a PrintJobCallback that a handler method returns; None: nothing)."""
    cdef PrintJobCallback typed
    cdef CefRefPtr[CefPrintJobCallback] ref
    cdef CefPrintJobCallback* raw
    if obj is None:
        return NULL
    if not isinstance(obj, PrintJobCallback):
        raise TypeError("expected a PrintJobCallback or None, not %s" % type(obj).__name__)
    typed = <PrintJobCallback>obj
    ref = typed._ref
    raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


class PrintHandler:
    """Implement this interface to handle printing on Linux. Each browser will have
    only one print job in progress at a time. The methods of this class will be
    called on the browser process UI thread.
    """

    def on_print_start(self, browser):
        """Called when printing has started for the specified |browser|. This method
        will be called before the other OnPrint*() methods and irrespective of how
        printing was initiated (e.g. CefBrowserHost::Print(), JavaScript
        window.print() or PDF extension print button).
        """
        return None

    def on_print_settings(self, browser, settings, get_defaults):
        """Synchronize |settings| with client state. If |get_defaults| is true then
        populate |settings| with the default print settings. Do not keep a
        reference to |settings| outside of this callback.
        """
        return None

    def on_print_dialog(self, browser, has_selection, callback):
        """Show the print dialog. Execute |callback| once the dialog is dismissed.
        Return true if the dialog will be displayed or false to cancel the
        printing immediately.
        """
        return False

    def on_print_job(self, browser, document_name, pdf_file_path, callback):
        """Send the print job to the printer. Execute |callback| once the job is
        completed. Return true if the job will proceed or false to cancel the job
        immediately.
        """
        return False

    def on_print_reset(self, browser):
        """Reset client state related to printing."""
        return None

    def get_pdf_paper_size(self, browser, device_units_per_inch):
        """Return the PDF paper size in device units. Used in combination with
        CefBrowserHost::PrintToPDF().
        """
        return Size()


cdef void _PrintHandler_on_print_start(void* py, CefBrowser* browser) noexcept with gil:
    try:
        _r = (<object>py).on_print_start(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
    except BaseException:
        _g_report()

cdef void _PrintHandler_on_print_settings(void* py, CefBrowser* browser, CefPrintSettings* settings, cpp_bool get_defaults) noexcept with gil:
    try:
        _r = (<object>py).on_print_settings(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_PrintSettings(CefRefPtr[CefPrintSettings](settings)), get_defaults)
    except BaseException:
        _g_report()

cdef cpp_bool _PrintHandler_on_print_dialog(void* py, CefBrowser* browser, cpp_bool has_selection, CefPrintDialogCallback* callback) noexcept with gil:
    try:
        _r = (<object>py).on_print_dialog(_wrap_Browser(CefRefPtr[CefBrowser](browser)), has_selection, _wrap_PrintDialogCallback(CefRefPtr[CefPrintDialogCallback](callback)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _PrintHandler_on_print_job(void* py, CefBrowser* browser, const CefString* document_name, const CefString* pdf_file_path, CefPrintJobCallback* callback) noexcept with gil:
    try:
        _r = (<object>py).on_print_job(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_str(document_name[0]), _g_str(pdf_file_path[0]), _wrap_PrintJobCallback(CefRefPtr[CefPrintJobCallback](callback)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _PrintHandler_on_print_reset(void* py, CefBrowser* browser) noexcept with gil:
    try:
        _r = (<object>py).on_print_reset(_wrap_Browser(CefRefPtr[CefBrowser](browser)))
    except BaseException:
        _g_report()

cdef void _PrintHandler_get_pdf_paper_size(void* py, CefBrowser* browser, int device_units_per_inch, CefSize* result) noexcept with gil:
    try:
        _r = (<object>py).get_pdf_paper_size(_wrap_Browser(CefRefPtr[CefBrowser](browser)), device_units_per_inch)
        _r0 = _r
        _g_to_Size(_r0, result)
    except BaseException:
        _g_report()


cdef CefRefPtr[CefPrintHandler] _g_make_PrintHandler(object obj) except *:
    cdef CefRefPtr[CefPrintHandler] ref
    cdef CwPrintHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, PrintHandler):
        raise TypeError("expected a PrintHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_print_start", None) is not PrintHandler.on_print_start:
        cb.fn_on_print_start = _PrintHandler_on_print_start
    if getattr(cls, "on_print_settings", None) is not PrintHandler.on_print_settings:
        cb.fn_on_print_settings = _PrintHandler_on_print_settings
    if getattr(cls, "on_print_dialog", None) is not PrintHandler.on_print_dialog:
        cb.fn_on_print_dialog = _PrintHandler_on_print_dialog
    if getattr(cls, "on_print_job", None) is not PrintHandler.on_print_job:
        cb.fn_on_print_job = _PrintHandler_on_print_job
    if getattr(cls, "on_print_reset", None) is not PrintHandler.on_print_reset:
        cb.fn_on_print_reset = _PrintHandler_on_print_reset
    if getattr(cls, "get_pdf_paper_size", None) is not PrintHandler.get_pdf_paper_size:
        cb.fn_get_pdf_paper_size = _PrintHandler_get_pdf_paper_size
    ref = CefRefPtr[CefPrintHandler](<CefPrintHandler*>new CwPrintHandlerProxy(cb))
    return ref


cdef inline CefPrintHandler* _g_export_PrintHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefPrintHandler] ref = _g_make_PrintHandler(obj)
    cdef CefPrintHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_PrintHandler(CefRefPtr[CefPrintHandler] ref):
    """The Python object that was given to CEF as this PrintHandler (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfPrintHandler(ref.get())
    if py == NULL:
        return None
    return <object>py


