# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class RequestContextHandler:
    """Implement this interface to provide handler implementations. The handler
    instance will not be released until all objects related to the context have
    been destroyed.
    """

    def on_request_context_initialized(self, request_context):
        """Called on the browser process UI thread immediately after the request
        context has been initialized.
        """
        return None

    def get_resource_request_handler(self, browser, frame, request, is_navigation, is_download, request_initiator):
        """Called on the browser process IO thread before a resource request is
        initiated. The |browser| and |frame| values represent the source of the
        request, and may be NULL for requests originating from service workers or
        CefURLRequest. |request| represents the request contents and cannot be
        modified in this callback. |is_navigation| will be true if the resource
        request is a navigation. |is_download| will be true if the resource
        request is a download. |request_initiator| is the origin (scheme + domain)
        of the page that initiated the request. Set |disable_default_handling| to
        true to disable default handling of the request, in which case it will
        need to be handled via CefResourceRequestHandler::GetResourceHandler or it
        will be canceled. To allow the resource load to proceed with default
        handling return NULL. To specify a handler for the resource return a
        CefResourceRequestHandler object. This method will not be called if the
        client associated with |browser| returns a non-NULL value from
        CefRequestHandler::GetResourceRequestHandler for the same request
        (identified by CefRequest::GetIdentifier). For worker requests without an
        associated frame or process handler, an arbitrary non-NULL handler from
        the contexts sharing the same storage will be used.
        """
        return None, False


cdef void _RequestContextHandler_on_request_context_initialized(void* py, CefRequestContext* request_context) noexcept with gil:
    try:
        _r = (<object>py).on_request_context_initialized(_wrap_RequestContext(CefRefPtr[CefRequestContext](request_context)))
    except BaseException:
        _g_report()

cdef CefResourceRequestHandler* _RequestContextHandler_get_resource_request_handler(void* py, CefBrowser* browser, CefFrame* frame, CefRequest* request, cpp_bool is_navigation, cpp_bool is_download, const CefString* request_initiator, cpp_bool* disable_default_handling) noexcept with gil:
    try:
        _r = (<object>py).get_resource_request_handler(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_Frame(CefRefPtr[CefFrame](frame)), _wrap_Request(CefRefPtr[CefRequest](request)), is_navigation, is_download, _g_str(request_initiator[0]))
        _r0, _r1 = _r
        disable_default_handling[0] = _r1
        return _g_export_ResourceRequestHandler(_r0)
    except BaseException:
        _g_report()
        return NULL


cdef CefRefPtr[CefRequestContextHandler] _g_make_RequestContextHandler(object obj) except *:
    cdef CefRefPtr[CefRequestContextHandler] ref
    cdef CwRequestContextHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, RequestContextHandler):
        raise TypeError("expected a RequestContextHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_request_context_initialized", None) is not RequestContextHandler.on_request_context_initialized:
        cb.fn_on_request_context_initialized = _RequestContextHandler_on_request_context_initialized
    if getattr(cls, "get_resource_request_handler", None) is not RequestContextHandler.get_resource_request_handler:
        cb.fn_get_resource_request_handler = _RequestContextHandler_get_resource_request_handler
    ref = CefRefPtr[CefRequestContextHandler](<CefRequestContextHandler*>new CwRequestContextHandlerProxy(cb))
    return ref


cdef inline CefRequestContextHandler* _g_export_RequestContextHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefRequestContextHandler] ref = _g_make_RequestContextHandler(obj)
    cdef CefRequestContextHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_RequestContextHandler(CefRefPtr[CefRequestContextHandler] ref):
    """The Python object that was given to CEF as this RequestContextHandler (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfRequestContextHandler(ref.get())
    if py == NULL:
        return None
    return <object>py


