# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

cdef class BeforeDownloadCallback:
    """Callback interface used to asynchronously continue a download."""
    cdef CefRefPtr[CefBeforeDownloadCallback] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("BeforeDownloadCallback objects are created by CEF or by a create() function")

    cdef CefBeforeDownloadCallback* _ptr(self) except NULL:
        cdef CefBeforeDownloadCallback* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("BeforeDownloadCallback has no CEF object")
        return p

    def continue_(self, download_path, bint show_dialog):
        """Call to continue the download. Set |download_path| to the full file path
        for the download including the file name or leave blank to use the
        suggested name and the default temp directory. Set |show_dialog| to true
        if you do wish to show the default \"Save As\" dialog.
        """
        cdef CefString _a0
        cdef CefBeforeDownloadCallback* _p = self._ptr()
        if download_path is not None:
            _a0 = _g_cef(download_path)
        with nogil:
            _p.Continue(_a0, show_dialog)
        return None


cdef object _wrap_BeforeDownloadCallback(CefRefPtr[CefBeforeDownloadCallback] ref):
    cdef BeforeDownloadCallback obj
    if ref.get() == NULL:
        return None
    obj = BeforeDownloadCallback.__new__(BeforeDownloadCallback)
    obj._ref = ref
    return obj


cdef class DownloadItemCallback:
    """Callback interface used to asynchronously cancel a download."""
    cdef CefRefPtr[CefDownloadItemCallback] _ref

    def __dealloc__(self):
        if _cef_was_shut_down:
            _g_forget(<void*>&self._ref)

    def __init__(self):
        raise TypeError("DownloadItemCallback objects are created by CEF or by a create() function")

    cdef CefDownloadItemCallback* _ptr(self) except NULL:
        cdef CefDownloadItemCallback* p = self._ref.get()
        if p == NULL:
            raise RuntimeError("DownloadItemCallback has no CEF object")
        return p

    def cancel(self):
        """Call to cancel the download."""
        cdef CefDownloadItemCallback* _p = self._ptr()
        with nogil:
            _p.Cancel()
        return None

    def pause(self):
        """Call to pause the download."""
        cdef CefDownloadItemCallback* _p = self._ptr()
        with nogil:
            _p.Pause()
        return None

    def resume(self):
        """Call to resume the download."""
        cdef CefDownloadItemCallback* _p = self._ptr()
        with nogil:
            _p.Resume()
        return None


cdef object _wrap_DownloadItemCallback(CefRefPtr[CefDownloadItemCallback] ref):
    cdef DownloadItemCallback obj
    if ref.get() == NULL:
        return None
    obj = DownloadItemCallback.__new__(DownloadItemCallback)
    obj._ref = ref
    return obj


class DownloadHandler:
    """Class used to handle file downloads. The methods of this class will called
    on the browser process UI thread.
    """

    def can_download(self, browser, url, request_method):
        """Called before a download begins in response to a user-initiated action
        (e.g. alt + link click or link click that returns a `Content-Disposition:
        attachment` response from the server). |url| is the target download URL
        and |request_method| is the target method (GET, POST, etc). Return true to
        proceed with the download or false to cancel the download. This method is
        not called for downloads initiated by CefBrowserHost::StartDownload().
        """
        return False

    def on_before_download(self, browser, download_item, suggested_name, callback):
        """Called before a download begins. |suggested_name| is the suggested name
        for the download file. Return true and execute |callback| either
        asynchronously or in this method to continue the download. Return false to
        proceed with default handling (cancel with Alloy style, default download
        handling with Chrome style). To cancel the download with either style
        execute the callback passed to OnDownloadUpdated(). If this method returns
        true and |callback| is destroyed without being executed, the download will
        be canceled. Do not keep a reference to |download_item| outside of this
        method.
        """
        return False

    def on_download_updated(self, browser, download_item, callback):
        """Called when a download's status or progress information has been updated.
        This may be called multiple times before and after OnBeforeDownload().
        Execute |callback| either asynchronously or in this method to cancel the
        download if desired. Do not keep a reference to |download_item| outside of
        this method.
        """
        return None


cdef cpp_bool _DownloadHandler_can_download(void* py, CefBrowser* browser, const CefString* url, const CefString* request_method) noexcept with gil:
    try:
        _r = (<object>py).can_download(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _g_str(url[0]), _g_str(request_method[0]))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef cpp_bool _DownloadHandler_on_before_download(void* py, CefBrowser* browser, CefDownloadItem* download_item, const CefString* suggested_name, CefBeforeDownloadCallback* callback) noexcept with gil:
    try:
        _r = (<object>py).on_before_download(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_DownloadItem(CefRefPtr[CefDownloadItem](download_item)), _g_str(suggested_name[0]), _wrap_BeforeDownloadCallback(CefRefPtr[CefBeforeDownloadCallback](callback)))
        _r0 = _r
        return _r0
    except BaseException:
        _g_report()
        return 0

cdef void _DownloadHandler_on_download_updated(void* py, CefBrowser* browser, CefDownloadItem* download_item, CefDownloadItemCallback* callback) noexcept with gil:
    try:
        _r = (<object>py).on_download_updated(_wrap_Browser(CefRefPtr[CefBrowser](browser)), _wrap_DownloadItem(CefRefPtr[CefDownloadItem](download_item)), _wrap_DownloadItemCallback(CefRefPtr[CefDownloadItemCallback](callback)))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefDownloadHandler] _g_make_DownloadHandler(object obj) except *:
    cdef CefRefPtr[CefDownloadHandler] ref
    cdef CwDownloadHandlerCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, DownloadHandler):
        raise TypeError("expected a DownloadHandler or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "can_download", None) is not DownloadHandler.can_download:
        cb.fn_can_download = _DownloadHandler_can_download
    if getattr(cls, "on_before_download", None) is not DownloadHandler.on_before_download:
        cb.fn_on_before_download = _DownloadHandler_on_before_download
    if getattr(cls, "on_download_updated", None) is not DownloadHandler.on_download_updated:
        cb.fn_on_download_updated = _DownloadHandler_on_download_updated
    ref = CefRefPtr[CefDownloadHandler](<CefDownloadHandler*>new CwDownloadHandlerProxy(cb))
    return ref


cdef inline CefDownloadHandler* _g_export_DownloadHandler(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefDownloadHandler] ref = _g_make_DownloadHandler(obj)
    cdef CefDownloadHandler* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


