# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

class EndTracingCallback:
    """Implement this interface to receive notification when tracing has completed.
    The methods of this class will be called on the browser process UI thread.
    """

    def on_end_tracing_complete(self, tracing_file):
        """Called after all processes have sent their trace data. |tracing_file| is
        the path at which tracing data was written. The client is responsible for
        deleting |tracing_file|.
        """
        return None


cdef void _EndTracingCallback_on_end_tracing_complete(void* py, const CefString* tracing_file) noexcept with gil:
    try:
        _r = (<object>py).on_end_tracing_complete(_g_str(tracing_file[0]))
    except BaseException:
        _g_report()


cdef CefRefPtr[CefEndTracingCallback] _g_make_EndTracingCallback(object obj) except *:
    cdef CefRefPtr[CefEndTracingCallback] ref
    cdef CwEndTracingCallbackCallbacks cb
    cdef type cls
    if obj is None:
        return ref
    if not isinstance(obj, EndTracingCallback):
        raise TypeError("expected a EndTracingCallback or None, not %s" % type(obj).__name__)
    cls = type(obj)
    Py_INCREF(obj)
    cb.py = <void*>obj
    cb.release = _g_release
    if getattr(cls, "on_end_tracing_complete", None) is not EndTracingCallback.on_end_tracing_complete:
        cb.fn_on_end_tracing_complete = _EndTracingCallback_on_end_tracing_complete
    ref = CefRefPtr[CefEndTracingCallback](<CefEndTracingCallback*>new CwEndTracingCallbackProxy(cb))
    return ref


cdef inline CefEndTracingCallback* _g_export_EndTracingCallback(object obj) except? NULL:
    """A reference for CEF to keep (the proxy calls Release() on it)."""
    cdef CefRefPtr[CefEndTracingCallback] ref = _g_make_EndTracingCallback(obj)
    cdef CefEndTracingCallback* raw = ref.get()
    if raw != NULL:
        raw.AddRef()
    return raw


cdef object _g_unexport_EndTracingCallback(CefRefPtr[CefEndTracingCallback] ref):
    """The Python object that was given to CEF as this EndTracingCallback (None: CEF's own, or none)."""
    cdef void* py
    if ref.get() == NULL:
        return None
    py = CwPyOfEndTracingCallback(ref.get())
    if py == NULL:
        return None
    return <object>py


