# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

# Forward declarations (the classes refer to each other)
cdef class AuthCallback
cdef class BeforeDownloadCallback
cdef class BinaryValue
cdef class Browser
cdef class BrowserHost
cdef class Callback
cdef class CommandLine
cdef class ContextMenuParams
cdef class CookieManager
cdef class DictionaryValue
cdef class Display
cdef class DownloadItem
cdef class DownloadItemCallback
cdef class DragData
cdef class FileDialogCallback
cdef class Frame
cdef class JSDialogCallback
cdef class ListValue
cdef class MediaAccessCallback
cdef class MenuModel
cdef class PermissionPromptCallback
cdef class PostData
cdef class PostDataElement
cdef class PrintDialogCallback
cdef class PrintJobCallback
cdef class PrintSettings
cdef class ProcessMessage
cdef class Registration
cdef class Request
cdef class RequestContext
cdef class ResourceReadCallback
cdef class ResourceSkipCallback
cdef class Response
cdef class RunContextMenuCallback
cdef class RunQuickMenuCallback
cdef class SSLInfo
cdef class StreamReader
cdef class StreamWriter
cdef class TaskManager
cdef class URLRequest
cdef class UnresponsiveProcessCallback
cdef class Value
cdef class ZipReader
