# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

def register_scheme_handler_factory(scheme_name, domain_name, factory):
    """Register a scheme handler factory with the global request context. An empty
    |domain_name| value for a standard scheme will cause the factory to match
    all domain names. The |domain_name| value will be ignored for non-standard
    schemes. If |scheme_name| is a built-in scheme and no handler is returned by
    |factory| then the built-in scheme handler factory will be called. If
    |scheme_name| is a custom scheme then you must also implement the
    CefApp::OnRegisterCustomSchemes() method in all processes. This function may
    be called multiple times to change or remove the factory that matches the
    specified |scheme_name| and optional |domain_name|. Returns false if an
    error occurs. This function may be called on any thread in the browser
    process. Using this function is equivalent to calling
    CefRequestContext::GetGlobalContext()->RegisterSchemeHandlerFactory().
    """
    cdef CefString _a0
    cdef CefString _a1
    cdef CefRefPtr[CefSchemeHandlerFactory] _a2
    cdef cpp_bool _r
    _a0 = _g_cef(scheme_name)
    if domain_name is not None:
        _a1 = _g_cef(domain_name)
    _a2 = _g_make_SchemeHandlerFactory(factory)
    with nogil:
        _r = CefRegisterSchemeHandlerFactory(_a0, _a1, _a2)
    return _r


def clear_scheme_handler_factories():
    """Clear all scheme handler factories registered with the global request
    context. Returns false on error. This function may be called on any thread
    in the browser process. Using this function is equivalent to calling
    CefRequestContext::GetGlobalContext()->ClearSchemeHandlerFactories().
    """
    cdef cpp_bool _r
    with nogil:
        _r = CefClearSchemeHandlerFactories()
    return _r


def get_mime_type(extension):
    """Returns the mime type for the specified file extension or an empty string if
    unknown.
    """
    cdef CefString _a0
    cdef CefString _r
    _a0 = _g_cef(extension)
    with nogil:
        _r = CefGetMimeType(_a0)
    return _g_str(_r)


def post_task(long long thread_id, task):
    """Post a task for execution on the specified thread. Equivalent to
    using CefTaskRunner::GetForThread(threadId)->PostTask(task).
    """
    cdef CefRefPtr[CefTask] _a1
    cdef cpp_bool _r
    if task is None:
        raise TypeError("task must not be None")
    _a1 = _g_make_Task(task)
    with nogil:
        _r = CefPostTask(<cef_thread_id_t>thread_id, _a1)
    return _r


def post_delayed_task(long long thread_id, task, int64_t delay_ms):
    """Post a task for delayed execution on the specified thread. Equivalent to
    using CefTaskRunner::GetForThread(threadId)->PostDelayedTask(task,
    delay_ms).
    """
    cdef CefRefPtr[CefTask] _a1
    cdef cpp_bool _r
    if task is None:
        raise TypeError("task must not be None")
    _a1 = _g_make_Task(task)
    with nogil:
        _r = CefPostDelayedTask(<cef_thread_id_t>thread_id, _a1, delay_ms)
    return _r


def currently_on(long long thread_id):
    """Returns true if called on the specified thread. Equivalent to using
    CefTaskRunner::GetForThread(threadId)->BelongsToCurrentThread().
    """
    cdef cpp_bool _r
    with nogil:
        _r = CefCurrentlyOn(<cef_thread_id_t>thread_id)
    return _r


def add_cross_origin_whitelist_entry(source_origin, target_protocol, target_domain, bint allow_target_subdomains):
    """Add an entry to the cross-origin access whitelist.

    The same-origin policy restricts how scripts hosted from different origins
    (scheme + domain + port) can communicate. By default, scripts can only
    access resources with the same origin. Scripts hosted on the HTTP and HTTPS
    schemes (but no other schemes) can use the \"Access-Control-Allow-Origin\"
    header to allow cross-origin requests. For example,
    https://source.example.com can make XMLHttpRequest requests on
    http://target.example.com if the http://target.example.com request returns
    an \"Access-Control-Allow-Origin: https://source.example.com\" response
    header.

    Scripts in separate frames or iframes and hosted from the same protocol and
    domain suffix can execute cross-origin JavaScript if both pages set the
    document.domain value to the same domain suffix. For example,
    scheme://foo.example.com and scheme://bar.example.com can communicate using
    JavaScript if both domains set document.domain=\"example.com\".

    This method is used to allow access to origins that would otherwise violate
    the same-origin policy. Scripts hosted underneath the fully qualified
    |source_origin| URL (like http://www.example.com) will be allowed access to
    all resources hosted on the specified |target_protocol| and |target_domain|.
    If |target_domain| is non-empty and |allow_target_subdomains| is false only
    exact domain matches will be allowed. If |target_domain| contains a top-
    level domain component (like \"example.com\") and |allow_target_subdomains| is
    true sub-domain matches will be allowed. If |target_domain| is empty and
    |allow_target_subdomains| if true all domains and IP addresses will be
    allowed.

    This method cannot be used to bypass the restrictions on local or display
    isolated schemes. See the comments on CefRegisterCustomScheme for more
    information.

    This function may be called on any thread. Returns false if |source_origin|
    is invalid or the whitelist cannot be accessed.
    """
    cdef CefString _a0
    cdef CefString _a1
    cdef CefString _a2
    cdef cpp_bool _r
    _a0 = _g_cef(source_origin)
    _a1 = _g_cef(target_protocol)
    if target_domain is not None:
        _a2 = _g_cef(target_domain)
    with nogil:
        _r = CefAddCrossOriginWhitelistEntry(_a0, _a1, _a2, allow_target_subdomains)
    return _r


def remove_cross_origin_whitelist_entry(source_origin, target_protocol, target_domain, bint allow_target_subdomains):
    """Remove an entry from the cross-origin access whitelist. Returns false if
    |source_origin| is invalid or the whitelist cannot be accessed.
    """
    cdef CefString _a0
    cdef CefString _a1
    cdef CefString _a2
    cdef cpp_bool _r
    _a0 = _g_cef(source_origin)
    _a1 = _g_cef(target_protocol)
    if target_domain is not None:
        _a2 = _g_cef(target_domain)
    with nogil:
        _r = CefRemoveCrossOriginWhitelistEntry(_a0, _a1, _a2, allow_target_subdomains)
    return _r


def clear_cross_origin_whitelist():
    """Remove all entries from the cross-origin access whitelist. Returns false if
    the whitelist cannot be accessed.
    """
    cdef cpp_bool _r
    with nogil:
        _r = CefClearCrossOriginWhitelist()
    return _r


def is_cert_status_error(long long status):
    """Returns true if the certificate status represents an error."""
    cdef cpp_bool _r
    with nogil:
        _r = CefIsCertStatusError(<cef_cert_status_t>status)
    return _r


def format_url_for_security_display(origin_url):
    """This is a convenience function for formatting a URL in a concise and human-
    friendly way to help users make security-related decisions (or in other
    circumstances when people need to distinguish sites, origins, or otherwise-
    simplified URLs from each other). Internationalized domain names (IDN) may
    be presented in Unicode if the conversion is considered safe. The returned
    value will (a) omit the path for standard schemes, excepting file and
    filesystem, and (b) omit the port if it is the default for the scheme. Do
    not use this for URLs which will be parsed or sent to other applications.
    """
    cdef CefString _a0
    cdef CefString _r
    _a0 = _g_cef(origin_url)
    with nogil:
        _r = CefFormatUrlForSecurityDisplay(_a0)
    return _g_str(_r)


def get_extensions_for_mime_type(mime_type):
    """Get the extensions associated with the given mime type. This should be
    passed in lower case. There could be multiple extensions for a given mime
    type, like \"html,htm\" for \"text/html\", or \"txt,text,html,...\" for \"text/*\".
    Any existing elements in the provided vector will not be erased.
    """
    cdef CefString _a0
    cdef vector[CefString] _a1
    _a0 = _g_cef(mime_type)
    with nogil:
        CefGetExtensionsForMimeType(_a0, _a1)
    return _g_str_list(&_a1)


def load_crl_sets_file(path):
    """Loads the existing \"Certificate Revocation Lists\" file that is managed by
    Google Chrome. This file can generally be found in Chrome's User Data
    directory (e.g. \"C:\\Users\\[User]\\AppData\\Local\\Google\\Chrome\\User Data\\\" on
    Windows) and is updated periodically by Chrome's component updater service.
    Must be called in the browser process after the context has been
    initialized. See https://dev.chromium.org/Home/chromium-security/crlsets for
    background.
    """
    cdef CefString _a0
    _a0 = _g_cef(path)
    with nogil:
        CefLoadCRLSetsFile(_a0)
    return None


def begin_tracing(categories, callback):
    """Start tracing events on all processes. Tracing is initialized asynchronously
    and |callback| will be executed on the UI thread after initialization is
    complete.

    If CefBeginTracing was called previously, or if a CefEndTracingAsync call is
    pending, CefBeginTracing will fail and return false.

    |categories| is a comma-delimited list of category wildcards. A category can
    have an optional '-' prefix to make it an excluded category. Having both
    included and excluded categories in the same list is not supported.

    Examples:
    - \"test_MyTest*\"
    - \"test_MyTest*,test_OtherStuff\"
    - \"-excluded_category1,-excluded_category2\"

    This function must be called on the browser process UI thread.
    """
    cdef CefString _a0
    cdef CefRefPtr[CefCompletionCallback] _a1
    cdef cpp_bool _r
    if categories is not None:
        _a0 = _g_cef(categories)
    _a1 = _g_make_CompletionCallback(callback)
    with nogil:
        _r = CefBeginTracing(_a0, _a1)
    return _r


def end_tracing(tracing_file, callback):
    """Stop tracing events on all processes.

    This function will fail and return false if a previous call to
    CefEndTracingAsync is already pending or if CefBeginTracing was not called.

    |tracing_file| is the path at which tracing data will be written and
    |callback| is the callback that will be executed once all processes have
    sent their trace data. If |tracing_file| is empty a new temporary file path
    will be used. If |callback| is empty no trace data will be written.

    This function must be called on the browser process UI thread.
    """
    cdef CefString _a0
    cdef CefRefPtr[CefEndTracingCallback] _a1
    cdef cpp_bool _r
    if tracing_file is not None:
        _a0 = _g_cef(tracing_file)
    _a1 = _g_make_EndTracingCallback(callback)
    with nogil:
        _r = CefEndTracing(_a0, _a1)
    return _r


def set_crash_key_value(key, value):
    """Sets or clears a specific key-value pair from the crash metadata."""
    cdef CefString _a0
    cdef CefString _a1
    _a0 = _g_cef(key)
    if value is not None:
        _a1 = _g_cef(value)
    with nogil:
        CefSetCrashKeyValue(_a0, _a1)
    return None


def crash_reporting_enabled():
    """Crash reporting is configured using an INI-style config file named
    \"crash_reporter.cfg\". On Windows and Linux this file must be placed next to
    the main application executable. On macOS this file must be placed in the
    top-level app bundle Resources directory (e.g.
    \"<appname>.app/Contents/Resources\"). File contents are as follows:

    <pre>
     # Comments start with a hash character and must be on their own line.

     [Config]
     ProductName=<Value of the \"prod\" crash key; defaults to \"cef\">
     ProductVersion=<Value of the \"ver\" crash key; defaults to the CEF version>
     AppName=<Windows only; App-specific folder name component for storing crash
              information; default to \"CEF\">
     ExternalHandler=<Windows only; Name of the external handler exe to use
                      instead of re-launching the main exe; default to empty>
     BrowserCrashForwardingEnabled=<macOS only; True if browser process crashes
                                    should be forwarded to the system crash
                                    reporter; default to false>
     ServerURL=<crash server URL; default to empty>
     RateLimitEnabled=<True if uploads should be rate limited; default to true>
     MaxUploadsPerDay=<Max uploads per 24 hours, used if rate limit is enabled;
                       default to 5>
     MaxDatabaseSizeInMb=<Total crash report disk usage greater than this value
                          will cause older reports to be deleted; default to 20>
     MaxDatabaseAgeInDays=<Crash reports older than this value will be deleted;
                           default to 5>

     [CrashKeys]
     my_key1=<small|medium|large>
     my_key2=<small|medium|large>
    </pre>

    <b>Config section:</b>

    If \"ProductName\" and/or \"ProductVersion\" are set then the specified values
    will be included in the crash dump metadata. On macOS if these values are
    set to empty then they will be retrieved from the Info.plist file using the
    \"CFBundleName\" and \"CFBundleShortVersionString\" keys respectively.

    If \"AppName\" is set on Windows then crash report information (metrics,
    database and dumps) will be stored locally on disk under the
    \"C:\\Users\\[CurrentUser]\\AppData\\Local\\[AppName]\\User Data\" folder. On other
    platforms the cef_settings_t.root_cache_path value will be used.

    If \"ExternalHandler\" is set on Windows then the specified exe will be
    launched as the crashpad-handler instead of re-launching the main process
    exe. The value can be an absolute path or a path relative to the main exe
    directory. On Linux the cef_settings_t.browser_subprocess_path value will be
    used. On macOS the existing subprocess app bundle will be used.

    If \"BrowserCrashForwardingEnabled\" is set to true on macOS then browser
    process crashes will be forwarded to the system crash reporter. This results
    in the crash UI dialog being displayed to the user and crash reports being
    logged under \"~/Library/Logs/DiagnosticReports\". Forwarding of crash reports
    from non-browser processes and Debug builds is always disabled.

    If \"ServerURL\" is set then crashes will be uploaded as a multi-part POST
    request to the specified URL. Otherwise, reports will only be stored locally
    on disk.

    If \"RateLimitEnabled\" is set to true then crash report uploads will be rate
    limited as follows:
     1. If \"MaxUploadsPerDay\" is set to a positive value then at most the
        specified number of crashes will be uploaded in each 24 hour period.
     2. If crash upload fails due to a network or server error then an
        incremental backoff delay up to a maximum of 24 hours will be applied
        for retries.
     3. If a backoff delay is applied and \"MaxUploadsPerDay\" is > 1 then the
        \"MaxUploadsPerDay\" value will be reduced to 1 until the client is
        restarted. This helps to avoid an upload flood when the network or
        server error is resolved.
    Rate limiting is not supported on Linux.

    If \"MaxDatabaseSizeInMb\" is set to a positive value then crash report
    storage on disk will be limited to that size in megabytes. For example, on
    Windows each dump is about 600KB so a \"MaxDatabaseSizeInMb\" value of 20
    equates to about 34 crash reports stored on disk. Not supported on Linux.

    If \"MaxDatabaseAgeInDays\" is set to a positive value then crash reports
    older than the specified age in days will be deleted. Not supported on
    Linux.

    <b>CrashKeys section:</b>

    A maximum of 26 crash keys of each size can be specified for use by the
    application. Crash key values will be truncated based on the specified size
    (small = 64 bytes, medium = 256 bytes, large = 1024 bytes). The value of
    crash keys can be set from any thread or process using the
    CefSetCrashKeyValue function. These key/value pairs will be sent to the
    crash server along with the crash dump file.
    """
    cdef cpp_bool _r
    with nogil:
        _r = CefCrashReportingEnabled()
    return _r


def is_rtl():
    """Returns true if the application text direction is right-to-left."""
    if not _cef_started:
        raise RuntimeError("is_rtl() can only be called after CefApp.initialize()")
    cdef cpp_bool _r
    with nogil:
        _r = CefIsRTL()
    return _r


def get_path(long long key):
    """Retrieve the path associated with the specified |key|. Returns true on
    success. Can be called on any thread in the browser process.
    """
    cdef CefString _a1
    cdef cpp_bool _r
    with nogil:
        _r = CefGetPath(<cef_path_key_t>key, _a1)
    return (_r, _g_str(_a1))


def now_from_system_trace_time():
    """Returns the current system trace time or, if none is defined, the current
    high-res time. Can be used by clients to synchronize with the time
    information in trace events.
    """
    cdef int64_t _r
    with nogil:
        _r = CefNowFromSystemTraceTime()
    return _r


