# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

# Value type structs: the named tuples are defined in cefweaver/types/structs.py
from cefweaver.types import AcceleratedPaintNativePixmapPlane, AudioParameters, BrowserSettings, Cookie, Insets, KeyEvent, LinuxWindowProperties, MediaSinkDeviceInfo, MouseEvent, PdfPrintSettings, Point, PopupFeatures, Range, Rect, RequestContextSettings, ScreenInfo, Size, TaskInfo, TouchEvent, TouchHandleState, URLParts, AcceleratedPaintInfoCommon, BoxLayoutSettings, CompositionUnderline, DraggableRegion, AcceleratedPaintInfo

cdef inline object _g_from_AcceleratedPaintNativePixmapPlane(const CefAcceleratedPaintNativePixmapPlane* value):
    return AcceleratedPaintNativePixmapPlane(value.stride, value.offset, value.size, value.fd)


cdef inline object _g_from_AudioParameters(const CefAudioParameters* value):
    return AudioParameters(_g_enum(_types.ChannelLayout, value.channel_layout), value.sample_rate, value.frames_per_buffer)


cdef inline int _g_to_AudioParameters(object obj, CefAudioParameters* out) except -1:
    try:
        _f0, _f1, _f2 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a AudioParameters (or a sequence of 3 values), not %r" % (obj,)) from None
    out.channel_layout = <cef_channel_layout_t><int>_f0
    out.sample_rate = _f1
    out.frames_per_buffer = _f2
    return 0


cdef inline object _g_from_BrowserSettings(const CefBrowserSettings* value):
    return BrowserSettings(value.windowless_frame_rate, _g_string_field(&value.standard_font_family), _g_string_field(&value.fixed_font_family), _g_string_field(&value.serif_font_family), _g_string_field(&value.sans_serif_font_family), _g_string_field(&value.cursive_font_family), _g_string_field(&value.fantasy_font_family), value.default_font_size, value.default_fixed_font_size, value.minimum_font_size, value.minimum_logical_font_size, _g_string_field(&value.default_encoding), _g_enum(_types.State, value.remote_fonts), _g_enum(_types.State, value.javascript), _g_enum(_types.State, value.javascript_close_windows), _g_enum(_types.State, value.javascript_access_clipboard), _g_enum(_types.State, value.javascript_dom_paste), _g_enum(_types.State, value.image_loading), _g_enum(_types.State, value.image_shrink_standalone_to_fit), _g_enum(_types.State, value.text_area_resize), _g_enum(_types.State, value.tab_to_links), _g_enum(_types.State, value.local_storage), _g_enum(_types.State, value.webgl), value.background_color, _g_enum(_types.State, value.chrome_status_bubble), _g_enum(_types.State, value.chrome_zoom_bubble))


cdef inline int _g_to_BrowserSettings(object obj, CefBrowserSettings* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8, _f9, _f10, _f11, _f12, _f13, _f14, _f15, _f16, _f17, _f18, _f19, _f20, _f21, _f22, _f23, _f24, _f25 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a BrowserSettings (or a sequence of 26 values), not %r" % (obj,)) from None
    out.windowless_frame_rate = _f0
    _g_set_string_field(&out.standard_font_family, _f1)
    _g_set_string_field(&out.fixed_font_family, _f2)
    _g_set_string_field(&out.serif_font_family, _f3)
    _g_set_string_field(&out.sans_serif_font_family, _f4)
    _g_set_string_field(&out.cursive_font_family, _f5)
    _g_set_string_field(&out.fantasy_font_family, _f6)
    out.default_font_size = _f7
    out.default_fixed_font_size = _f8
    out.minimum_font_size = _f9
    out.minimum_logical_font_size = _f10
    _g_set_string_field(&out.default_encoding, _f11)
    out.remote_fonts = <cef_state_t><int>_f12
    out.javascript = <cef_state_t><int>_f13
    out.javascript_close_windows = <cef_state_t><int>_f14
    out.javascript_access_clipboard = <cef_state_t><int>_f15
    out.javascript_dom_paste = <cef_state_t><int>_f16
    out.image_loading = <cef_state_t><int>_f17
    out.image_shrink_standalone_to_fit = <cef_state_t><int>_f18
    out.text_area_resize = <cef_state_t><int>_f19
    out.tab_to_links = <cef_state_t><int>_f20
    out.local_storage = <cef_state_t><int>_f21
    out.webgl = <cef_state_t><int>_f22
    out.background_color = _f23
    out.chrome_status_bubble = <cef_state_t><int>_f24
    out.chrome_zoom_bubble = <cef_state_t><int>_f25
    return 0


cdef inline object _g_from_Cookie(const CefCookie* value):
    return Cookie(_g_string_field(&value.name), _g_string_field(&value.value), _g_string_field(&value.domain), _g_string_field(&value.path), value.secure, value.httponly, _g_from_basetime(value.creation.val), _g_from_basetime(value.last_access.val), value.has_expires, _g_from_basetime(value.expires.val), _g_enum(_types.CookieSameSite, value.same_site), _g_enum(_types.CookiePriority, value.priority))


cdef inline int _g_to_Cookie(object obj, CefCookie* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8, _f9, _f10, _f11 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a Cookie (or a sequence of 12 values), not %r" % (obj,)) from None
    _g_set_string_field(&out.name, _f0)
    _g_set_string_field(&out.value, _f1)
    _g_set_string_field(&out.domain, _f2)
    _g_set_string_field(&out.path, _f3)
    out.secure = _f4
    out.httponly = _f5
    out.creation.val = _g_to_basetime(_f6)
    out.last_access.val = _g_to_basetime(_f7)
    out.has_expires = _f8
    out.expires.val = _g_to_basetime(_f9)
    out.same_site = <cef_cookie_same_site_t><int>_f10
    out.priority = <cef_cookie_priority_t><int>_f11
    return 0


cdef inline object _g_from_Insets(const CefInsets* value):
    return Insets(value.top, value.left, value.bottom, value.right)


cdef inline int _g_to_Insets(object obj, CefInsets* out) except -1:
    try:
        _f0, _f1, _f2, _f3 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a Insets (or a sequence of 4 values), not %r" % (obj,)) from None
    out.top = _f0
    out.left = _f1
    out.bottom = _f2
    out.right = _f3
    return 0


cdef inline object _g_from_KeyEvent(const CefKeyEvent* value):
    return KeyEvent(_g_enum(_types.KeyEventType, value.type), value.modifiers, value.windows_key_code, value.native_key_code, value.is_system_key, value.character, value.unmodified_character, value.focus_on_editable_field)


cdef inline int _g_to_KeyEvent(object obj, CefKeyEvent* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a KeyEvent (or a sequence of 8 values), not %r" % (obj,)) from None
    out.type = <cef_key_event_type_t><int>_f0
    out.modifiers = _f1
    out.windows_key_code = _f2
    out.native_key_code = _f3
    out.is_system_key = _f4
    out.character = _f5
    out.unmodified_character = _f6
    out.focus_on_editable_field = _f7
    return 0


cdef inline object _g_from_LinuxWindowProperties(const CefLinuxWindowProperties* value):
    return LinuxWindowProperties(_g_string_field(&value.wayland_app_id), _g_string_field(&value.wm_class_class), _g_string_field(&value.wm_class_name), _g_string_field(&value.wm_role_name))


cdef inline int _g_to_LinuxWindowProperties(object obj, CefLinuxWindowProperties* out) except -1:
    try:
        _f0, _f1, _f2, _f3 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a LinuxWindowProperties (or a sequence of 4 values), not %r" % (obj,)) from None
    _g_set_string_field(&out.wayland_app_id, _f0)
    _g_set_string_field(&out.wm_class_class, _f1)
    _g_set_string_field(&out.wm_class_name, _f2)
    _g_set_string_field(&out.wm_role_name, _f3)
    return 0


cdef inline object _g_from_MediaSinkDeviceInfo(const CefMediaSinkDeviceInfo* value):
    return MediaSinkDeviceInfo(_g_string_field(&value.ip_address), value.port, _g_string_field(&value.model_name))


cdef inline int _g_to_MediaSinkDeviceInfo(object obj, CefMediaSinkDeviceInfo* out) except -1:
    try:
        _f0, _f1, _f2 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a MediaSinkDeviceInfo (or a sequence of 3 values), not %r" % (obj,)) from None
    _g_set_string_field(&out.ip_address, _f0)
    out.port = _f1
    _g_set_string_field(&out.model_name, _f2)
    return 0


cdef inline object _g_from_MouseEvent(const CefMouseEvent* value):
    return MouseEvent(value.x, value.y, value.modifiers)


cdef inline int _g_to_MouseEvent(object obj, CefMouseEvent* out) except -1:
    try:
        _f0, _f1, _f2 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a MouseEvent (or a sequence of 3 values), not %r" % (obj,)) from None
    out.x = _f0
    out.y = _f1
    out.modifiers = _f2
    return 0


cdef inline object _g_from_PdfPrintSettings(const CefPdfPrintSettings* value):
    return PdfPrintSettings(value.landscape, value.print_background, value.scale, value.paper_width, value.paper_height, value.prefer_css_page_size, _g_enum(_types.PdfPrintMarginType, value.margin_type), value.margin_top, value.margin_right, value.margin_bottom, value.margin_left, _g_string_field(&value.page_ranges), value.display_header_footer, _g_string_field(&value.header_template), _g_string_field(&value.footer_template), value.generate_tagged_pdf, value.generate_document_outline)


cdef inline int _g_to_PdfPrintSettings(object obj, CefPdfPrintSettings* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8, _f9, _f10, _f11, _f12, _f13, _f14, _f15, _f16 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a PdfPrintSettings (or a sequence of 17 values), not %r" % (obj,)) from None
    out.landscape = _f0
    out.print_background = _f1
    out.scale = _f2
    out.paper_width = _f3
    out.paper_height = _f4
    out.prefer_css_page_size = _f5
    out.margin_type = <cef_pdf_print_margin_type_t><int>_f6
    out.margin_top = _f7
    out.margin_right = _f8
    out.margin_bottom = _f9
    out.margin_left = _f10
    _g_set_string_field(&out.page_ranges, _f11)
    out.display_header_footer = _f12
    _g_set_string_field(&out.header_template, _f13)
    _g_set_string_field(&out.footer_template, _f14)
    out.generate_tagged_pdf = _f15
    out.generate_document_outline = _f16
    return 0


cdef inline object _g_from_Point(const CefPoint* value):
    return Point(value.x, value.y)


cdef inline int _g_to_Point(object obj, CefPoint* out) except -1:
    try:
        _f0, _f1 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a Point (or a sequence of 2 values), not %r" % (obj,)) from None
    out.x = _f0
    out.y = _f1
    return 0


cdef inline object _g_from_PopupFeatures(const CefPopupFeatures* value):
    return PopupFeatures(value.x, value.x_set, value.y, value.y_set, value.width, value.width_set, value.height, value.height_set, value.is_popup)


cdef inline int _g_to_PopupFeatures(object obj, CefPopupFeatures* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a PopupFeatures (or a sequence of 9 values), not %r" % (obj,)) from None
    out.x = _f0
    out.x_set = _f1
    out.y = _f2
    out.y_set = _f3
    out.width = _f4
    out.width_set = _f5
    out.height = _f6
    out.height_set = _f7
    out.is_popup = _f8
    return 0


cdef inline object _g_from_Range(const CefRange* value):
    return Range(value.from_, value.to)


cdef inline int _g_to_Range(object obj, CefRange* out) except -1:
    try:
        _f0, _f1 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a Range (or a sequence of 2 values), not %r" % (obj,)) from None
    out.from_ = _f0
    out.to = _f1
    return 0


cdef inline object _g_from_Rect(const CefRect* value):
    return Rect(value.x, value.y, value.width, value.height)


cdef inline int _g_to_Rect(object obj, CefRect* out) except -1:
    try:
        _f0, _f1, _f2, _f3 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a Rect (or a sequence of 4 values), not %r" % (obj,)) from None
    out.x = _f0
    out.y = _f1
    out.width = _f2
    out.height = _f3
    return 0


cdef inline object _g_from_RequestContextSettings(const CefRequestContextSettings* value):
    return RequestContextSettings(_g_string_field(&value.cache_path), value.persist_session_cookies, _g_string_field(&value.accept_language_list), _g_string_field(&value.cookieable_schemes_list), value.cookieable_schemes_exclude_defaults)


cdef inline int _g_to_RequestContextSettings(object obj, CefRequestContextSettings* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a RequestContextSettings (or a sequence of 5 values), not %r" % (obj,)) from None
    _g_set_string_field(&out.cache_path, _f0)
    out.persist_session_cookies = _f1
    _g_set_string_field(&out.accept_language_list, _f2)
    _g_set_string_field(&out.cookieable_schemes_list, _f3)
    out.cookieable_schemes_exclude_defaults = _f4
    return 0


cdef inline object _g_from_ScreenInfo(const CefScreenInfo* value):
    return ScreenInfo(value.device_scale_factor, value.depth, value.depth_per_component, value.is_monochrome, _g_from_Rect(<const CefRect*>&value.rect), _g_from_Rect(<const CefRect*>&value.available_rect))


cdef inline int _g_to_ScreenInfo(object obj, CefScreenInfo* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a ScreenInfo (or a sequence of 6 values), not %r" % (obj,)) from None
    out.device_scale_factor = _f0
    out.depth = _f1
    out.depth_per_component = _f2
    out.is_monochrome = _f3
    _g_to_Rect(_f4, <CefRect*>&out.rect)
    _g_to_Rect(_f5, <CefRect*>&out.available_rect)
    return 0


cdef inline object _g_from_Size(const CefSize* value):
    return Size(value.width, value.height)


cdef inline int _g_to_Size(object obj, CefSize* out) except -1:
    try:
        _f0, _f1 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a Size (or a sequence of 2 values), not %r" % (obj,)) from None
    out.width = _f0
    out.height = _f1
    return 0


cdef inline object _g_from_TaskInfo(const CefTaskInfo* value):
    return TaskInfo(value.id, _g_enum(_types.TaskType, value.type), value.is_killable, _g_string_field(&value.title), value.cpu_usage, value.number_of_processors, value.memory, value.gpu_memory, value.is_gpu_memory_inflated)


cdef inline int _g_to_TaskInfo(object obj, CefTaskInfo* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a TaskInfo (or a sequence of 9 values), not %r" % (obj,)) from None
    out.id = _f0
    out.type = <cef_task_type_t><int>_f1
    out.is_killable = _f2
    _g_set_string_field(&out.title, _f3)
    out.cpu_usage = _f4
    out.number_of_processors = _f5
    out.memory = _f6
    out.gpu_memory = _f7
    out.is_gpu_memory_inflated = _f8
    return 0


cdef inline object _g_from_TouchEvent(const CefTouchEvent* value):
    return TouchEvent(value.id, value.x, value.y, value.radius_x, value.radius_y, value.rotation_angle, value.pressure, _g_enum(_types.TouchEventType, value.type), value.modifiers, _g_enum(_types.PointerType, value.pointer_type))


cdef inline int _g_to_TouchEvent(object obj, CefTouchEvent* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8, _f9 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a TouchEvent (or a sequence of 10 values), not %r" % (obj,)) from None
    out.id = _f0
    out.x = _f1
    out.y = _f2
    out.radius_x = _f3
    out.radius_y = _f4
    out.rotation_angle = _f5
    out.pressure = _f6
    out.type = <cef_touch_event_type_t><int>_f7
    out.modifiers = _f8
    out.pointer_type = <cef_pointer_type_t><int>_f9
    return 0


cdef inline object _g_from_TouchHandleState(const CefTouchHandleState* value):
    return TouchHandleState(value.touch_handle_id, value.flags, value.enabled, _g_enum(_types.HorizontalAlignment, value.orientation), value.mirror_vertical, value.mirror_horizontal, _g_from_Point(<const CefPoint*>&value.origin), value.alpha)


cdef inline int _g_to_TouchHandleState(object obj, CefTouchHandleState* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a TouchHandleState (or a sequence of 8 values), not %r" % (obj,)) from None
    out.touch_handle_id = _f0
    out.flags = _f1
    out.enabled = _f2
    out.orientation = <cef_horizontal_alignment_t><int>_f3
    out.mirror_vertical = _f4
    out.mirror_horizontal = _f5
    _g_to_Point(_f6, <CefPoint*>&out.origin)
    out.alpha = _f7
    return 0


cdef inline object _g_from_URLParts(const CefURLParts* value):
    return URLParts(_g_string_field(&value.spec), _g_string_field(&value.scheme), _g_string_field(&value.username), _g_string_field(&value.password), _g_string_field(&value.host), _g_string_field(&value.port), _g_string_field(&value.origin), _g_string_field(&value.path), _g_string_field(&value.query), _g_string_field(&value.fragment))


cdef inline int _g_to_URLParts(object obj, CefURLParts* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8, _f9 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a URLParts (or a sequence of 10 values), not %r" % (obj,)) from None
    _g_set_string_field(&out.spec, _f0)
    _g_set_string_field(&out.scheme, _f1)
    _g_set_string_field(&out.username, _f2)
    _g_set_string_field(&out.password, _f3)
    _g_set_string_field(&out.host, _f4)
    _g_set_string_field(&out.port, _f5)
    _g_set_string_field(&out.origin, _f6)
    _g_set_string_field(&out.path, _f7)
    _g_set_string_field(&out.query, _f8)
    _g_set_string_field(&out.fragment, _f9)
    return 0


cdef inline object _g_from_AcceleratedPaintInfoCommon(const CefAcceleratedPaintInfoCommon* value):
    return AcceleratedPaintInfoCommon(value.timestamp, _g_from_Size(<const CefSize*>&value.coded_size), _g_from_Rect(<const CefRect*>&value.visible_rect), _g_from_Rect(<const CefRect*>&value.content_rect), _g_from_Size(<const CefSize*>&value.source_size), _g_from_Rect(<const CefRect*>&value.capture_update_rect), _g_from_Rect(<const CefRect*>&value.region_capture_rect), value.capture_counter, value.has_capture_update_rect, value.has_region_capture_rect, value.has_source_size, value.has_capture_counter)


cdef inline object _g_from_BoxLayoutSettings(const CefBoxLayoutSettings* value):
    return BoxLayoutSettings(value.horizontal, value.inside_border_horizontal_spacing, value.inside_border_vertical_spacing, _g_from_Insets(<const CefInsets*>&value.inside_border_insets), value.between_child_spacing, _g_enum(_types.AxisAlignment, value.main_axis_alignment), _g_enum(_types.AxisAlignment, value.cross_axis_alignment), value.minimum_cross_axis_size, value.default_flex)


cdef inline int _g_to_BoxLayoutSettings(object obj, CefBoxLayoutSettings* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4, _f5, _f6, _f7, _f8 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a BoxLayoutSettings (or a sequence of 9 values), not %r" % (obj,)) from None
    out.horizontal = _f0
    out.inside_border_horizontal_spacing = _f1
    out.inside_border_vertical_spacing = _f2
    _g_to_Insets(_f3, <CefInsets*>&out.inside_border_insets)
    out.between_child_spacing = _f4
    out.main_axis_alignment = <cef_axis_alignment_t><int>_f5
    out.cross_axis_alignment = <cef_axis_alignment_t><int>_f6
    out.minimum_cross_axis_size = _f7
    out.default_flex = _f8
    return 0


cdef inline object _g_from_CompositionUnderline(const CefCompositionUnderline* value):
    return CompositionUnderline(_g_from_Range(<const CefRange*>&value.range), value.color, value.background_color, value.thick, _g_enum(_types.CompositionUnderlineStyle, value.style))


cdef inline int _g_to_CompositionUnderline(object obj, CefCompositionUnderline* out) except -1:
    try:
        _f0, _f1, _f2, _f3, _f4 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a CompositionUnderline (or a sequence of 5 values), not %r" % (obj,)) from None
    _g_to_Range(_f0, <CefRange*>&out.range)
    out.color = _f1
    out.background_color = _f2
    out.thick = _f3
    out.style = <cef_composition_underline_style_t><int>_f4
    return 0


cdef inline object _g_from_DraggableRegion(const CefDraggableRegion* value):
    return DraggableRegion(_g_from_Rect(<const CefRect*>&value.bounds), value.draggable)


cdef inline int _g_to_DraggableRegion(object obj, CefDraggableRegion* out) except -1:
    try:
        _f0, _f1 = obj
    except (TypeError, ValueError):
        raise TypeError("expected a DraggableRegion (or a sequence of 2 values), not %r" % (obj,)) from None
    _g_to_Rect(_f0, <CefRect*>&out.bounds)
    out.draggable = _f1
    return 0


cdef inline object _g_from_AcceleratedPaintInfo(const CefAcceleratedPaintInfo* value):
    return AcceleratedPaintInfo(tuple([_g_from_AcceleratedPaintNativePixmapPlane(<const CefAcceleratedPaintNativePixmapPlane*>&value.planes[_i]) for _i in range(min(value.plane_count, 4))]), value.modifier, _g_enum(_types.ColorType, value.format), _g_from_AcceleratedPaintInfoCommon(<const CefAcceleratedPaintInfoCommon*>&value.extra))


