# Generated from CEF 154.0.34+g14c5a08+chromium-154.0.8037.98
# GENERATED by tools/gen/generate.py. DO NOT EDIT.

# Lists
cdef inline list _g_list_CompositionUnderline(const vector[CefCompositionUnderline]* values):
    cdef list result = []
    cdef size_t i
    for i in range(values.size()):
        result.append(_g_from_CompositionUnderline(&values[0][i]))
    return result


cdef inline int _g_vector_CompositionUnderline(object seq, vector[CefCompositionUnderline]& out) except -1:
    cdef CefCompositionUnderline item
    out.clear()
    for obj in seq:
        _g_to_CompositionUnderline(obj, &item)
        out.push_back(item)
    return 0


cdef inline list _g_list_Display(const vector[CefRefPtr[CefDisplay]]* values):
    cdef list result = []
    cdef size_t i
    for i in range(values.size()):
        result.append(_wrap_Display(values[0][i]))
    return result


cdef inline list _g_list_DraggableRegion(const vector[CefDraggableRegion]* values):
    cdef list result = []
    cdef size_t i
    for i in range(values.size()):
        result.append(_g_from_DraggableRegion(&values[0][i]))
    return result


cdef inline int _g_vector_DraggableRegion(object seq, vector[CefDraggableRegion]& out) except -1:
    cdef CefDraggableRegion item
    out.clear()
    for obj in seq:
        _g_to_DraggableRegion(obj, &item)
        out.push_back(item)
    return 0


cdef inline list _g_list_PostDataElement(const vector[CefRefPtr[CefPostDataElement]]* values):
    cdef list result = []
    cdef size_t i
    for i in range(values.size()):
        result.append(_wrap_PostDataElement(values[0][i]))
    return result


cdef inline list _g_list_Range(const vector[CefRange]* values):
    cdef list result = []
    cdef size_t i
    for i in range(values.size()):
        result.append(_g_from_Range(&values[0][i]))
    return result


cdef inline int _g_vector_Range(object seq, vector[CefRange]& out) except -1:
    cdef CefRange item
    out.clear()
    for obj in seq:
        _g_to_Range(obj, &item)
        out.push_back(item)
    return 0


cdef inline list _g_list_Rect(const vector[CefRect]* values):
    cdef list result = []
    cdef size_t i
    for i in range(values.size()):
        result.append(_g_from_Rect(&values[0][i]))
    return result


cdef inline int _g_vector_Rect(object seq, vector[CefRect]& out) except -1:
    cdef CefRect item
    out.clear()
    for obj in seq:
        _g_to_Rect(obj, &item)
        out.push_back(item)
    return 0


cdef inline list _g_list_int64_t(const vector[int64_t]* values):
    cdef list result = []
    cdef size_t i
    for i in range(values.size()):
        result.append(values[0][i])
    return result


cdef inline int _g_vector_int64_t(object seq, vector[int64_t]& out) except -1:
    out.clear()
    for item in seq:
        out.push_back(item)
    return 0


cdef inline int _g_str_vector(object seq, vector[CefString]& out) except -1:
    out.clear()
    for item in seq:
        out.push_back(_g_cef(item))
    return 0


